/*
DM PACK
created with:
python /workspace/home/himal.d/MatterProtocol/build-raspberrypi4-64-rdk-broadband/tmp/work/cortexa72-rdk-linux/ccsp-epon-agent/rdkb-2024q3-kirkstone+git999-r0/recipe-sysroot-native/usr/bin/dm_pack_code_gen.py /workspace/home/himal.d/MatterProtocol/meta-cmf/../rdkb/components/opensource/ccsp/CcspEPONAgent/config/TR181-EPON.XML /workspace/home/himal.d/MatterProtocol/meta-cmf/../rdkb/components/opensource/ccsp/CcspEPONAgent/source/EPONAgentSsp/dm_pack_datamodel.c
*/

#include "ansc_platform.h"
#include "ansc_xml_dom_parser_interface.h"
#include "dm_pack_xml_helper.h"
PVOID DMPackCreateDataModelXML(){
 PANSC_XML_DOM_NODE_OBJECT P0,P1,P2,P3,P4,P5;
 P0=DMPackCreatePNode(0,"dataModelInfo");
  P1=DMPackCreateNode(P0,"version","1",1);
  P1=DMPackCreateNode(P0,"moduleName","CCSP EPON Agent",15);
  P1=DMPackCreateNode(P0,"author","Fiber Optics",12);
  P1=DMPackCreateNode(P0,"description","COSA TR181 and extension for EPON",33);
  P1=DMPackCreatePNode(P0,"library");
   P2=DMPackCreateNode(P1,"path","libepon_tr181",13);
   P2=DMPackCreateNode(P1,"func_Init","COSA_Init",9);
   P2=DMPackCreateNode(P1,"func_Async_Init","COSA_Async_Init",15);
   P2=DMPackCreateNode(P1,"func_Unload","COSA_Unload",11);
   P2=DMPackCreateNode(P1,"func_MemoryCheck","COSA_MemoryCheck",16);
   P2=DMPackCreateNode(P1,"func_MemoryUsage","COSA_MemoryUsage",16);
   P2=DMPackCreateNode(P1,"func_MemoryTable","COSA_MemoryTable",16);
  P1=DMPackCreatePNode(P0,"objects");
   P2=DMPackCreateObject(P1, 0,"DPoE",0);
    DMPackCreateFunctions(P2,"DPoE",11,10,11,12,13,15,16,17,18,20,21,22);
    P3=DMPackCreatePNode(P2,"parameters");
     DMPackCreateParamTSW(P3,"Mac_address","string(64)","string",0);
     DMPackCreateW(P3,"NumberOfNetworkPorts",2,0);
     DMPackCreateW(P3,"NumberOfS1Interfaces",2,0);
     DMPackCreateW(P3,"ResetOnu",0,1);
     DMPackCreateW(P3,"DynamicMacAddressAgeLimit",2,0);
     DMPackCreateW(P3,"DynamicMacLearningTableSize",2,0);
     DMPackCreateW(P3,"MacLearningAggregateLimit",2,0);
     DMPackCreateW(P3,"ClearOnuLinkStatistics",0,1);
    P3=DMPackCreatePNode(P2,"objects");
     P4=DMPackCreateObject(P3, 0,"DPoE_FirmwareInfo",0);
      DMPackCreateFunctions(P4,"DPoE_FirmwareInfo",1,13);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParamTSW(P5,"bootVersion","string(64)","string",0);
       DMPackCreateParamTSW(P5,"bootCrc32","string(64)","string",0);
       DMPackCreateParamTSW(P5,"appVersion","string(64)","string",0);
       DMPackCreateParamTSW(P5,"appCrc32","string(64)","string",0);
     P4=DMPackCreateObject(P3, 0,"DPoE_ChipInfo",0);
      DMPackCreateFunctions(P4,"DPoE_ChipInfo",1,13);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParamTSW(P5,"jedecId","string(64)","string",0);
       DMPackCreateParamTSW(P5,"chipModel","string(64)","string",0);
       DMPackCreateParamTSW(P5,"chipVersion","string(64)","string",0);
     P4=DMPackCreateObject(P3, 0,"DPoE_ManufacturerInfo",0);
      DMPackCreateFunctions(P4,"DPoE_ManufacturerInfo",1,13);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParamTSW(P5,"info","string(64)","string",0);
       DMPackCreateParamTSW(P5,"organizationName","string(256)","string",0);
       DMPackCreateParamTSW(P5,"manufacturerDate","string(64)","string",0);
     P4=DMPackCreateObject(P3, 0,"DPoE_DeviceSysDescrInfo",0);
      DMPackCreateFunctions(P4,"DPoE_DeviceSysDescrInfo",1,13);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParamTSW(P5,"vendorName","string(64)","string",0);
       DMPackCreateParamTSW(P5,"modelNumber","string(64)","string",0);
       DMPackCreateParamTSW(P5,"hardwareVersion","string(64)","string",0);
     P4=DMPackCreateObject(P3, 0,"DPoE_OnuPacketBufferCapabilities",0);
      DMPackCreateFunctions(P4,"DPoE_OnuPacketBufferCapabilities",1,12);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"upstreamQueues",2,0);
       DMPackCreateW(P5,"upQueuesMaxPerLink",2,0);
       DMPackCreateW(P5,"upQueueIncrement",2,0);
       DMPackCreateW(P5,"downstreamQueues",2,0);
       DMPackCreateW(P5,"dnQueuesMaxPerPort",2,0);
       DMPackCreateW(P5,"dnQueueIncrement",2,0);
       DMPackCreateW(P5,"totalPacketBuffer",2,0);
       DMPackCreateW(P5,"dnPacketBuffer",2,0);
     P4=DMPackCreateObject(P3, 1,"DPoE_LlidForwardingState","32");
      DMPackCreateFunctions(P4,"DPoE_LlidForwardingState",4,0,2,12,10);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"link",2,0);
       DMPackCreateW(P5,"forwardingState",0,0);
     P4=DMPackCreateObject(P3, 1,"DPoE_OamFrameRate","32");
      DMPackCreateFunctions(P4,"DPoE_OamFrameRate",3,0,2,12);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"link",2,0);
       DMPackCreateW(P5,"maxRate",2,0);
       DMPackCreateW(P5,"minRate",2,0);
     P4=DMPackCreateObject(P3, 1,"DPoE_DynamicMacTable","32");
      DMPackCreateFunctions(P4,"DPoE_DynamicMacTable",4,0,2,12,13);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"link",2,0);
       DMPackCreateParamTSW(P5,"macAddress","string(64)","string",0);
     P4=DMPackCreateObject(P3, 1,"DPoE_StaticMacTable","32");
      DMPackCreateFunctions(P4,"DPoE_StaticMacTable",4,0,2,12,13);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"link",2,0);
       DMPackCreateParamTSW(P5,"macAddress","string(64)","string",0);
     P4=DMPackCreateObject(P3, 1,"DPoE_OnuLinkStatistics","32");
      DMPackCreateFunctions(P4,"DPoE_OnuLinkStatistics",3,0,2,12);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"rxUnicastFrames",2,0);
       DMPackCreateW(P5,"txUnicastFrames",2,0);
       DMPackCreateW(P5,"rxFrameTooShort",2,0);
       DMPackCreateW(P5,"rxFrame64",2,0);
       DMPackCreateW(P5,"rxFrame65_127",2,0);
       DMPackCreateW(P5,"rxFrame128_255",2,0);
       DMPackCreateW(P5,"rxFrame256_511",2,0);
       DMPackCreateW(P5,"rxFrame512_1023",2,0);
       DMPackCreateW(P5,"rxFrame1024_1518",2,0);
       DMPackCreateW(P5,"rxFrame1519_Plus",2,0);
       DMPackCreateW(P5,"txFrame64",2,0);
       DMPackCreateW(P5,"txFrame65_127",2,0);
       DMPackCreateW(P5,"txFrame128_255",2,0);
       DMPackCreateW(P5,"txFrame256_511",2,0);
       DMPackCreateW(P5,"txFrame512_1023",2,0);
       DMPackCreateW(P5,"txFrame_1024_1518",2,0);
       DMPackCreateW(P5,"txFrame_1519_Plus",2,0);
       DMPackCreateW(P5,"framesDropped",2,0);
       DMPackCreateW(P5,"bytesDropped",2,0);
       DMPackCreateW(P5,"opticalMonVcc",2,0);
       DMPackCreateW(P5,"opticalMonTxBiasCurrent",2,0);
       DMPackCreateW(P5,"opticalMonTxPower",2,0);
       DMPackCreateW(P5,"opticalMonRxPower",2,0);
   P2=DMPackCreateObject(P1, 0,"DeviceInfo",0);
    DMPackCreateFunctions(P2,"DeviceInfo",4,10,13,15,18);
    P3=DMPackCreatePNode(P2,"parameters");
     DMPackCreateParam(P3,"X_RDKCENTRAL-COM_FirmwareDownloadStatus",3);
     DMPackCreateParam(P3,"X_RDKCENTRAL-COM_FirmwareDownloadProtocol",3);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_FirmwareDownloadURL",3,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_FirmwareToDownload",3,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_FirmwareDownloadNow",0,1);
 return P0;
}
