/*
DM PACK
created with:
python /workspace/home/himal.d/MatterProtocol/build-raspberrypi4-64-rdk-broadband/tmp/work/cortexa72-rdk-linux/ccsp-moca/rdkb-2024q3-kirkstone+git999-r0/recipe-sysroot-native/usr/bin/dm_pack_code_gen.py /workspace/home/himal.d/MatterProtocol/meta-cmf/../rdkb/components/opensource/ccsp/CcspMoCA/config/TR181-MoCA.XML /workspace/home/himal.d/MatterProtocol/meta-cmf/../rdkb/components/opensource/ccsp/CcspMoCA/source/MoCASsp/dm_pack_datamodel.c
*/

#include "ansc_platform.h"
#include "ansc_xml_dom_parser_interface.h"
#include "dm_pack_xml_helper.h"
PVOID DMPackCreateDataModelXML(){
 PANSC_XML_DOM_NODE_OBJECT P0,P1,P2,P3,P4,P5,P6,P7,P8,P9;
 P0=DMPackCreatePNode(0,"dataModelInfo");
  P1=DMPackCreateNode(P0,"version","1",1);
  P1=DMPackCreateNode(P0,"moduleName","COSA_TR181_USGv2",16);
  P1=DMPackCreatePNode(P0,"author");
  P1=DMPackCreatePNode(P0,"description");
  P1=DMPackCreatePNode(P0,"library");
  P1=DMPackCreatePNode(P0,"objects");
   P2=DMPackCreateObject(P1, 0,"DeviceInfo",0);
    P3=DMPackCreatePNode(P2,"objects");
     P4=DMPackCreateObject(P3, 0,"X_RDKCENTRAL-COM_xOpsDeviceMgmt",0);
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 0,"Logging",0);
        DMPackCreateFunctions(P6,"Logging",7,10,12,15,17,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"xOpsDMMoCALogEnabled",0,1);
         DMPackCreateW(P7,"xOpsDMMoCALogPeriod",2,1);
   P2=DMPackCreateObject(P1, 0,"MoCA",0);
    DMPackCreateFunctions(P2,"MoCA",11,10,11,12,13,15,16,17,18,20,21,22);
    P3=DMPackCreatePNode(P2,"parameters");
     DMPackCreateParam(P3,"InterfaceNumberOfEntries",2);
     DMPackCreateParamTSW(P3,"X_CISCO_COM_ProvisioningFilename","string(128)","string",1);
     DMPackCreateParamTSW(P3,"X_CISCO_COM_ProvisioningServerAddressType","string: IPv4(1),IPv6(2)","uint32/mapped",1);
     DMPackCreateParamTSW(P3,"X_CISCO_COM_ProvisioningServerAddress","string(64)","string",1);
     DMPackCreateParam(P3,"MocaResetCount",2);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_MoCAHost_Sync",0,1);
     DMPackCreateW(P3,"Data",3,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_ForceEnable",0,1);
    P3=DMPackCreatePNode(P2,"objects");
     P4=DMPackCreateObject(P3, 0,"X_RDKCENTRAL-COM_xOpsDeviceMgmt",0);
      DMPackCreateFunctions(P4,"MoCAReset",2,10,15);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"Reset",0,1);
     P4=DMPackCreateObject(P3, 1,"Interface","128");
      DMPackCreateFunctions(P4,"Interface1",13,0,2,10,11,12,13,15,16,17,18,20,21,22);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"Enable",0,1);
       DMPackCreateParamTS(P5,"Status","string: Up(1),Down(2),Unknown(3),Dormant(4),NotPresent(5),LowerLayerDown(6),Error(7)","uint32/mapped");
       DMPackCreateParamTSW(P5,"Alias","string(64)","string",1);
       DMPackCreateParamTS(P5,"Name","string(64)","string");
       DMPackCreateN(P5,"LastChange",2,0);
       DMPackCreateParamTSW(P5,"LowerLayers","string(1024)","string",1);
       DMPackCreateParam(P5,"Upstream",0);
       DMPackCreateParam(P5,"MACAddress",3);
       DMPackCreateParamTS(P5,"FirmwareVersion","string(64)","string");
       DMPackCreateParam(P5,"MaxBitRate",2);
       DMPackCreateParam(P5,"MaxIngressBW",2);
       DMPackCreateParam(P5,"MaxEgressBW",2);
       DMPackCreateParamTS(P5,"HighestVersion","string(64)","string");
       DMPackCreateParamTS(P5,"CurrentVersion","string(64)","string");
       DMPackCreateParam(P5,"NetworkCoordinator",2);
       DMPackCreateParam(P5,"NodeID",2);
       DMPackCreateParam(P5,"MaxNodes",0);
       DMPackCreateW(P5,"PreferredNC",0,1);
       DMPackCreateParam(P5,"BackupNC",2);
       DMPackCreateW(P5,"PrivacyEnabledSetting",0,1);
       DMPackCreateParam(P5,"PrivacyEnabled",0);
       DMPackCreateParamTS(P5,"FreqCapabilityMask","hexBinary(8)","string");
       DMPackCreateParamTSW(P5,"FreqCurrentMaskSetting","string(256)","string",1);
       DMPackCreateParamTS(P5,"FreqCurrentMask","hexBinary(8)","string");
       DMPackCreateParam(P5,"CurrentOperFreq",2);
       DMPackCreateParam(P5,"LastOperFreq",2);
       DMPackCreateParamTSW(P5,"KeyPassphrase","string(17)","string",1);
       DMPackCreateW(P5,"TxPowerLimit",1,1);
       DMPackCreateW(P5,"PowerCntlPhyTarget",2,1);
       DMPackCreateW(P5,"BeaconPowerLimit",2,1);
       DMPackCreateParamTS(P5,"NetworkTabooMask","hexBinary(8)","string");
       DMPackCreateParamTSW(P5,"NodeTabooMask","hexBinary(8)","string",1);
       DMPackCreateParam(P5,"TxBcastRate",2);
       DMPackCreateParam(P5,"TxBcastPowerReduction",2);
       DMPackCreateParam(P5,"QAM256Capable",0);
       DMPackCreateParamTS(P5,"PacketAggregationCapability","unsignedInt[0:10]","uint32");
       DMPackCreateW(P5,"X_CISCO_COM_Reset",0,1);
       DMPackCreateW(P5,"X_CISCO_COM_MixedMode",0,1);
       DMPackCreateW(P5,"X_CISCO_COM_ChannelScanning",0,1);
       DMPackCreateW(P5,"X_CISCO_COM_AutoPowerControlEnable",0,1);
       DMPackCreateW(P5,"X_CISCO_COM_EnableTabooBit",0,1);
       DMPackCreateParam(P5,"X_CISCO_COM_CycleMaster",0);
       DMPackCreateW(P5,"AutoPowerControlPhyRate",2,1);
       DMPackCreateParam(P5,"X_CISCO_COM_BestNetworkCoordinatorID",2);
       DMPackCreateParamTS(P5,"X_CISCO_NetworkCoordinatorMACAddress","string(18)","string");
       DMPackCreateParamTSW(P5,"X_CISCO_COM_ChannelScanMask","string(256)","string",1);
       DMPackCreateParam(P5,"X_CISCO_COM_NumberOfConnectedClients",2);
       DMPackCreateParam(P5,"LinkUpTime",2);
       DMPackCreateParam(P5,"AssociatedDeviceNumberOfEntries",2);
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 0,"Stats",0);
        DMPackCreateFunctions(P6,"Stats2",11,10,11,12,13,15,16,17,18,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateN(P7,"BytesSent",2,0);
         DMPackCreateN(P7,"BytesReceived",2,0);
         DMPackCreateN(P7,"PacketsSent",2,0);
         DMPackCreateN(P7,"PacketsReceived",2,0);
         DMPackCreateN(P7,"ErrorsSent",2,0);
         DMPackCreateN(P7,"ErrorsReceived",2,0);
         DMPackCreateN(P7,"UnicastPacketsSent",2,0);
         DMPackCreateN(P7,"UnicastPacketsReceived",2,0);
         DMPackCreateN(P7,"DiscardPacketsSent",2,0);
         DMPackCreateN(P7,"DiscardPacketsReceived",2,0);
         DMPackCreateN(P7,"MulticastPacketsSent",2,0);
         DMPackCreateN(P7,"MulticastPacketsReceived",2,0);
         DMPackCreateN(P7,"BroadcastPacketsSent",2,0);
         DMPackCreateN(P7,"BroadcastPacketsReceived",2,0);
         DMPackCreateN(P7,"UnknownProtoPacketsReceived",2,0);
         DMPackCreateW(P7,"Reset",0,1);
         DMPackCreateParam(P7,"X_CISCO_COM_ExtAggrAverageTx",2);
         DMPackCreateParam(P7,"X_CISCO_COM_ExtAggrAverageRx",2);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 1,"X_CISCO_COM_ExtCounterTable","128");
          DMPackCreateFunctions(P8,"X_CISCO_COM_ExtCounterTable",6,0,2,10,11,12,13);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateParamTS(P9,"Type","string: rx(1),tx(2),rxErr(3),txErr(4),rxDrop(5)","string");
           DMPackCreateParam(P9,"Map",2);
           DMPackCreateParam(P9,"Rsrv",2);
           DMPackCreateParam(P9,"Lc",2);
           DMPackCreateParam(P9,"Adm",2);
           DMPackCreateParam(P9,"Probe",2);
           DMPackCreateParam(P9,"Async",2);
         P8=DMPackCreateObject(P7, 1,"X_CISCO_COM_ExtAggrCounterTable","128");
          DMPackCreateFunctions(P8,"X_CISCO_COM_ExtAggrCounterTable",6,0,2,10,11,12,13);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateParam(P9,"Tx",2);
           DMPackCreateParam(P9,"Rx",2);
       P6=DMPackCreateObject(P5, 0,"QoS",0);
        DMPackCreateFunctions(P6,"QoS",4,10,11,12,13);
        DMPackCreateFunctions(P6,"Qos",7,15,16,17,18,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"X_CISCO_COM_Enabled",0,1);
         DMPackCreateParam(P7,"EgressNumFlows",2);
         DMPackCreateParam(P7,"IngressNumFlows",2);
         DMPackCreateParam(P7,"FlowStatsNumberOfEntries",2);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 2,"FlowStats","128");
          DMPackCreateFunctions(P8,"FlowStats",8,0,2,5,6,10,11,12,13);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateParam(P9,"FlowID",2);
           DMPackCreateParamTS(P9,"PacketDA","string(32)","string");
           DMPackCreateParam(P9,"IngressNodeID",2);
           DMPackCreateParam(P9,"EgressNodeID",2);
           DMPackCreateParam(P9,"LeaseTimeLeft",2);
           DMPackCreateParam(P9,"FlowPackets",2);
           DMPackCreateParam(P9,"MaxRate",2);
           DMPackCreateParam(P9,"MaxBurstSize",2);
           DMPackCreateParam(P9,"FlowTag",2);
           DMPackCreateParam(P9,"LeaseTime",2);
       P6=DMPackCreateObject(P5, 2,"X_CISCO_COM_PeerTable","64");
        DMPackCreateFunctions(P6,"X_CISCO_COM_PeerTable",8,0,2,5,6,10,11,12,13);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateParam(P7,"PeerSpeed",2);
       P6=DMPackCreateObject(P5, 2,"X_RDKCENTRAL-COM_MeshTable","256");
        DMPackCreateFunctions(P6,"MeshTable",5,0,2,5,6,12);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateParam(P7,"MeshTxNodeId",2);
         DMPackCreateParam(P7,"MeshRxNodeId",2);
         DMPackCreateParam(P7,"MeshPHYTxRate",2);
       P6=DMPackCreateObject(P5, 2,"AssociatedDevice","128");
        DMPackCreateFunctions(P6,"AssociatedDevice",8,0,2,5,6,10,11,12,13);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateParam(P7,"MACAddress",3);
         DMPackCreateParam(P7,"NodeID",2);
         DMPackCreateParam(P7,"X_CISCO_COM_RxBcastRate",2);
         DMPackCreateParam(P7,"PreferredNC",0);
         DMPackCreateParamTS(P7,"HighestVersion","string(64)","string");
         DMPackCreateParam(P7,"PHYTxRate",2);
         DMPackCreateParam(P7,"PHYRxRate",2);
         DMPackCreateParam(P7,"TxPowerControlReduction",2);
         DMPackCreateN(P7,"RxPowerLevel",1,0);
         DMPackCreateParam(P7,"TxBcastRate",2);
         DMPackCreateN(P7,"RxBcastPowerLevel",1,0);
         DMPackCreateN(P7,"TxPackets",2,0);
         DMPackCreateN(P7,"RxPackets",2,0);
         DMPackCreateParam(P7,"RxErroredAndMissedPackets",2);
         DMPackCreateParam(P7,"QAM256Capable",0);
         DMPackCreateParamTS(P7,"PacketAggregationCapability","unsignedInt[0:10]","uint32");
         DMPackCreateParam(P7,"RxSNR",2);
         DMPackCreateParam(P7,"Active",0);
         DMPackCreateParam(P7,"X_CISCO_COM_NumberOfClients",2);
 return P0;
}
