/*
DM PACK
created with:
python /workspace/home/himal.d/MatterProtocol/build-raspberrypi4-64-rdk-broadband/tmp/work/cortexa72-rdk-linux/ccsp-lm-lite/rdkb-2024q3-kirkstone+git999-r0/recipe-sysroot-native/usr/bin/dm_pack_code_gen.py /workspace/home/himal.d/MatterProtocol/meta-cmf/../rdkb/components/opensource/ccsp/CcspLMLite/config/LMLite.XML /workspace/home/himal.d/MatterProtocol/meta-cmf/../rdkb/components/opensource/ccsp/CcspLMLite/source/Ssp/dm_pack_datamodel.c
*/

#include "ansc_platform.h"
#include "ansc_xml_dom_parser_interface.h"
#include "dm_pack_xml_helper.h"
PVOID DMPackCreateDataModelXML(){
 PANSC_XML_DOM_NODE_OBJECT P0,P1,P2,P3,P4,P5,P6,P7;
 P0=DMPackCreatePNode(0,"dataModelInfo");
  P1=DMPackCreateNode(P0,"version","1",1);
  P1=DMPackCreateNode(P0,"moduleName","COSA_TR181_USGv2",16);
  P1=DMPackCreatePNode(P0,"author");
  P1=DMPackCreatePNode(P0,"description");
  P1=DMPackCreatePNode(P0,"library");
  P1=DMPackCreatePNode(P0,"objects");
   P2=DMPackCreateObject(P1, 0,"Hosts",0);
    DMPackCreateFunctions(P2,"Hosts",6,10,15,12,17,13,18);
    P3=DMPackCreatePNode(P2,"parameters");
     DMPackCreateParam(P3,"X_CISCO_COM_ConnectedDeviceNumber",2);
     DMPackCreateParam(P3,"X_CISCO_COM_ConnectedWiFiNumber",2);
     DMPackCreateParam(P3,"X_RDKCENTRAL-COM_HostVersionId",2);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_HostCountPeriod",2,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_LMHost_Sync",2,1);
     DMPackCreateParamTSW(P3,"X_RDKCENTRAL-COM_LMHost_Sync_From_MoCA","string(2048)","string",1);
     DMPackCreateParamTSW(P3,"X_RDKCENTRAL-COM_LMHost_Sync_From_WiFi","string(2048)","string",1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_EthHost_Sync",3,1);
     DMPackCreateW(P3,"X_RDK_PresenceDetectEnable",0,1);
     DMPackCreateW(P3,"X_RDK_WebPA_PresenceNotificationEnable",0,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_AddPresenceNotificationMac",3,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_DeletePresenceNotificationMac",3,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_PresenceLeaveIPv4CheckInterval",2,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_PresenceLeaveIPv4Retries",2,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_PresenceLeaveIPv6CheckInterval",2,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_PresenceLeaveIPv6Retries",2,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_BackgroundPresenceJoinInterval",2,1);
    P3=DMPackCreatePNode(P2,"objects");
     P4=DMPackCreateObject(P3, 2,"Host","64");
      DMPackCreateFunctions(P4,"Host",15,0,2,5,6,10,11,12,13,15,16,17,18,20,21,22);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParamTSW(P5,"Alias","string(64)","string",1);
       DMPackCreateParam(P5,"PhysAddress",3);
       DMPackCreateParam(P5,"IPAddress",3);
       DMPackCreateParam(P5,"DHCPClient",3);
       DMPackCreateParam(P5,"AssociatedDevice",3);
       DMPackCreateParam(P5,"Layer1Interface",3);
       DMPackCreateParam(P5,"Layer3Interface",3);
       DMPackCreateParam(P5,"VendorClassID",3);
       DMPackCreateParam(P5,"HostName",3);
       DMPackCreateParam(P5,"Active",0);
       DMPackCreateParamTSN(P5,"LeaseTimeRemaining","int[-1:]","int",0);
       DMPackCreateParam(P5,"X_CISCO_COM_ActiveTime",1);
       DMPackCreateParam(P5,"X_CISCO_COM_InactiveTime",1);
       DMPackCreateParam(P5,"RDK_PresenceActiveLastChange",2);
       DMPackCreateParam(P5,"X_COMCAST-COM_LastChange",2);
       DMPackCreateParamTSW(P5,"AddressSource","string(8)","string",1);
       DMPackCreateParamTSW(P5,"Comments","string(1024)","string",1);
       DMPackCreateParam(P5,"X_CISCO_COM_RSSI",1);
       DMPackCreateParamTSW(P5,"X_RDKCENTRAL-COM_Parent","string(18)","string",0);
       DMPackCreateParamTSW(P5,"X_RDKCENTRAL-COM_DeviceType","string(64)","string",0);
       DMPackCreateParam(P5,"X_RDKCENTRAL-COM_Layer1Interface",3);
       DMPackCreateParam(P5,"X_RDKCENTRAL-COM_PresenceNotificationEnabled",0);
       DMPackCreateParam(P5,"RDK_PresenceActive",0);
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 1,"IPv4Address","16");
        DMPackCreateFunctions(P6,"Host_IPv4Address",6,0,2,10,11,12,13);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateParam(P7,"IPAddress",3);
       P6=DMPackCreateObject(P5, 1,"IPv6Address","16");
        DMPackCreateFunctions(P6,"Host_IPv6Address",6,0,2,10,11,12,13);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateParam(P7,"IPAddress",3);
   P2=DMPackCreateObject(P1, 0,"XHosts",0);
    DMPackCreateFunctions(P2,"XHosts",1,12);
    P3=DMPackCreatePNode(P2,"parameters");
     DMPackCreateParam(P3,"X_CISCO_COM_ConnectedDeviceNumber",2);
    P3=DMPackCreatePNode(P2,"objects");
     P4=DMPackCreateObject(P3, 2,"XHost","64");
      DMPackCreateFunctions(P4,"XHost",12,0,2,5,6,10,11,12,13,18,20,21,22);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParamTSW(P5,"Alias","string(64)","string",1);
       DMPackCreateParam(P5,"PhysAddress",3);
       DMPackCreateParam(P5,"IPAddress",3);
       DMPackCreateParam(P5,"DHCPClient",3);
       DMPackCreateParam(P5,"AssociatedDevice",3);
       DMPackCreateParam(P5,"Layer1Interface",3);
       DMPackCreateParam(P5,"Layer3Interface",3);
       DMPackCreateParam(P5,"HostName",3);
       DMPackCreateParam(P5,"Active",0);
       DMPackCreateParamTSN(P5,"LeaseTimeRemaining","int[-1:]","int",0);
       DMPackCreateParam(P5,"X_CISCO_COM_ActiveTime",1);
       DMPackCreateParam(P5,"X_CISCO_COM_InactiveTime",1);
       DMPackCreateParam(P5,"X_COMCAST-COM_LastChange",2);
       DMPackCreateParamTSW(P5,"AddressSource","string(8)","string",1);
       DMPackCreateParamTSW(P5,"Comments","string(1024)","string",1);
       DMPackCreateParam(P5,"X_CISCO_COM_RSSI",1);
       DMPackCreateParamTSW(P5,"X_RDKCENTRAL-COM_Parent","string(18)","string",0);
       DMPackCreateParamTSW(P5,"X_RDKCENTRAL-COM_DeviceType","string(64)","string",0);
       DMPackCreateParam(P5,"X_RDKCENTRAL-COM_Layer1Interface",3);
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 1,"XIPv4Address","16");
        DMPackCreateFunctions(P6,"XHost_IPv4Address",3,0,2,13);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateParam(P7,"IPAddress",3);
       P6=DMPackCreateObject(P5, 1,"XIPv6Address","16");
        DMPackCreateFunctions(P6,"XHost_IPv6Address",3,0,2,13);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateParam(P7,"IPAddress",3);
   P2=DMPackCreateObject(P1, 0,"X_RDKCENTRAL-COM_Report",0);
    P3=DMPackCreatePNode(P2,"objects");
     P4=DMPackCreateObject(P3, 0,"NetworkDevicesStatus",0);
      DMPackCreateFunctions(P4,"NetworkDevicesStatus",8,10,12,15,17,13,20,21,22);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"Enabled",0,1);
       DMPackCreateW(P5,"ReportingPeriod",2,1);
       DMPackCreateW(P5,"PollingPeriod",2,1);
       DMPackCreateW(P5,"Schema",3,0);
       DMPackCreateW(P5,"SchemaID",3,0);
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 0,"Default",0);
        DMPackCreateFunctions(P6,"NetworkDevicesStatus_Default",5,12,17,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"ReportingPeriod",2,1);
         DMPackCreateW(P7,"PollingPeriod",2,1);
         DMPackCreateW(P7,"OverrideTTL",2,0);
     P4=DMPackCreateObject(P3, 0,"NetworkDevicesTraffic",0);
      DMPackCreateFunctions(P4,"NetworkDevicesTraffic",8,10,12,15,17,13,20,21,22);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"Enabled",0,1);
       DMPackCreateW(P5,"ReportingPeriod",2,1);
       DMPackCreateW(P5,"PollingPeriod",2,1);
       DMPackCreateW(P5,"Schema",3,0);
       DMPackCreateW(P5,"SchemaID",3,0);
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 0,"Default",0);
        DMPackCreateFunctions(P6,"NetworkDevicesTraffic_Default",5,12,17,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"ReportingPeriod",2,1);
         DMPackCreateW(P7,"PollingPeriod",2,1);
         DMPackCreateW(P7,"OverrideTTL",2,0);
   P2=DMPackCreateObject(P1, 0,"ManagementServer",0);
    P3=DMPackCreatePNode(P2,"objects");
     P4=DMPackCreateObject(P3, 2,"ManageableDevice","255");
      DMPackCreateFunctions(P4,"ManageableDevice",5,0,5,6,13,2);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParamTS(P5,"ManufacturerOUI","string(6)","string");
       DMPackCreateParamTS(P5,"SerialNumber","string(64)","string");
       DMPackCreateParamTS(P5,"ProductClass","string(64)","string");
       DMPackCreateParamTS(P5,"Host","string(1024)","string");
 return P0;
}
