/*
DM PACK
created with:
python /workspace/home/himal.d/MatterProtocol/build-raspberrypi4-64-rdk-broadband/tmp/work/cortexa72-rdk-linux/ccsp-cm-agent/rdkb-2024q3-kirkstone+git999-r0/recipe-sysroot-native/usr/bin/dm_pack_code_gen.py /workspace/home/himal.d/MatterProtocol/meta-cmf/../rdkb/components/opensource/ccsp/CcspCMAgent/config-arm/TR181-CM.XML /workspace/home/himal.d/MatterProtocol/meta-cmf/../rdkb/components/opensource/ccsp/CcspCMAgent/source/CMAgentSsp/dm_pack_datamodel.c
*/

#include "ansc_platform.h"
#include "ansc_xml_dom_parser_interface.h"
#include "dm_pack_xml_helper.h"
PVOID DMPackCreateDataModelXML(){
 PANSC_XML_DOM_NODE_OBJECT P0,P1,P2,P3,P4,P5;
 P0=DMPackCreatePNode(0,"dataModelInfo");
  P1=DMPackCreateNode(P0,"version","1",1);
  P1=DMPackCreateNode(P0,"moduleName","COSA_TR181_USGv2",16);
  P1=DMPackCreatePNode(P0,"author");
  P1=DMPackCreateNode(P0,"description","COSA TR181 and extension for USGv2.",35);
  P1=DMPackCreatePNode(P0,"library");
   P2=DMPackCreateNode(P1,"path","libcm_tr181",11);
   P2=DMPackCreateNode(P1,"func_Init","COSA_Init",9);
   P2=DMPackCreateNode(P1,"func_Async_Init","COSA_Async_Init",15);
   P2=DMPackCreateNode(P1,"func_Unload","COSA_Unload",11);
   P2=DMPackCreateNode(P1,"func_MemoryCheck","COSA_MemoryCheck",16);
   P2=DMPackCreateNode(P1,"func_MemoryUsage","COSA_MemoryUsage",16);
   P2=DMPackCreateNode(P1,"func_MemoryTable","COSA_MemoryTable",16);
  P1=DMPackCreatePNode(P0,"objects");
   P2=DMPackCreateObject(P1, 0,"X_CISCO_COM_CableModem",0);
    DMPackCreateFunctions(P2,"X_CISCO_COM_CableModem",11,10,11,12,13,15,16,17,18,20,21,22);
    P3=DMPackCreatePNode(P2,"parameters");
     DMPackCreateParamTS(P3,"TelephonyDHCPStatus","string(32)","string");
     DMPackCreateParamTS(P3,"TelephonyTftpStatus","string(32)","string");
     DMPackCreateParamTS(P3,"TelephonyRegistrationStatus","string(32)","string");
     DMPackCreateParam(P3,"DOCSISDHCPAttempts",2);
     DMPackCreateParam(P3,"DOCSISTftpAttempts",2);
     DMPackCreateParam(P3,"MaxCpeAllowed",2);
     DMPackCreateParamTS(P3,"DOCSISConfigFileName","string(64)","string");
     DMPackCreateParamTS(P3,"ToDStatus","string(64)","string");
     DMPackCreateParamTS(P3,"UpstreamServiceFlowParams","string(64)","string");
     DMPackCreateParamTS(P3,"DownstreamServiceFlowParams","string(64)","string");
     DMPackCreateParamTS(P3,"DOCSISDownstreamDataRate","string(64)","string");
     DMPackCreateParamTS(P3,"DOCSISUpstreamDataRate","string(64)","string");
     DMPackCreateParamTS(P3,"MACAddress","string(64)","string");
     DMPackCreateParam(P3,"BPIState",0);
     DMPackCreateParam(P3,"NetworkAccess",0);
     DMPackCreateParamS(P3,"UpgradeServerIP",3,"uint32/ip4_addr");
     DMPackCreateParamTS(P3,"Market","string(64)","string");
     DMPackCreateParamTS(P3,"MDDIPOverride","string(64)","string");
     DMPackCreateParamS(P3,"IPAddress",3,"uint32/ip4_addr");
     DMPackCreateParamTS(P3,"BootFileName","string(64)","string");
     DMPackCreateParamS(P3,"SubnetMask",3,"uint32/ip4_addr");
     DMPackCreateParamS(P3,"Gateway",3,"uint32/ip4_addr");
     DMPackCreateParamS(P3,"TFTPServer",3,"uint32/ip4_addr");
     DMPackCreateParamTS(P3,"TimeServer","string(64)","string");
     DMPackCreateParam(P3,"TimeOffset",1);
     DMPackCreateParam(P3,"LeaseTimeRemaining",2);
     DMPackCreateParamTS(P3,"RebindTimeRemaining","string(64)","string");
     DMPackCreateParamTS(P3,"RenewTimeRemaining","string(64)","string");
     DMPackCreateParamTS(P3,"IPv6Address","string(40)","string");
     DMPackCreateParamTS(P3,"IPv6BootFileName","string(64)","string");
     DMPackCreateParamTS(P3,"IPv6Prefix","string(40)","string");
     DMPackCreateParamTS(P3,"IPv6Router","string(40)","string");
     DMPackCreateParamTS(P3,"IPv6TFTPServer","string(40)","string");
     DMPackCreateParamTS(P3,"IPv6TimeServer","string(40)","string");
     DMPackCreateParam(P3,"IPv6LeaseTimeRemaining",2);
     DMPackCreateParam(P3,"IPv6RebindTimeRemaining",2);
     DMPackCreateParam(P3,"IPv6RenewTimeRemaining",2);
     DMPackCreateParamTS(P3,"DOCSISVersion","string(64)","string");
     DMPackCreateParamTS(P3,"CMStatus","string(64)","string");
     DMPackCreateParamTS(P3,"DOCSISDownstreamScanning","string(64)","string");
     DMPackCreateParamTS(P3,"DOCSISDownstreamRanging","string(64)","string");
     DMPackCreateParamTS(P3,"DOCSISUpstreamScanning","string(64)","string");
     DMPackCreateParamTS(P3,"DOCSISUpstreamRanging","string(64)","string");
     DMPackCreateParamTS(P3,"DOCSISTftpStatus","string(64)","string");
     DMPackCreateParamTS(P3,"DOCSISDataRegComplete","string(64)","string");
     DMPackCreateParamTS(P3,"LoopDiagnosticsDetails","string(64)","string");
     DMPackCreateW(P3,"LoopDiagnosticsStart",0,1);
     DMPackCreateParamTS(P3,"CoreVersion","string(64)","string");
     DMPackCreateParamTS(P3,"DOCSISDHCPStatus","string(64)","string");
     DMPackCreateW(P3,"EnableLog",0,1);
     DMPackCreateW(P3,"LockedUpstreamChID",2,1);
     DMPackCreateW(P3,"StartDSFrequency",2,1);
     DMPackCreateParamTS(P3,"ProvIpType","string(64)","string");
     DMPackCreateParam(P3,"CMResetCount",2);
     DMPackCreateParam(P3,"LocalResetCount",2);
     DMPackCreateParam(P3,"DocsisResetCount",2);
     DMPackCreateParam(P3,"ErouterResetCount",2);
     DMPackCreateW(P3,"RequestPhyStatus",3,1);
     DMPackCreateW(P3,"RequestOperationalStatus",3,1);
     DMPackCreateW(P3,"ConfigureWan",0,1);
     DMPackCreateW(P3,"PostCfgWanFinalize",3,1);
     DMPackCreateW(P3,"CustomWanConfigUpdate",0,1);
    P3=DMPackCreatePNode(P2,"objects");
     P4=DMPackCreateObject(P3, 2,"CMErrorCodewords","128");
      DMPackCreateFunctions(P4,"CMErrorCodewords",6,0,2,5,6,12,13);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParam(P5,"UnerroredCodewords",2);
       DMPackCreateParam(P5,"CorrectableCodewords",2);
       DMPackCreateParam(P5,"UncorrectableCodewords",2);
     P4=DMPackCreateObject(P3, 2,"DocsisLog","128");
      DMPackCreateFunctions(P4,"DocsisLog",6,0,2,5,6,12,13);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParam(P5,"Time",3);
       DMPackCreateParam(P5,"EventID",2);
       DMPackCreateParam(P5,"EventLevel",2);
       DMPackCreateParam(P5,"Description",3);
     P4=DMPackCreateObject(P3, 2,"DownstreamChannel","128");
      DMPackCreateFunctions(P4,"DownstreamChannel",6,0,2,5,6,12,13);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParam(P5,"ChannelID",2);
       DMPackCreateParamTS(P5,"Frequency","string(64)","string");
       DMPackCreateParamTS(P5,"PowerLevel","string(64)","string");
       DMPackCreateParamTS(P5,"SNRLevel","string(64)","string");
       DMPackCreateParamTS(P5,"Modulation","string(64)","string");
       DMPackCreateParam(P5,"Octets",2);
       DMPackCreateParam(P5,"Correcteds",2);
       DMPackCreateParam(P5,"Uncorrectables",2);
       DMPackCreateParamTS(P5,"LockStatus","string(64)","string");
     P4=DMPackCreateObject(P3, 2,"UpstreamChannel","128");
      DMPackCreateFunctions(P4,"UpstreamChannel",6,0,2,5,6,12,13);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParam(P5,"ChannelID",2);
       DMPackCreateParamTS(P5,"Frequency","string(64)","string");
       DMPackCreateParamTS(P5,"PowerLevel","string(64)","string");
       DMPackCreateParamTS(P5,"ChannelType","string(64)","string");
       DMPackCreateParamTS(P5,"SymbolRate","string(64)","string");
       DMPackCreateParamTS(P5,"Modulation","string(64)","string");
       DMPackCreateParamTS(P5,"LockStatus","string(64)","string");
   P2=DMPackCreateObject(P1, 0,"DeviceInfo",0);
    DMPackCreateFunctions(P2,"DeviceInfo",4,10,13,15,18);
    P3=DMPackCreatePNode(P2,"parameters");
     DMPackCreateParam(P3,"X_RDKCENTRAL-COM_FirmwareDownloadStatus",3);
     DMPackCreateParam(P3,"X_RDKCENTRAL-COM_FirmwareDownloadProtocol",3);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_FirmwareDownloadURL",3,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_FirmwareToDownload",3,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_FirmwareDownloadNow",0,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_CableRfSignalStatus",0,0);
   P2=DMPackCreateObject(P1, 0,"QOS",0);
    DMPackCreateFunctions(P2,"",0);
    P3=DMPackCreatePNode(P2,"parameters");
    P3=DMPackCreatePNode(P2,"objects");
     P4=DMPackCreateObject(P3, 0,"X_RDK_LldMarkingRules",0);
      DMPackCreateFunctions(P4,"LldMarkingRules",2,13,18);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"Data",3,1);
   P2=DMPackCreateObject(P1, 0,"X_RDKCENTRAL-COM_CableModem",0);
    DMPackCreateFunctions(P2,"X_RDKCENTRAL_COM_CableModem",1,10);
    P3=DMPackCreatePNode(P2,"parameters");
     DMPackCreateW(P3,"LLD_Active",0,0);
    P3=DMPackCreatePNode(P2,"objects");
     P4=DMPackCreateObject(P3, 2,"DsOfdmChan","128");
      DMPackCreateFunctions(P4,"X_RDKCENTRAL_COM_CableModem_DsOfdmChan",6,5,6,0,2,12,13);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParam(P5,"ChannelID",2);
       DMPackCreateParamTS(P5,"ChanIndicator","string: other(1),primary(2),backupPrimary(3),nonPrimary(4)","uint32/mapped");
       DMPackCreateParam(P5,"SubcarrierZeroFreq",2);
       DMPackCreateParamTS(P5,"FirstActiveSubcarrierNum","unsignedInt[148:7895]","uint32");
       DMPackCreateParamTS(P5,"LastActiveSubcarrierNum","unsignedInt[148:7895]","uint32");
       DMPackCreateParam(P5,"NumActiveSubcarriers",2);
       DMPackCreateParam(P5,"SubcarrierSpacing",2);
       DMPackCreateParam(P5,"CyclicPrefix",2);
       DMPackCreateParam(P5,"RollOffPeriod",2);
       DMPackCreateParam(P5,"PlcFreq",2);
       DMPackCreateParam(P5,"NumPilots",2);
       DMPackCreateParam(P5,"TimeInterleaverDepth",2);
       DMPackCreateParamTS(P5,"SNRLevel","string(64)","string");
       DMPackCreateParamTS(P5,"PowerLevel","string(64)","string");
       DMPackCreateParam(P5,"PlcTotalCodewords",2);
       DMPackCreateParam(P5,"PlcUnreliableCodewords",2);
       DMPackCreateParam(P5,"NcpTotalFields",2);
       DMPackCreateParam(P5,"NcpFieldCrcFailures",2);
     P4=DMPackCreateObject(P3, 2,"UsOfdmaChan","128");
      DMPackCreateFunctions(P4,"X_RDKCENTRAL_COM_CableModem_UsOfdmaChan",6,5,0,2,6,10,12);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParam(P5,"ChannelId",2);
       DMPackCreateParam(P5,"ConfigChangeCt",2);
       DMPackCreateParam(P5,"SubcarrierZeroFreq",2);
       DMPackCreateParam(P5,"FirstActiveSubcarrierNum",2);
       DMPackCreateParam(P5,"LastActiveSubcarrierNum",2);
       DMPackCreateParamTS(P5,"NumActiveSubcarriers","unsignedInt[1:3800]","uint32");
       DMPackCreateParam(P5,"SubcarrierSpacing",2);
       DMPackCreateParam(P5,"CyclicPrefix",2);
       DMPackCreateParam(P5,"RollOffPeriod",2);
       DMPackCreateParam(P5,"NumSymbolsPerFrame",2);
       DMPackCreateParam(P5,"TxPower",2);
       DMPackCreateParam(P5,"PreEqEnabled",0);
     P4=DMPackCreateObject(P3, 2,"StatusOfdma","128");
      DMPackCreateFunctions(P4,"X_RDKCENTRAL_COM_CableModem_StatusOfdma",6,5,0,2,6,10,12);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParam(P5,"ChannelId",2);
       DMPackCreateParam(P5,"T3Timeouts",2);
       DMPackCreateParam(P5,"T4Timeouts",2);
       DMPackCreateParam(P5,"RangingAborteds",2);
       DMPackCreateParam(P5,"T3Exceededs",2);
       DMPackCreateParam(P5,"IsMuted",0);
       DMPackCreateParamTS(P5,"RangingStatus","string: other(1),aborted(2),retriesExceeded(3),success(4),continue(5),timeoutT4(6)","uint32/mapped");
 return P0;
}
