/*
DM PACK
created with:
python /workspace/home/himal.d/MatterProtocol/build-raspberrypi4-64-rdk-broadband/tmp/work/cortexa72-rdk-linux/rdktelcovoicemanager/rdkb-2024q3-kirkstone+git999-r0/recipe-sysroot-native/usr/bin/dm_pack_code_gen.py /workspace/home/himal.d/MatterProtocol/meta-cmf/../rdkb/components/opensource/ccsp/RdkTelcoVoiceManager/config/RdkTelcoVoiceManager_v2.xml /workspace/home/himal.d/MatterProtocol/meta-cmf/../rdkb/components/opensource/ccsp/RdkTelcoVoiceManager/source/TelcoVoiceManager/dm_pack_datamodel.c
*/

#include "ansc_platform.h"
#include "ansc_xml_dom_parser_interface.h"
#include "dm_pack_xml_helper.h"
PVOID DMPackCreateDataModelXML(){
 PANSC_XML_DOM_NODE_OBJECT P0,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15;
 P0=DMPackCreatePNode(0,"dataModelInfo");
  P1=DMPackCreateNode(P0,"version","1",1);
  P1=DMPackCreateNode(P0,"moduleName","TR104_RdkTelcoVoiceManager",26);
  P1=DMPackCreatePNode(P0,"author");
  P1=DMPackCreatePNode(P0,"description");
  P1=DMPackCreatePNode(P0,"library");
  P1=DMPackCreatePNode(P0,"objects");
   P2=DMPackCreateObject(P1, 0,"X_RDK_TelcoVoice",0);
    DMPackCreateFunctions(P2,"X_RDK_TelcoVoice",5,13,18,20,21,22);
    P3=DMPackCreatePNode(P2,"parameters");
     DMPackCreateW(P3,"Data",3,1);
     DMPackCreateParam(P3,"DatamodelVersion",3);
   P2=DMPackCreateObject(P1, 0,"Services",0);
    P3=DMPackCreatePNode(P2,"objects");
     P4=DMPackCreateObject(P3, 0,"X_RDK_Report",0);
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 0,"Voice",0);
        DMPackCreateFunctions(P6,"X_RDK_Report_VoiceService",8,12,17,13,10,15,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"Enabled",0,1);
         DMPackCreateW(P7,"ReportingPeriod",2,1);
         DMPackCreateParam(P7,"Schema",3);
         DMPackCreateParam(P7,"SchemaID",3);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 0,"Default",0);
          DMPackCreateFunctions(P8,"X_RDK_Report_VoiceService_Default",2,12,17);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"ReportingPeriod",2,1);
           DMPackCreateParamTSW(P9,"OverrideTTL","unsignedInt[1:900]","uint32",1);
     P4=DMPackCreateObject(P3, 2,"VoiceService","128");
      DMPackCreateFunctions(P4,"VoiceService",13,5,6,0,2,12,17,10,15,13,18,20,21,22);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParamTSW(P5,"Alias","string(64)","string",1);
       DMPackCreateW(P5,"X_RDK_DisableLoopCurrentUntilRegistered",0,1);
       DMPackCreateParamTSW(P5,"X_RDK_BoundIfName","string(256)","string",1);
       DMPackCreateParamTSW(P5,"X_RDK_IpAddressFamily","string(256)","string",1);
       DMPackCreateParamTSW(P5,"X_RDK_BoundIpAddr","string(256)","string",0);
       DMPackCreateW(P5,"X_RDK_Firewall_Rule_Data",3,0);
       DMPackCreateParamTSW(P5,"X_RDK_Enable","string: Disable(0),Enable(1)","uint32/mapped",1);
       DMPackCreateParamTS(P5,"X_RDK_Status","string: Stopped(0),Starting(1),Started(2),Stopping(3),Error(4)","uint32/mapped");
       DMPackCreateW(P5,"X_RDK_FactoryReset",0,1);
       DMPackCreateParam(P5,"X_RDK_OngoingEmergencyCall",0);
       DMPackCreateParamTS(P5,"X_RDK_LocalTimeZone","string(256)","string");
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 0,"X_RDK_Debug",0);
        DMPackCreateFunctions(P6,"X_RDK_Debug",7,13,12,18,17,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateParamTSW(P7,"CCTKTraceGroup","string(256)","string",1);
         DMPackCreateParamTSW(P7,"CCTKTraceLevel","string(256)","string",1);
         DMPackCreateW(P7,"ModuleLogLevels",3,1);
         DMPackCreateW(P7,"LogServer",3,1);
         DMPackCreateW(P7,"LogServerPort",2,1);
       P6=DMPackCreateObject(P5, 0,"Capabilities",0);
        DMPackCreateFunctions(P6,"TelcoVoiceMgrDml_capabilities",3,12,13,11);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateParam(P7,"MaxLineCount",1);
         DMPackCreateParam(P7,"MaxExtensionCount",1);
         DMPackCreateParam(P7,"MaxCallLogCount",1);
         DMPackCreateParam(P7,"MaxSessionsPerLine",1);
         DMPackCreateParam(P7,"MaxSessionsPerExtension",1);
         DMPackCreateParam(P7,"MaxSessionCount",1);
         DMPackCreateParamTS(P7,"NetworkConnectionModes","String(255)","string");
         DMPackCreateParamTS(P7,"UserConnectionModes","String(255)","string");
         DMPackCreateParamTS(P7,"ToneFileFormats","string: G.711MuLaw(0),G.711ALaw(1),G.729(2),MP3(3),WAV(4),AMR(5)","uint32/mapped");
         DMPackCreateParamTS(P7,"RingFileFormats","string: MIDI(0),SMAF_MMF(1),RTTTL(2),MP3(3),WAV(4),AMR(5)","uint32/mapped");
         DMPackCreateParamTS(P7,"FacilityActions","string: AA_REGISTER(0),AA_ERASE(1),AA_INTERROGATE(2),CA_ACTIVATE(3),CCBS_ACTIVATE(4),CCBS_DEACTIVATE(5),CCBS_INTERROGATE(6),CCNR_ACTIVATE(7),CCNR_DEACTIVATE(8),CCNR_INTERROGATE(9),CFB_REGISTER(10),CFB_ACTIVATE(11),CFB_DEACTIVATE(12),CFB_ERASE(13),CFB_INTERROGATE(14),CFNR_REGISTER(15),CFNR_ACTIVATE(16),CFNR_DEACTIVATE(17),CFNR_ERASE(18),CFNR_INTERROGATE(19),CFNR_TIMER(20),CFT_ACTIVATE(21),CFT_DEACTIVATE(22),CFT_INTERROGATE(23),CFU_REGISTER(24),CFU_ACTIVATE(25),CFU_DEACTIVATE(26),CFU_ERASE(27),CFU_INTERROGATE(28),CLIR_ACTIVATE(29),CLIR_DEACTIVATE(30),CLIR_INTERROGATE(31),CP_INVOKE(32),CW_ACTIVATE(33),CW_DEACTIVATE(34),CW_INVOKE(35),DND_ACTIVATE(36),DND_DEACTIVATE(37),DND_INTERROGATE(38),EXT_INVOKE(39),LINE_INVOKE(40),MAILBOX_INVOKE(41),OCB_ACTIVATE(42),OCB_DEACTIVATE(43),OCB_INTERROGATE(44),PSO_ACTIVATE(45),PW_SET(46),SCF_ACTIVATE(47),SCF_DEACTIVATE(48),SCF_INTERROGATE(49),SCREJ_ACTIVATE(50),SCREJ_DEACTIVATE(51),SCREJ_INTERROGATE(52),SR_ACTIVATE(53),SR_DEACTIVATE(54),SR_INTERROGATE(55)","uint32/mapped");
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 0,"SIP",0);
          P9=DMPackCreatePNode(P8,"objects");
           P10=DMPackCreateObject(P9, 0,"Client",0);
            DMPackCreateFunctions(P10,"TelcoVoiceMgrDml_capabilities_SIP_Client",2,12,13);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateParamTS(P11,"Extensions","String(255)","string");
             DMPackCreateParamTS(P11,"URISchemes","String(255)","string");
             DMPackCreateParamTS(P11,"EventTypes","String(255)","string");
             DMPackCreateParamTS(P11,"TLSAuthenticationProtocols","string: Null(0),MD5(1),SHA-1(2),SHA-2(3),AEAD(4)","uint32/mapped");
             DMPackCreateParamTS(P11,"TLSAuthenticationKeySizes","String(255)","string");
             DMPackCreateParamTS(P11,"TLSEncryptionProtocols","string: Null(0),RC4(1),RC2(2),DES(3),3DES(4),AES(5),Camellia(6)","uint32/mapped");
             DMPackCreateParamTS(P11,"TLSEncryptionKeySizes","String(255)","string");
             DMPackCreateParamTS(P11,"TLSKeyExchangeProtocols","string: RSA(0),DSS(1),DHE-RSA(2),DHE-DSS(3),ECDHE-RSA(4),ECDHE-ECDSA(5)","uint32/mapped");
           P10=DMPackCreateObject(P9, 0,"Registrar",0);
            DMPackCreateFunctions(P10,"TelcoVoiceMgrDml_capabilities_SIP_Registrar",2,12,13);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateParamTS(P11,"Extensions","String(255)","string");
             DMPackCreateParamTS(P11,"URISchemes","String(255)","string");
             DMPackCreateParamTS(P11,"EventTypes","String(255)","string");
             DMPackCreateParamTS(P11,"TLSAuthenticationProtocols","string: Null(0),MD5(1),SHA-1(2),SHA-2(3),AEAD(4)","uint32/mapped");
             DMPackCreateParamTS(P11,"TLSAuthenticationKeySizes","String(255)","string");
             DMPackCreateParamTS(P11,"TLSEncryptionProtocols","string: Null(0),RC4(1),RC2(2),DES(3),3DES(4),AES(5),Camellia(6)","uint32/mapped");
             DMPackCreateParamTS(P11,"TLSEncryptionKeySizes","String(255)","string");
             DMPackCreateParamTS(P11,"TLSKeyExchangeProtocols","string: RSA(0),DSS(1),DHE-RSA(2),DHE-DSS(3),ECDHE-RSA(4),ECDHE-ECDSA(5)","uint32/mapped");
         P8=DMPackCreateObject(P7, 0,"MGCP",0);
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_capabilities_MGCP",1,13);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateParamTS(P9,"Extensions","String(255)","string");
         P8=DMPackCreateObject(P7, 0,"H323",0);
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_capabilities_H323",2,12,10);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateParam(P9,"FastStart",0);
           DMPackCreateParamTS(P9,"H235AuthenticationMethods","string: dhExch(0),pwdSymEnc(1),pwdHash(2),certSign(3),ipsec(4),tls(5)","uint32/mapped");
         P8=DMPackCreateObject(P7, 0,"ISDN",0);
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_capabilities_ISDN",1,10);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateParam(P9,"MSN",0);
           DMPackCreateParam(P9,"DDI",0);
           DMPackCreateParam(P9,"MCID",0);
           DMPackCreateParam(P9,"MWI",0);
           DMPackCreateParam(P9,"AoC",0);
           DMPackCreateParam(P9,"ECT",0);
         P8=DMPackCreateObject(P7, 0,"POTS",0);
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_capabilities_POTS",3,12,13,10);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateParamTS(P9,"DialType","string: Tone(0),Pulse(1),Tone_And_Pulse(2)","uint32/mapped");
           DMPackCreateParam(P9,"ClipGeneration",0);
           DMPackCreateParam(P9,"ChargingPulse",0);
         P8=DMPackCreateObject(P7, 2,"Codec","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_capabilities_CodecList",11,5,6,0,2,12,13,18,10,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateParamTS(P9,"Codec","string: AMR(0),Clearmod_RFC4040(1),EVRC1(2),EVRCB1(3),G.711MuLaw(4),G.711ALaw(5),G.726(6),G.729(7),G.729.1(8),G.729a(9),G.729e(10),G.728(11),G.723.1(12),G.722(13),G.722.1(14),G.722.2(15),Generic_Comfort_Noise_RFC3389(16),GSM-FR(17),GSM-HR(18),GSM-EFR(19),iLBC(20),Speex(21)","uint32/mapped");
           DMPackCreateParam(P9,"BitRate",2);
           DMPackCreateParamTS(P9,"PacketizationPeriod","String(255)","string");
           DMPackCreateParam(P9,"SilenceSuppression",0);
         P8=DMPackCreateObject(P7, 0,"QualityIndicator",0);
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_capabilities_QualityIndicator",2,12,13);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateParamTS(P9,"QIModelsSupported","String(255)","string");
           DMPackCreateParam(P9,"MaxQIValues",2);
           DMPackCreateParam(P9,"MaxWorstQIValues",2);
       P6=DMPackCreateObject(P5, 0,"ReservedPorts",0);
        DMPackCreateFunctions(P6,"TelcoVoiceMgrDml_ReservedPorts",2,13,18);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateParamTSW(P7,"WANPortRange","String(255)","string",1);
         DMPackCreateParamTSW(P7,"LANPortRange","String(255)","string",1);
       P6=DMPackCreateObject(P5, 0,"ISDN",0);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 2,"BRI","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_ISDN_BRIList",13,5,6,0,2,12,17,13,18,10,15,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
           DMPackCreateParamTS(P9,"Status","string: Up(0),Error(1),Testing(2),Disabled(3)","uint32/mapped");
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateParamTS(P9,"Name","String(64)","string");
           DMPackCreateParamTSW(P9,"ToneEventProfile","String(256)","string",1);
           DMPackCreateParamTSW(P9,"ApplicationInterface","string: VoIP(0),VoATM(1),Data(2)","uint32/mapped",1);
           DMPackCreateParamTSW(P9,"Protocol","string: EuroISDN(0),NI-1(1),NI-2(2),5ESS(3),NTT(4),VN3(5),VN4(6),QSIG(7)","uint32/mapped",1);
           DMPackCreateParamTSW(P9,"ProtocolEmulation","string: TE(0),NT(1)","uint32/mapped",1);
           DMPackCreateW(P9,"PermanentLayer2",0,1);
           DMPackCreateW(P9,"PermanentLayer1",0,1);
           DMPackCreateW(P9,"LapdDisconnectionTimeout",0,1);
           DMPackCreateParamTSW(P9,"TEINegotiation","string: Static(0),Dynamic(1)","uint32/mapped",1);
           DMPackCreateW(P9,"StaticTEI",2,1);
           DMPackCreateW(P9,"LifeLineHold",0,1);
           DMPackCreateW(P9,"PowerSourceOne",0,1);
           DMPackCreateW(P9,"MaxNumBChannels",2,1);
           DMPackCreateParamTSW(P9,"OutboundOnlyBChannels","String(255)","string",1);
           DMPackCreateParamTSW(P9,"InboundOnlyBChannels","String(255)","string",1);
           DMPackCreateParamTSW(P9,"BidirectionalBChannels","String(255)","string",1);
         P8=DMPackCreateObject(P7, 2,"PRI","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_ISDN_PRIList",13,5,6,0,2,12,17,13,18,10,15,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
           DMPackCreateParamTS(P9,"Status","string: Up(0),Error(1),Testing(2),Disabled(3)","uint32/mapped");
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateParamTS(P9,"Name","String(64)","string");
           DMPackCreateParamTSW(P9,"ToneEventProfile","String(256)","string",1);
           DMPackCreateParamTSW(P9,"ApplicationInterface","string: VoIP(0),VoATM(1),Data(2)","uint32/mapped",1);
           DMPackCreateParamTSW(P9,"Protocol","string: EuroISDN(0),NI-1(1),NI-2(2),4ESS(3),5ESS(4),NTT(5),QSIG(6)","uint32/mapped",1);
           DMPackCreateParamTSW(P9,"ProtocolEmulation","string: TE(0),NT(1)","uint32/mapped",1);
           DMPackCreateW(P9,"PermanentLayer2",0,1);
           DMPackCreateParamTSW(P9,"Linecode","string: ami(0),hdb3(1),b8zs(2)","uint32/mapped",1);
           DMPackCreateParamTSW(P9,"ESF","string: None(0),DF(1),MF(1),EMF(2),SF(3),ESF(4),AutoDetect(5)","uint32/mapped",1);
           DMPackCreateParamTSW(P9,"PhysicalInterfaceType","string: T1(0),E1(1)","uint32/mapped",1);
           DMPackCreateW(P9,"MaxNumBChannels",2,1);
           DMPackCreateParamTSW(P9,"OutboundOnlyBChannels","String(255)","string",1);
           DMPackCreateParamTSW(P9,"InboundOnlyBChannels","String(255)","string",1);
           DMPackCreateParamTSW(P9,"BidirectionalBChannels","String(255)","string",1);
           DMPackCreateParamTSW(P9,"ClockMode","string: Master(0),Slave(1)","uint32/mapped",1);
       P6=DMPackCreateObject(P5, 0,"POTS",0);
        DMPackCreateFunctions(P6,"TelcoVoiceMgrDml_POTS",2,13,18);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateParamTSW(P7,"Region","String(2)","string",1);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 2,"FXO","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_POTS_FXOList",13,5,6,0,2,12,17,13,18,10,15,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
           DMPackCreateParamTS(P9,"Status","string: Up(0),Error(1),Testing(2),Disabled(3)","uint32/mapped");
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateParamTS(P9,"Name","String(64)","string");
           DMPackCreateParamTSW(P9,"ToneEventProfile","String(256)","string",1);
           DMPackCreateW(P9,"SecondStepDialing",0,1);
           DMPackCreateW(P9,"TimeoutBeforeDialing",2,1);
           DMPackCreateW(P9,"RingingTimeout",2,1);
           DMPackCreateW(P9,"RingNumber",2,1);
           DMPackCreateW(P9,"OnHookMinDuration",2,1);
           DMPackCreateParamTSW(P9,"SignalingMode","string: LoopStart(0),GroundStart(1)","uint32/mapped",1);
           DMPackCreateW(P9,"DTMFDialoutInterval",2,1);
           DMPackCreateW(P9,"CallerIdDetectionEnable",0,1);
           DMPackCreateParam(P9,"Active",0);
          P9=DMPackCreatePNode(P8,"objects");
           P10=DMPackCreateObject(P9, 0,"DiagTests",0);
            DMPackCreateFunctions(P10,"TelcoVoiceMgrDml_POTS_FXOList_DiagTests",2,12,17);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateParamTSW(P11,"DiagnosticsState","string: None(0),Requested(1),Complete(2),Error_Internal(3),Error_Other(4)","uint32/mapped",1);
             DMPackCreateParamTSW(P11,"TestSelector","string: Battery(0),DialTone(1)","uint32/mapped",1);
             DMPackCreateParamTS(P11,"TestResult","string: Success(0),Failure(1)","uint32/mapped");
         P8=DMPackCreateObject(P7, 2,"FXS","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_POTS_FXSList",13,5,6,0,2,12,17,13,18,10,15,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
           DMPackCreateParamTS(P9,"Status","string: Up(0),Error(1),Testing(2),Disabled(3)","uint32/mapped");
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateParamTS(P9,"Name","String(64)","string");
           DMPackCreateParamTSW(P9,"ToneEventProfile","String(256)","string",1);
           DMPackCreateParamTSW(P9,"FaxPassThrough","string: Disable(0),Auto(1),Force(2)","uint32/mapped",1);
           DMPackCreateParamTSW(P9,"ModemPassThrough","string: Disable(0),Auto(1),Force(2)","uint32/mapped",1);
           DMPackCreateParamTSW(P9,"DialType","string: Tone(0),Pulse(1)","uint32/mapped",1);
           DMPackCreateW(P9,"ClipGeneration",0,1);
           DMPackCreateW(P9,"ChargingPulse",0,1);
           DMPackCreateParam(P9,"Active",0);
           DMPackCreateParamTSW(P9,"TerminalType","string: Audio(0),Fax(1),Modem(2),Any(4)","uint32/mapped",1);
          P9=DMPackCreatePNode(P8,"objects");
           P10=DMPackCreateObject(P9, 0,"VoiceProcessing",0);
            DMPackCreateFunctions(P10,"TelcoVoiceMgrDml_POTS_FXSList_VoiceProcessing",5,12,11,16,10,15);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateW(P11,"TransmitGain",1,1);
             DMPackCreateW(P11,"ReceiveGain",1,1);
             DMPackCreateW(P11,"EchoCancellationEnable",0,1);
             DMPackCreateParam(P11,"EchoCancellationInUse",0);
             DMPackCreateParam(P11,"EchoCancellationTail",2);
           P10=DMPackCreateObject(P9, 0,"DiagTests",0);
            DMPackCreateFunctions(P10,"TelcoVoiceMgrDml_POTS_FXSList_DiagTests",2,12,17);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateParamTSW(P11,"DiagnosticsState","string: None(0),Requested(1),Complete(2),Error_Internal(3),Error_Other(4)","uint32/mapped",1);
             DMPackCreateParamTSW(P11,"TestSelector","string: Hazard Potential(0),Foreign Voltage(1),Resistive Faults(2),Off-hook(3), REN(4)","uint32/mapped",1);
             DMPackCreateParamTS(P11,"TestResult","string: Success(0),Failure(1)","uint32/mapped");
         P8=DMPackCreateObject(P7, 0,"Ringer",0);
          P9=DMPackCreatePNode(P8,"objects");
           P10=DMPackCreateObject(P9, 2,"Event","128");
            DMPackCreateFunctions(P10,"TelcoVoiceMgrDml_POTS_Ringer_EventList",10,5,6,0,2,12,13,18,20,21,22);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateParamTSW(P11,"Alias","string(64)","string",1);
             DMPackCreateParamTS(P11,"Function","string: Default(0),CCBSCallBack(1),CCNRCallBack(2),InternalCall(3),RingSplash(4),Group(5)","uint32/mapped");
             DMPackCreateParamTSW(P11,"Cadence","String(255)","string",1);
       P6=DMPackCreateObject(P5, 0,"DECT",0);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 2,"Base","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_DECT_BaseList",13,5,6,0,2,12,17,13,18,10,15,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
           DMPackCreateParamTS(P9,"Status","string: Up(0),Error(1),Testing(2),Disabled(3)","uint32/mapped");
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateParamTS(P9,"Name","String(64)","string");
           DMPackCreateParamTSW(P9,"ToneEventProfile","String(256)","string",1);
           DMPackCreateParamTS(P9,"Standard","string: GAP(0),CAT-iq_1.0(1),CAT-iq_2.0(2),CAT-iq_2.1(3),CAT-iq_3.0(4),CAT-iq_4.0(5)","uint32/mapped");
           DMPackCreateParamTS(P9,"RFPI","String(255)","string");
           DMPackCreateW(P9,"MaxSupportedPP",2,1);
           DMPackCreateParamTSW(P9,"PIN","String(255)","string",1);
           DMPackCreateParam(P9,"RepeaterSupportEnabled",0);
           DMPackCreateW(P9,"NEMOEnable",0,1);
           DMPackCreateW(P9,"SubscriptionEnable",0,1);
           DMPackCreateW(P9,"CipheringEnable",0,1);
           DMPackCreateParamTS(P9,"EncryptionType","string: DSC(0),DSC2(1),CCM(2) ","uint32/mapped");
           DMPackCreateParamTSW(P9,"RFPowerControl","string: Normal(0),Reduced(1)","uint32/mapped",1);
           DMPackCreateParamTS(P9,"FirmwareVersion","String(20)","string");
           DMPackCreateParamTS(P9,"EepromVersion","String(20)","string");
           DMPackCreateParamTS(P9,"HardwareVersion","String(20)","string");
          P9=DMPackCreatePNode(P8,"objects");
           P10=DMPackCreateObject(P9, 0,"Stats",0);
            DMPackCreateFunctions(P10,"TelcoVoiceMgrDml_DECT_BaseList_Stats",1,12);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateParam(P11,"Handovers",2);
             DMPackCreateParam(P11,"HandoverFailures",2);
             DMPackCreateParam(P11,"ControlFieldErrors",2);
             DMPackCreateParam(P11,"PayloadFieldErrors",2);
             DMPackCreateParam(P11,"SyncFailures",2);
         P8=DMPackCreateObject(P7, 2,"Portable","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_DECT_PortableList",13,5,6,0,2,12,17,13,18,10,15,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
           DMPackCreateParamTS(P9,"Status","string: Up(0),Error(1),Testing(2),Disabled(3)","uint32/mapped");
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateParamTSW(P9,"CodecList","String(255)","string",1);
           DMPackCreateParamTS(P9,"RegistrationStatus","string: In_reach(0),Not_in_reach(1)","uint32/mapped");
           DMPackCreateParamTS(P9,"IPUI","String(255)","string");
           DMPackCreateParam(P9,"IPUILength",2);
           DMPackCreateParamTS(P9,"IPEI","String(255)","string");
           DMPackCreateParamTS(P9,"PARK","String(255)","string");
           DMPackCreateParamTS(P9,"BaseAttachedTo","String(256)","string");
           DMPackCreateParamTS(P9,"PortableType","string: GAP(0),CAT-iq_1.0(1),CAT-iq_2.0(2),CAT-iq_2.1(3),CAT-iq_3.0(4),CAT-iq_4.0(5)","uint32/mapped");
           DMPackCreateParamTS(P9,"SubscriptionTime","String(255)","string");
           DMPackCreateParamTSW(P9,"Control","string: Unregister(0),Disable(1)","uint32/mapped",1);
           DMPackCreateParamTS(P9,"HardwareVersion","String(20)","string");
           DMPackCreateParamTS(P9,"SoftwareVersion","String(20)","string");
           DMPackCreateParam(P9,"SoftwareUpgrade",0);
           DMPackCreateParamTS(P9,"LastUpdateDateTime","String(255)","string");
           DMPackCreateParamTSW(P9,"OperatorName","String(32)","string",1);
       P6=DMPackCreateObject(P5, 0,"SIP",0);
        DMPackCreateFunctions(P6,"TelcoVoiceMgrDml_SIP",1,13);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 2,"Client","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_SIP_ClientList",13,5,6,0,2,12,17,13,18,10,15,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
           DMPackCreateW(P9,"QuiescentMode",0,1);
           DMPackCreateParamTS(P9,"Status","string: Up(0),Initializing(1),Registering(2),Deregistering(3),Error_Misconfigured(4),Error_Network(5),Error_Registration(6),Quiescent(7),Disabled(8)","uint32/mapped");
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateParamTS(P9,"Origin","string: AutoConfigured(0),Static(1)","uint32/mapped");
           DMPackCreateParamTSW(P9,"RegisterMode","string: RFC3261(0),STATIC(1),RFC6140(2),TISPAN(3)","uint32/mapped",1);
           DMPackCreateParamTSW(P9,"AuthUserName","String(128)","string",1);
           DMPackCreateParamTSW(P9,"AuthPassword","String(128)","string",1);
           DMPackCreateParamTSW(P9,"Network","String(256)","string",1);
           DMPackCreateW(P9,"MaxSessions",2,1);
           DMPackCreateParamTSW(P9,"RegisterURI","String(389)","string",1);
           DMPackCreateW(P9,"E164Format",0,1);
           DMPackCreateW(P9,"T38Enable",0,1);
          P9=DMPackCreatePNode(P8,"objects");
           P10=DMPackCreateObject(P9, 2,"Contact","128");
            DMPackCreateFunctions(P10,"TelcoVoiceMgrDml_SIP_ClientList_ContactList",13,5,6,0,2,12,17,13,18,10,15,20,21,22);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateW(P11,"Enable",0,1);
             DMPackCreateParamTS(P11,"Status","string: Up(0),Error(1),Disabled(2)","uint32/mapped");
             DMPackCreateParamTSW(P11,"Alias","string(64)","string",1);
             DMPackCreateParamTS(P11,"Origin","string: AutoConfigured(0),Static(1)","uint32/mapped");
             DMPackCreateParamTSW(P11,"IPAddress","String(45)","string",1);
             DMPackCreateW(P11,"Port",2,1);
             DMPackCreateParamTSW(P11,"ContactURI","String(256)","string",1);
             DMPackCreateParamTS(P11,"ExpireTime","String(255)","string");
             DMPackCreateW(P11,"PingInterval",2,1);
             DMPackCreateParamTS(P11,"UserAgent","String(256)","string");
           P10=DMPackCreateObject(P9, 2,"EventSubscribe","128");
            DMPackCreateFunctions(P10,"TelcoVoiceMgrDml_SIP_ClientList_EvtSubList",11,5,6,0,2,13,18,10,15,20,21,22);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateW(P11,"Enable",0,1);
             DMPackCreateParamTSW(P11,"Alias","string(64)","string",1);
             DMPackCreateParamTS(P11,"Event","String(32)","string");
             DMPackCreateParamTSW(P11,"AuthUserName","String(128)","string",1);
             DMPackCreateParamTSW(P11,"AuthPassword","String(128)","string",1);
         P8=DMPackCreateObject(P7, 2,"Network","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_SIP_NetworkList",15,5,6,0,2,12,17,13,18,11,16,10,15,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
           DMPackCreateW(P9,"QuiescentMode",0,1);
           DMPackCreateParamTS(P9,"Status","string: Up(0),Resolving(1),Error_DNS(2),Error_Other(3),Disabled(4)","uint32/mapped");
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateParamTSW(P9,"ProxyServer","String(256)","string",1);
           DMPackCreateW(P9,"ProxyServerPort",2,1);
           DMPackCreateParamTSW(P9,"ProxyServerTransport","string: UDP(0),TCP(1),TLS(2),SCTP(3)","uint32/mapped",1);
           DMPackCreateParamTSW(P9,"RegistrarServer","String(256)","string",1);
           DMPackCreateW(P9,"RegistrarServerPort",2,1);
           DMPackCreateParamTSW(P9,"RegistrarServerTransport","string: UDP(0),TCP(1),TLS(2),SCTP(3)","uint32/mapped",1);
           DMPackCreateParamTSW(P9,"ServerDomain","String(256)","string",1);
           DMPackCreateParamTS(P9,"ChosenDomain","String(256)","string");
           DMPackCreateParamTS(P9,"ChosenIPAddress","String(45)","string");
           DMPackCreateParam(P9,"ChosenPort",2);
           DMPackCreateParamTSW(P9,"UserAgentDomain","String(256)","string",1);
           DMPackCreateW(P9,"UserAgentPort",2,1);
           DMPackCreateParamTSW(P9,"UserAgentTransport","string: UDP(0),TCP(1),TLS(2),SCTP(3)","uint32/mapped",1);
           DMPackCreateParamTSW(P9,"OutboundProxy","String(256)","string",1);
           DMPackCreateParamTS(P9,"OutboundProxyResolvedAddress","String(45)","string");
           DMPackCreateParamTS(P9,"OutboundProxyPrecedence","string: Static(0),DHCP(1)","uint32/mapped");
           DMPackCreateW(P9,"OutboundProxyPort",2,1);
           DMPackCreateW(P9,"STUNEnable",0,1);
           DMPackCreateParamTSW(P9,"STUNServer","String(256)","string",1);
           DMPackCreateW(P9,"NonVoiceBandwidthReservedUpstream",2,1);
           DMPackCreateW(P9,"NonVoiceBandwidthReservedDownstream",2,1);
           DMPackCreateParamTSW(P9,"Organization","String(256)","string",1);
           DMPackCreateW(P9,"RegistrationPeriod",2,1);
           DMPackCreateParamTSW(P9,"Realm","String(255)","string",1);
           DMPackCreateW(P9,"TimerT1",2,1);
           DMPackCreateW(P9,"TimerT2",2,1);
           DMPackCreateW(P9,"TimerT4",2,1);
           DMPackCreateW(P9,"TimerA",2,1);
           DMPackCreateW(P9,"TimerB",2,1);
           DMPackCreateW(P9,"TimerC",2,1);
           DMPackCreateW(P9,"TimerD",2,1);
           DMPackCreateW(P9,"TimerE",2,1);
           DMPackCreateW(P9,"TimerF",2,1);
           DMPackCreateW(P9,"TimerG",2,1);
           DMPackCreateW(P9,"TimerH",2,1);
           DMPackCreateW(P9,"TimerI",2,1);
           DMPackCreateW(P9,"TimerJ",2,1);
           DMPackCreateW(P9,"TimerK",2,1);
           DMPackCreateW(P9,"InviteExpires",2,1);
           DMPackCreateW(P9,"ReInviteExpires",2,1);
           DMPackCreateW(P9,"RegisterExpires",2,1);
           DMPackCreateW(P9,"RegisterRetryInterval",2,1);
           DMPackCreateParamTSW(P9,"InboundAuth","string: None(0),Digest(1),SourceFilter(2)","uint32/mapped",1);
           DMPackCreateParamTSW(P9,"InboundAuthUsername","String(256)","string",1);
           DMPackCreateParamTSW(P9,"InboundAuthPassword","String(256)","string",1);
           DMPackCreateW(P9,"UseCodecPriorityInSDPResponse",0,1);
           DMPackCreateW(P9,"DSCPMark",2,1);
           DMPackCreateW(P9,"VLANIDMark",1,1);
           DMPackCreateW(P9,"EthernetPriorityMark",1,1);
           DMPackCreateParamTSW(P9,"ConferenceCallDomainURI","String(256)","string",1);
           DMPackCreateW(P9,"TimerLoginRejected",2,1);
           DMPackCreateW(P9,"NoLoginRetry",0,1);
           DMPackCreateW(P9,"TimerRegistrationFailed",2,1);
           DMPackCreateW(P9,"TimerSubscriptionFailed",2,1);
           DMPackCreateParam(P9,"UnansweredRegistrationAttempts",2);
           DMPackCreateParamTSW(P9,"VoIPProfile","String(256)","string",1);
           DMPackCreateParamTSW(P9,"CodecList","String(255)","string",1);
           DMPackCreateW(P9,"MaxSessions",2,1);
           DMPackCreateParam(P9,"X_RDK_SKBMark",2);
           DMPackCreateW(P9,"X_RDK-Central_COM_ConferencingURI",3,1);
           DMPackCreateW(P9,"X_RDK-Central_COM_NetworkDisconnect",0,1);
           DMPackCreateW(P9,"X_RDK_PRACKRequired",0,1);
          P9=DMPackCreatePNode(P8,"objects");
           P10=DMPackCreateObject(P9, 2,"FQDNServer","128");
            DMPackCreateFunctions(P10,"TelcoVoiceMgrDml_SIP_NetworkList_FQDNServerList",13,5,6,0,2,12,17,13,18,10,15,20,21,22);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateW(P11,"Enable",0,1);
             DMPackCreateParamTSW(P11,"Alias","string(64)","string",1);
             DMPackCreateParamTS(P11,"Origin","string: AutoConfigured(0),Static(1)","uint32/mapped");
             DMPackCreateParamTSW(P11,"Domain","String(256)","string",1);
             DMPackCreateW(P11,"Weight",2,1);
             DMPackCreateW(P11,"Priority",2,1);
             DMPackCreateW(P11,"Port",2,1);
             DMPackCreateParamTSW(P11,"IPAddresses","String(255)","string",1);
           P10=DMPackCreateObject(P9, 2,"EventSubscribe","128");
            DMPackCreateFunctions(P10,"TelcoVoiceMgrDml_SIP_NetworkList_EvtSubList",13,5,6,0,2,12,17,13,18,10,15,20,21,22);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateW(P11,"Enable",0,1);
             DMPackCreateParamTSW(P11,"Alias","string(64)","string",1);
             DMPackCreateParamTSW(P11,"Event","String(32)","string",1);
             DMPackCreateParamTSW(P11,"Notifier","String(256)","string",1);
             DMPackCreateW(P11,"NotifierPort",2,1);
             DMPackCreateParamTSW(P11,"NotifierTransport","string: UDP(0),TCP(1),TLS(2),SCTP(3)","uint32/mapped",1);
             DMPackCreateW(P11,"ExpireTime",2,1);
           P10=DMPackCreateObject(P9, 2,"ResponseMap","128");
            DMPackCreateFunctions(P10,"TelcoVoiceMgrDml_SIP_NetworkList_RespMapList",13,5,6,0,2,12,17,13,18,10,15,20,21,22);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateParamTSW(P11,"Alias","string(64)","string",1);
             DMPackCreateW(P11,"SIPResponseNumber",2,1);
             DMPackCreateW(P11,"Enable",0,1);
             DMPackCreateParamTSW(P11,"TextMessage","String(64)","string",1);
             DMPackCreateParamTSW(P11,"Tone","String(256)","string",1);
         P8=DMPackCreateObject(P7, 2,"Proxy","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_SIP_ProxyList",13,5,6,0,2,12,17,13,18,10,15,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
           DMPackCreateParamTS(P9,"Status","string: Up(0),Error(1),Disabled(2)","uint32/mapped");
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateParamTS(P9,"Origin","string: AutoConfigured(0),Static(1)","uint32/mapped");
           DMPackCreateParamTSW(P9,"ProxyIPAddress","String(45)","string",1);
           DMPackCreateW(P9,"ProxyPort",2,1);
           DMPackCreateParamTS(P9,"ContactURI","String(256)","string");
           DMPackCreateParamTSW(P9,"VoIPProfile","String(256)","string",1);
         P8=DMPackCreateObject(P7, 2,"Registrar","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_SIP_RegistrarList",13,5,6,0,2,12,17,13,18,10,15,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
           DMPackCreateW(P9,"QuiescentMode",0,1);
           DMPackCreateParamTS(P9,"Status","string: Up(0),Error(1),Disabled(2)","uint32/mapped");
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateParamTS(P9,"Origin","string: AutoConfigured(0),Static(1)","uint32/mapped");
           DMPackCreateParamTSW(P9,"RegistrarIPAddress","String(45)","string",1);
           DMPackCreateW(P9,"RegistrarPort",2,1);
           DMPackCreateW(P9,"RegisterExpires",2,1);
           DMPackCreateW(P9,"PingInterval",2,1);
           DMPackCreateParamTSW(P9,"Organization","String(256)","string",1);
           DMPackCreateParamTSW(P9,"Realm","String(255)","string",1);
           DMPackCreateParamTSW(P9,"VoIPProfile","String(256)","string",1);
           DMPackCreateParamTS(P9,"ContactURI","String(256)","string");
          P9=DMPackCreatePNode(P8,"objects");
           P10=DMPackCreateObject(P9, 2,"Account","128");
            DMPackCreateFunctions(P10,"TelcoVoiceMgrDml_SIP_RegistrarList_AccountList",13,5,6,0,2,12,17,13,18,10,15,20,21,22);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateParamTSW(P11,"Enable","string: Enable(0),Quiescent(1),Disable(2)","uint32/mapped",1);
             DMPackCreateW(P11,"QuiescentMode",0,1);
             DMPackCreateParamTS(P11,"Status","string: Up(0),Initializing(1),Registering(2),Deregistering(3),Error_Misconfigured(4),Error_Network(5),Error_Registration(6),Quiescent(7),Disabled(8)","uint32/mapped");
             DMPackCreateParamTSW(P11,"Alias","string(64)","string",1);
             DMPackCreateParamTS(P11,"Origin","string: AutoConfigured(0),Static(1)","uint32/mapped");
             DMPackCreateParamTS(P11,"CallStatus","string: Idle(0),Dialing(1),Delivered(2),Connected(3),Alerting(4),Disconnected(5)","uint32/mapped");
             DMPackCreateParamTSW(P11,"AuthUserName","String(128)","string",1);
             DMPackCreateParamTSW(P11,"AuthPassword","String(128)","string",1);
             DMPackCreateParamTS(P11,"RegistrationStatus","string: Registered(0),Unregistered(1)","uint32/mapped");
             DMPackCreateParamTSW(P11,"URI","String(389)","string",1);
             DMPackCreateParamTSW(P11,"Domain","String(256)","string",1);
             DMPackCreateParamTSW(P11,"CodecList","String(255)","string",1);
             DMPackCreateParamTSW(P11,"VoIPProfile","String(256)","string",1);
            P11=DMPackCreatePNode(P10,"objects");
             P12=DMPackCreateObject(P11, 2,"Contact","128");
              DMPackCreateFunctions(P12,"TelcoVoiceMgrDml_SIP_RegistrarList_AccountList_ContactList",12,5,6,0,2,12,13,18,10,15,20,21,22);
              P13=DMPackCreatePNode(P12,"parameters");
               DMPackCreateW(P13,"Enable",0,1);
               DMPackCreateParamTS(P13,"Status","string: Up(0),Error(1),Disabled(2)","uint32/mapped");
               DMPackCreateParamTSW(P13,"Alias","string(64)","string",1);
               DMPackCreateParamTS(P13,"Origin","string: AutoConfigured(0),Static(1)","uint32/mapped");
               DMPackCreateParamTSW(P13,"IPAddress","String(45)","string",1);
               DMPackCreateW(P13,"Port",2,1);
               DMPackCreateParamTSW(P13,"ContactURI","String(256)","string",1);
               DMPackCreateParamTS(P13,"ExpireTime","String(255)","string");
               DMPackCreateParamTSW(P13,"UserAgent","String(64)","string",1);
       P6=DMPackCreateObject(P5, 0,"MGCP",0);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 2,"Client","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_MGCP_ClientList",13,5,6,0,2,12,17,13,18,10,15,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
           DMPackCreateW(P9,"QuiescentMode",0,1);
           DMPackCreateParamTS(P9,"Status","string: Up(0),Initializing(1),Registering(2),Deregistering(3),Error_Misconfigured(4),Error_Network(5),Error_Registration(6),Quiescent(7),Disabled(8)","uint32/mapped");
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateParamTSW(P9,"RegisterMode","string: Wildcard(0),Individual(1)","uint32/mapped",1);
           DMPackCreateW(P9,"LocalPort",2,1);
           DMPackCreateParamTSW(P9,"Domain","String(256)","string",1);
           DMPackCreateParamTSW(P9,"User","String(64)","string",1);
           DMPackCreateParamTSW(P9,"Network","String(256)","string",1);
           DMPackCreateW(P9,"MaxSessions",2,1);
         P8=DMPackCreateObject(P7, 2,"Network","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_MGCP_NetworkList",15,5,6,0,2,12,17,13,18,11,16,10,15,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
           DMPackCreateW(P9,"QuiescentMode",0,1);
           DMPackCreateParamTS(P9,"Status","string: Up(0),Resolving(1),Error_DNS(2),Error_Other(3),Disabled(4)","uint32/mapped");
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateParamTSW(P9,"CallAgent1","String(256)","string",1);
           DMPackCreateW(P9,"CallAgentPort1",2,1);
           DMPackCreateParamTSW(P9,"CallAgent2","String(256)","string",1);
           DMPackCreateW(P9,"CallAgentPort2",2,1);
           DMPackCreateW(P9,"RetranIntervalTimer",2,1);
           DMPackCreateW(P9,"MaxRetranCount",2,1);
           DMPackCreateW(P9,"DSCPMark",2,1);
           DMPackCreateW(P9,"VLANIDMark",1,1);
           DMPackCreateW(P9,"EthernetPriorityMark",1,1);
           DMPackCreateW(P9,"AllowPiggybackEvents",0,1);
           DMPackCreateW(P9,"SendRSIPImmediately",0,1);
           DMPackCreateW(P9,"STUNEnable",0,1);
           DMPackCreateParamTSW(P9,"STUNServer","String(256)","string",1);
           DMPackCreateW(P9,"NonVoiceBandwidthReservedUpstream",2,1);
           DMPackCreateW(P9,"NonVoiceBandwidthReservedDownstream",2,1);
           DMPackCreateW(P9,"MaxSessions",2,1);
           DMPackCreateParamTSW(P9,"VoIPProfile","String(256)","string",1);
           DMPackCreateParamTSW(P9,"CodecList","String(255)","string",1);
       P6=DMPackCreateObject(P5, 0,"H323",0);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 2,"Client","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_H323_ClientList",13,5,6,0,2,12,17,13,18,10,15,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
           DMPackCreateW(P9,"QuiescentMode",0,1);
           DMPackCreateParamTS(P9,"Status","string: Up(0),Initializing(1),Registering(2),Deregistering(3),Error_Misconfigured(4),Error_Network(5),Error_Registration(6),Quiescent(7),Disabled(8)","uint32/mapped");
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateW(P9,"H235Authentication",0,1);
           DMPackCreateParamTSW(P9,"AuthPassword","String(255)","string",1);
           DMPackCreateParamTSW(P9,"SendersID","String(255)","string",1);
           DMPackCreateParamTSW(P9,"Network","String(256)","string",1);
           DMPackCreateParamTSW(P9,"H323ID","String(32)","string",1);
           DMPackCreateW(P9,"MaxSessions",2,1);
         P8=DMPackCreateObject(P7, 2,"Network","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_H323_NetworkList",15,5,6,0,2,12,17,13,18,11,16,10,15,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
           DMPackCreateW(P9,"QuiescentMode",0,1);
           DMPackCreateParamTS(P9,"Status","string: Up(0),Resolving(1),Error_DNS(2),Error_Other(3),Disabled(4)","uint32/mapped");
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateParamTSW(P9,"Gatekeeper","String(255)","string",1);
           DMPackCreateW(P9,"GatekeeperPort",2,1);
           DMPackCreateParamTSW(P9,"GatekeeperID","String(255)","string",1);
           DMPackCreateW(P9,"TimeToLive",2,1);
           DMPackCreateW(P9,"DSCPMark",2,1);
           DMPackCreateW(P9,"VLANIDMark",1,1);
           DMPackCreateW(P9,"EthernetPriorityMark",1,1);
           DMPackCreateW(P9,"STUNEnable",0,1);
           DMPackCreateParamTSW(P9,"STUNServer","String(256)","string",1);
           DMPackCreateW(P9,"NonVoiceBandwidthReservedUpstream",2,1);
           DMPackCreateW(P9,"NonVoiceBandwidthReservedDownstream",2,1);
           DMPackCreateW(P9,"MaxSessions",2,1);
           DMPackCreateParamTSW(P9,"VoIPProfile","String(256)","string",1);
           DMPackCreateParamTSW(P9,"CodecList","String(255)","string",1);
       P6=DMPackCreateObject(P5, 2,"Trunk","128");
        DMPackCreateFunctions(P6,"TelcoVoiceMgrDml_TrunkList",15,5,6,0,2,12,17,13,18,11,16,10,15,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"Enable",0,1);
         DMPackCreateW(P7,"QuiescentMode",0,1);
         DMPackCreateParamTS(P7,"Status","string: Up(0),Initializing(1),Registering(2),Unregistering(3),Error(4),Testing(5),Disabled(6)","uint32/mapped");
         DMPackCreateParamTSW(P7,"Alias","string(64)","string",1);
         DMPackCreateParamTS(P7,"Origin","string: AutoConfigured(0),Static(1)","uint32/mapped");
         DMPackCreateParamTSW(P7,"Name","String(16)","string",1);
         DMPackCreateParamTSW(P7,"DDIRange","String(255)","string",1);
         DMPackCreateW(P7,"LineObjectCreation",0,1);
         DMPackCreateW(P7,"MaxChannels",2,1);
         DMPackCreateW(P7,"MaxOutboundChannelCount",1,1);
         DMPackCreateW(P7,"MaxInboundChannelCount",1,1);
         DMPackCreateParamTSW(P7,"CodecPriority","string: Local(0),Remote(1)","uint32/mapped",1);
         DMPackCreateParamTSW(P7,"Provider","String(256)","string",1);
       P6=DMPackCreateObject(P5, 0,"CallControl",0);
        DMPackCreateFunctions(P6,"TelcoVoiceMgrDml_CallControl",2,12,17);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"MaxNumberOfLines",2,1);
         DMPackCreateW(P7,"MaxNumberOfExtensions",2,1);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 2,"Line","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_CallControl_LineList",12,5,6,0,2,12,13,18,10,15,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
           DMPackCreateW(P9,"QuiescentMode",0,1);
           DMPackCreateParamTS(P9,"Status","string: Up(0),Error(1),Testing(2),Quiescent(3),Disabled(4)","uint32/mapped");
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateParamTS(P9,"CallStatus","string: Idle(0),Dialing(1),Delivered(2),Connected(3),Alerting(4),Disconnected(5)","uint32/mapped");
           DMPackCreateParamTS(P9,"Origin","string: Static(0),DDIRange(1)","uint32/mapped");
           DMPackCreateParamTSW(P9,"DirectoryNumber","String(32)","string",1);
           DMPackCreateParamTSW(P9,"Provider","String(256)","string",1);
           DMPackCreateParamTSW(P9,"CallingFeatures","String(256)","string",1);
          P9=DMPackCreatePNode(P8,"objects");
           P10=DMPackCreateObject(P9, 0,"Stats",0);
            P11=DMPackCreatePNode(P10,"objects");
             P12=DMPackCreateObject(P11, 0,"IncomingCalls",0);
              DMPackCreateFunctions(P12,"TelcoVoiceMgrDml_CallControl_LineList_stats_InCalls",1,12);
              P13=DMPackCreatePNode(P12,"parameters");
               DMPackCreateParam(P13,"CallsReceived",2);
               DMPackCreateParam(P13,"CallsConnected",2);
               DMPackCreateParam(P13,"CallsFailed",2);
               DMPackCreateParam(P13,"CallsDropped",2);
               DMPackCreateParam(P13,"TotalCallTime",2);
             P12=DMPackCreateObject(P11, 0,"OutgoingCalls",0);
              DMPackCreateFunctions(P12,"TelcoVoiceMgrDml_CallControl_LineList_stats_OutCalls",1,12);
              P13=DMPackCreatePNode(P12,"parameters");
               DMPackCreateParam(P13,"CallsAttempted",2);
               DMPackCreateParam(P13,"CallsConnected",2);
               DMPackCreateParam(P13,"CallsFailed",2);
               DMPackCreateParam(P13,"CallsDropped",2);
               DMPackCreateParam(P13,"TotalCallTime",2);
             P12=DMPackCreateObject(P11, 0,"RTP",0);
              DMPackCreateFunctions(P12,"TelcoVoiceMgrDml_CallControl_LineList_stats_RTP",1,12);
              P13=DMPackCreatePNode(P12,"parameters");
               DMPackCreateParam(P13,"PacketsReceived",2);
               DMPackCreateParam(P13,"PacketsSent",2);
               DMPackCreateParam(P13,"PacketsLost",2);
               DMPackCreateParam(P13,"BytesSent",2);
               DMPackCreateParam(P13,"BytesReceived",2);
             P12=DMPackCreateObject(P11, 0,"DSP",0);
              DMPackCreateFunctions(P12,"TelcoVoiceMgrDml_CallControl_LineList_stats_DSP",1,12);
              P13=DMPackCreatePNode(P12,"parameters");
               DMPackCreateParam(P13,"Overruns",2);
               DMPackCreateParam(P13,"Underruns",2);
         P8=DMPackCreateObject(P7, 2,"Extension","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_CallControl_ExtensionList",12,5,6,0,2,12,13,18,10,15,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
           DMPackCreateW(P9,"QuiescentMode",0,1);
           DMPackCreateParamTS(P9,"Status","string: Up(0),Initializing(1),Error(2),Testing(3),Quiescent(4),Disabled(5)","uint32/mapped");
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateParamTS(P9,"CallStatus","string: Idle(0),Dialing(1),Delivered(2),Connected(3),Alerting(4),Disconnected(5)","uint32/mapped");
           DMPackCreateParamTS(P9,"Origin","string: AutoConfigured(0),Static(1)","uint32/mapped");
           DMPackCreateParamTSW(P9,"Name","String(256)","string",1);
           DMPackCreateParamTSW(P9,"ExtensionNumber","String(32)","string",1);
           DMPackCreateParamTSW(P9,"Provider","String(256)","string",1);
           DMPackCreateParamTSW(P9,"NumberingPlan","String(256)","string",1);
           DMPackCreateParamTSW(P9,"X_RDK_FacilityAction","String(64)","string",1);
           DMPackCreateParamTSW(P9,"X_RDK_FacilityActionArgument","String(256)","string",1);
           DMPackCreateParamTS(P9,"X_RDK_FacilityActionResult","string: Idle(0),InProgress(1),Success(2),Error_Not_In_Reach(3),Error_TimeOut(4)","uint32/mapped");
           DMPackCreateParamTSW(P9,"CallingFeatures","String(256)","string",1);
           DMPackCreateParamTS(P9,"CallWaitingStatus","string: Disabled(0),Idle(1),SecondaryRinging(2),SecondaryConnecting(3),SecondaryConnected(4)","uint32/mapped");
           DMPackCreateParamTS(P9,"ConferenceCallingStatus","string: Disabled(0),Idle(1),SecondaryCalling(2),SecondaryConnecting(3),SecondaryConnected(4),InConferenceCall(5)","uint32/mapped");
           DMPackCreateParam(P9,"ConferenceCallingSessionCount",2);
           DMPackCreateParamTSW(P9,"VoiceMail","String(256)","string",1);
          P9=DMPackCreatePNode(P8,"objects");
           P10=DMPackCreateObject(P9, 0,"Stats",0);
            P11=DMPackCreatePNode(P10,"objects");
             P12=DMPackCreateObject(P11, 0,"IncomingCalls",0);
              DMPackCreateFunctions(P12,"TelcoVoiceMgrDml_CallControl_ExtensionList_Stats_InCalls",1,12);
              P13=DMPackCreatePNode(P12,"parameters");
               DMPackCreateParam(P13,"CallsReceived",2);
               DMPackCreateParam(P13,"CallsConnected",2);
               DMPackCreateParam(P13,"CallsFailed",2);
               DMPackCreateParam(P13,"CallsDropped",2);
               DMPackCreateParam(P13,"TotalCallTime",2);
             P12=DMPackCreateObject(P11, 0,"OutgoingCalls",0);
              DMPackCreateFunctions(P12,"TelcoVoiceMgrDml_CallControl_ExtensionList_Stats_OutCalls",1,12);
              P13=DMPackCreatePNode(P12,"parameters");
               DMPackCreateParam(P13,"CallsAttempted",2);
               DMPackCreateParam(P13,"CallsConnected",2);
               DMPackCreateParam(P13,"CallsFailed",2);
               DMPackCreateParam(P13,"CallsDropped",2);
               DMPackCreateParam(P13,"TotalCallTime",2);
             P12=DMPackCreateObject(P11, 0,"RTP",0);
              DMPackCreateFunctions(P12,"TelcoVoiceMgrDml_CallControl_ExtensionList_Stats_RTP",1,12);
              P13=DMPackCreatePNode(P12,"parameters");
               DMPackCreateParam(P13,"PacketsReceived",2);
               DMPackCreateParam(P13,"PacketsSent",2);
               DMPackCreateParam(P13,"PacketsLost",2);
               DMPackCreateParam(P13,"BytesSent",2);
               DMPackCreateParam(P13,"BytesReceived",2);
             P12=DMPackCreateObject(P11, 0,"DSP",0);
              DMPackCreateFunctions(P12,"TelcoVoiceMgrDml_CallControl_ExtensionList_Stats_DSP",1,12);
              P13=DMPackCreatePNode(P12,"parameters");
               DMPackCreateParam(P13,"Overruns",2);
               DMPackCreateParam(P13,"Underruns",2);
         P8=DMPackCreateObject(P7, 2,"Group","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_CallControl_GroupList",11,5,6,0,2,12,17,13,18,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateParamTSW(P9,"Extensions","String(2048)","string",1);
           DMPackCreateParamTSW(P9,"RingType","string: Simultaneous(0),Hierarchical(1),Cyclic(2)","uint32/mapped",1);
           DMPackCreateW(P9,"RingTimeout",2,1);
         P8=DMPackCreateObject(P7, 2,"Mailbox","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_CallControl_MailboxList",13,5,6,0,2,12,17,13,18,10,15,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateW(P9,"MaxMsg",2,1);
           DMPackCreateW(P9,"MaxMessageTime",2,1);
           DMPackCreateW(P9,"MinSize",2,1);
           DMPackCreateParamTSW(P9,"SMTPServerAddress","String(256)","string",1);
           DMPackCreateW(P9,"SMTPServerPort",2,1);
           DMPackCreateParamTSW(P9,"SMTPUser","String(256)","string",1);
           DMPackCreateParamTSW(P9,"SMTPPassword","String(256)","string",1);
           DMPackCreateParamTSW(P9,"SMTPAuthenticationType","string: None(0),SSL(1),TLS(2),Auto(3)","uint32/mapped",1);
           DMPackCreateParamTSW(P9,"SMTPFrom","String(256)","string",1);
         P8=DMPackCreateObject(P7, 2,"IncomingMap","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_CallControl_IncomingMapList",13,5,6,0,2,12,17,13,18,10,15,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateParamTSW(P9,"Line","String(256)","string",1);
           DMPackCreateParamTSW(P9,"Extension","String(256)","string",1);
           DMPackCreateW(P9,"Order",2,1);
           DMPackCreateW(P9,"Timeout",2,1);
         P8=DMPackCreateObject(P7, 3,"OutgoingMap","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_CallControl_OutgoingMapList",15,5,6,0,2,3,4,12,17,13,18,10,15,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateParamTSW(P9,"CLIPNoScreeningNumber","String(32)","string",1);
           DMPackCreateParamTSW(P9,"Extension","String(256)","string",1);
           DMPackCreateParamTSW(P9,"Line","String(256)","string",1);
           DMPackCreateW(P9,"Order",2,1);
         P8=DMPackCreateObject(P7, 3,"NumberingPlan","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_CallControl_NumberingPlanList",13,5,6,0,2,3,4,12,17,13,18,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateW(P9,"MinimumNumberOfDigits",2,1);
           DMPackCreateW(P9,"MaximumNumberOfDigits",2,1);
           DMPackCreateW(P9,"InterDigitTimerStd",2,1);
           DMPackCreateW(P9,"InterDigitTimerOpen",2,1);
           DMPackCreateParamTSW(P9,"TerminationDigit","String(1)","string",1);
           DMPackCreateParamTSW(P9,"InvalidNumberTone","String(256)","string",1);
           DMPackCreateParam(P9,"PrefixInfoMaxEntries",2);
          P9=DMPackCreatePNode(P8,"objects");
           P10=DMPackCreateObject(P9, 2,"PrefixInfo","128");
            DMPackCreateFunctions(P10,"TelcoVoiceMgrDml_CallControl_NumberingPlanList_PrefixInfoList",13,5,6,0,2,12,17,13,18,10,15,20,21,22);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateParamTSW(P11,"Alias","string(64)","string",1);
             DMPackCreateW(P11,"Enable",0,1);
             DMPackCreateParamTSW(P11,"PrefixRange","String(42)","string",1);
             DMPackCreateW(P11,"PrefixMinNumberOfDigits",2,1);
             DMPackCreateW(P11,"PrefixMaxNumberOfDigits",2,1);
             DMPackCreateW(P11,"NumberOfDigitsToRemove",2,1);
             DMPackCreateW(P11,"PosOfDigitsToRemove",2,1);
             DMPackCreateParamTSW(P11,"DialTone","String(256)","string",1);
             DMPackCreateParamTSW(P11,"FacilityAction","String(64)","string",1);
             DMPackCreateParamTSW(P11,"FacilityActionArgument","String(256)","string",1);
         P8=DMPackCreateObject(P7, 0,"CallingFeatures",0);
          P9=DMPackCreatePNode(P8,"objects");
           P10=DMPackCreateObject(P9, 2,"Set","128");
            DMPackCreateFunctions(P10,"TelcoVoiceMgrDml_CallControl_CallingFeatures_SetList",13,5,6,0,2,12,17,13,18,10,15,20,21,22);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateParamTSW(P11,"Alias","string(64)","string",1);
             DMPackCreateW(P11,"CallerIDEnable",0,1);
             DMPackCreateW(P11,"CallerIDNameEnable",0,1);
             DMPackCreateW(P11,"CallWaitingEnable",0,1);
             DMPackCreateW(P11,"CallForwardUnconditionalEnable",0,1);
             DMPackCreateParamTSW(P11,"CallForwardUnconditionalNumber","String(32)","string",1);
             DMPackCreateW(P11,"CallForwardOnBusyEnable",0,1);
             DMPackCreateParamTSW(P11,"CallForwardOnBusyNumber","String(32)","string",1);
             DMPackCreateW(P11,"CallForwardOnBusyRingTimeout",2,1);
             DMPackCreateW(P11,"CallForwardOnNoAnswerEnable",0,1);
             DMPackCreateParamTSW(P11,"CallForwardOnNoAnswerNumber","String(32)","string",1);
             DMPackCreateW(P11,"CallForwardOnNoAnswerRingTimeout",2,1);
             DMPackCreateW(P11,"CallTransferEnable",0,1);
             DMPackCreateW(P11,"MWIEnable",0,1);
             DMPackCreateW(P11,"VMWIEnable",0,1);
             DMPackCreateParam(P11,"LineMessagesWaiting",2);
             DMPackCreateW(P11,"AnonymousCallRejectionEnable",0,1);
             DMPackCreateW(P11,"AnonymousCallEnable",0,1);
             DMPackCreateW(P11,"DoNotDisturbEnable",0,1);
             DMPackCreateW(P11,"RepeatDialEnable",0,1);
             DMPackCreateW(P11,"VoiceMailEnable",0,1);
             DMPackCreateW(P11,"CallPickUpEnable",0,1);
             DMPackCreateW(P11,"CCBSEnable",0,1);
             DMPackCreateW(P11,"IIFCEnable",0,1);
             DMPackCreateW(P11,"BlockForwardEnable",0,1);
             DMPackCreateW(P11,"SecretForwarderEnable",0,1);
             DMPackCreateW(P11,"FollowMeEnable",0,1);
             DMPackCreateW(P11,"X_RDK-Central_COM_ConferenceCallingEnable",0,1);
             DMPackCreateW(P11,"X_RDK-Central_COM_HoldEnable",0,1);
             DMPackCreateW(P11,"X_RDK-Central_COM_PhoneCallerIDEnable",0,1);
            P11=DMPackCreatePNode(P10,"objects");
             P12=DMPackCreateObject(P11, 2,"CFT","128");
              DMPackCreateFunctions(P12,"TelcoVoiceMgrDml_CallControl_CallingFeatures_SetList_CFTList",11,5,6,0,2,13,18,10,15,20,21,22);
              P13=DMPackCreatePNode(P12,"parameters");
               DMPackCreateW(P13,"Enable",0,1);
               DMPackCreateParamTSW(P13,"Alias","string(64)","string",1);
               DMPackCreateParamTSW(P13,"Day","String(255)","string",1);
               DMPackCreateParamTSW(P13,"StartTime","String(5)","string",1);
               DMPackCreateParamTSW(P13,"EndTime","String(5)","string",1);
               DMPackCreateParamTSW(P13,"ForwardedToNumber","String(32)","string",1);
             P12=DMPackCreateObject(P11, 2,"SCF","128");
              DMPackCreateFunctions(P12,"TelcoVoiceMgrDml_CallControl_CallingFeatures_SetList_SCFList",11,5,6,0,2,13,18,10,15,20,21,22);
              P13=DMPackCreatePNode(P12,"parameters");
               DMPackCreateW(P13,"Enable",0,1);
               DMPackCreateParamTSW(P13,"Alias","string(64)","string",1);
               DMPackCreateParamTSW(P13,"CallingNumber","String(32)","string",1);
               DMPackCreateParamTSW(P13,"ForwardedToNumber","String(32)","string",1);
             P12=DMPackCreateObject(P11, 2,"SCREJ","128");
              DMPackCreateFunctions(P12,"TelcoVoiceMgrDml_CallControl_CallingFeatures_SetList_SCREJList",11,5,6,0,2,13,18,10,15,20,21,22);
              P13=DMPackCreatePNode(P12,"parameters");
               DMPackCreateW(P13,"Enable",0,1);
               DMPackCreateParamTSW(P13,"Alias","string(64)","string",1);
               DMPackCreateParamTSW(P13,"CallingNumber","String(32)","string",1);
             P12=DMPackCreateObject(P11, 2,"FollowMe","128");
              DMPackCreateFunctions(P12,"TelcoVoiceMgrDml_CallControl_CallingFeatures_SetList_FollowMeList",13,5,6,0,2,12,17,13,18,10,15,20,21,22);
              P13=DMPackCreatePNode(P12,"parameters");
               DMPackCreateW(P13,"Enable",0,1);
               DMPackCreateParamTSW(P13,"Alias","string(64)","string",1);
               DMPackCreateW(P13,"Delay",2,1);
               DMPackCreateParamTSW(P13,"Number","String(32)","string",1);
               DMPackCreateW(P13,"Order",2,1);
             P12=DMPackCreateObject(P11, 0,"Voice2Mail",0);
              DMPackCreateFunctions(P12,"TelcoVoiceMgrDml_CallControl_CallingFeatures_SetList_Voice2Mail",6,12,17,13,18,10,15);
              P13=DMPackCreatePNode(P12,"parameters");
               DMPackCreateW(P13,"Enable",0,1);
               DMPackCreateW(P13,"MaxMessageLength",2,1);
               DMPackCreateW(P13,"Attach",0,1);
               DMPackCreateW(P13,"KeepLocal",0,1);
               DMPackCreateParamTSW(P13,"EMailAddress","String(255)","string",1);
       P6=DMPackCreateObject(P5, 2,"Interwork","128");
        DMPackCreateFunctions(P6,"TelcoVoiceMgrDml_InterworkList",13,5,6,0,2,12,17,13,18,10,15,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"Enable",0,1);
         DMPackCreateW(P7,"QuiescentMode",0,1);
         DMPackCreateParamTS(P7,"Status","string: Up(0),Error(1),Quiescent(2),Disabled(3)","uint32/mapped");
         DMPackCreateParamTSW(P7,"Alias","string(64)","string",1);
         DMPackCreateParamTS(P7,"OperationalStatus","string: InService(0),OutOfService(1),NetworkServersOffline(2)","uint32/mapped");
         DMPackCreateParamTS(P7,"OperationalStatusReason","String(256)","string");
         DMPackCreateParamTSW(P7,"NetworkConnectionMode","string: Static(0),RegisterDynamic(1),RegisterLearn(2),RegisterStatic(3)","uint32/mapped",1);
         DMPackCreateParamTSW(P7,"UserConnectionMode","string: Static(0),RegisterDynamic(1),RegisterLearn(2)","uint32/mapped",1);
         DMPackCreateW(P7,"E164Mode",0,1);
         DMPackCreateParamTSW(P7,"NetworkAuthenticationChallengeMode","string: PassThru(0),RespondLocal(1),Hop-by-Hop(2)","uint32/mapped",1);
         DMPackCreateParamTS(P7,"NetworkIPAddress","String(45)","string");
         DMPackCreateParamTSW(P7,"InterworkingRuleSetURI","String(256)","string",1);
         DMPackCreateW(P7,"InterworkingRuleSetInterval",2,1);
         DMPackCreateParamTSW(P7,"InterworkingRuleSetTime","String(255)","string",1);
         DMPackCreateParamTSW(P7,"FirewallRuleSetURI","String(256)","string",1);
         DMPackCreateW(P7,"FirewallRuleSetInterval",2,1);
         DMPackCreateParamTSW(P7,"FirewallRuleSetTime","String(255)","string",1);
         DMPackCreateParamTSW(P7,"InterworkName","String(256)","string",1);
         DMPackCreateParamTSW(P7,"ProxyServer","String(256)","string",1);
         DMPackCreateParamTSW(P7,"Networks","String(255)","string",1);
         DMPackCreateParamTSW(P7,"E164Client","String(256)","string",1);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 2,"UserInterface","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_InterworkList_UIList",11,5,6,0,2,13,18,10,15,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateParamTSW(P9,"Registrar","String(256)","string",1);
           DMPackCreateParamTSW(P9,"Network","String(256)","string",1);
         P8=DMPackCreateObject(P7, 2,"Map","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_InterworkList_MapList",13,5,6,0,2,12,17,13,18,10,15,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
           DMPackCreateParamTS(P9,"Status","String(255)","string");
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateParamTS(P9,"StatusDescription","String(256)","string");
           DMPackCreateParamTS(P9,"LastTime","String(255)","string");
           DMPackCreateParamTS(P9,"Origin","String(255)","string");
           DMPackCreateParamTSW(P9,"NetworkConnection","String(256)","string",1);
           DMPackCreateParamTSW(P9,"UserConnection","String(256)","string",1);
           DMPackCreateParamTSW(P9,"DigitMap","String(256)","string",1);
           DMPackCreateW(P9,"DigitMapEnable",0,1);
           DMPackCreateW(P9,"Priority",2,1);
       P6=DMPackCreateObject(P5, 2,"CallLog","128");
        DMPackCreateFunctions(P6,"TelcoVoiceMgrDml_CallLogList",10,5,6,0,2,12,13,18,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateParamTSW(P7,"Alias","string(64)","string",1);
         DMPackCreateParamTS(P7,"CallingPartyNumber","String(256)","string");
         DMPackCreateParamTS(P7,"CalledPartyNumber","String(256)","string");
         DMPackCreateParamTS(P7,"Source","String(256)","string");
         DMPackCreateParamTS(P7,"Destination","String(256)","string");
         DMPackCreateParamTS(P7,"RemoteParty","String(32)","string");
         DMPackCreateParamTS(P7,"UsedLine","String(256)","string");
         DMPackCreateParamTS(P7,"UsedExtensions","String(255)","string");
         DMPackCreateParamTS(P7,"Direction","string: Incoming(0),Outgoing(1)","uint32/mapped");
         DMPackCreateParamTS(P7,"Start","String(255)","string");
         DMPackCreateParam(P7,"Duration",2);
         DMPackCreateParamTS(P7,"CallTerminationCause","string: NoExtensionsMapped(0),NoExtensionsAvailable(1),AnonymousCallRejection(2),CallWaitingRejected(3),CallForwardingUnconditional(4),CallForwardingBusy(5),CallForwardingNoReply(6),LocalDisconnect(7),LocalForbidden(8),LocalTimeout(9),LocalMediaError(10),LocalPriority(11),LocalReject(12),LocalTransfer(13),LocalInternalError(14),RemoteDisconnect(15),RemoteBadRequest(16),RemoteForbidden(17),RemoteNotFound(18),RemoteReject(19),RemoteNotAllowed(20),RemoteNotAcceptable(21),RemoteTimeout(22),RemoteUnavailable(23),RemoteBusy(24),RemoteNotSupported(25),RemoteNetworkFailure(26)","uint32/mapped");
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 2,"SignalingPerformance","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_CallLogList_SignalPerfList",11,5,6,0,2,12,17,11,16,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateParamTS(P9,"Protocol","string: H323(0),SIP(1) ","uint32/mapped");
           DMPackCreateParam(P9,"CallSetupDelay",2);
           DMPackCreateParam(P9,"OutgoingMediaEstablishDelay",1);
           DMPackCreateParam(P9,"IncomingMediaEstablishDelay",1);
         P8=DMPackCreateObject(P7, 2,"Session","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_CallLogList_SessionList",9,5,6,0,2,12,13,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateParamTS(P9,"StreamType","string: Audio(0),Video(1),Fax(2),Modem(3)","uint32/mapped");
           DMPackCreateParamTS(P9,"Start","String(255)","string");
           DMPackCreateParam(P9,"Duration",2);
           DMPackCreateParamTS(P9,"SessionID","String(16)","string");
          P9=DMPackCreatePNode(P8,"objects");
           P10=DMPackCreateObject(P9, 0,"X_RDKCENTRAL-COM_Stats",0);
            DMPackCreateFunctions(P10,"TelcoVoiceMgrDml_CallLogList_SessionList_Stats",1,12);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateParam(P11,"MOSCQScore",2);
             DMPackCreateParam(P11,"MOSLQScore",2);
             DMPackCreateParam(P11,"RFactor",2);
           P10=DMPackCreateObject(P9, 0,"Source",0);
            P11=DMPackCreatePNode(P10,"objects");
             P12=DMPackCreateObject(P11, 0,"RTP",0);
              DMPackCreateFunctions(P12,"TelcoVoiceMgrDml_CallLogList_SessionList_source_RTP",3,12,13,11);
              P13=DMPackCreatePNode(P12,"parameters");
               DMPackCreateParamTS(P13,"FarEndIPAddress","String(45)","string");
               DMPackCreateParam(P13,"FarEndUDPPort",2);
               DMPackCreateParam(P13,"LocalUDPPort",2);
               DMPackCreateParam(P13,"MinJitter",1);
               DMPackCreateParam(P13,"MaxJitter",1);
               DMPackCreateParam(P13,"MeanJitter",1);
               DMPackCreateParam(P13,"PacketDelayVariation",1);
               DMPackCreateParam(P13,"BufferDelay",1);
               DMPackCreateParam(P13,"BurstCount",2);
               DMPackCreateParam(P13,"PacketsReceived",2);
               DMPackCreateParam(P13,"PacketsSent",2);
               DMPackCreateParam(P13,"PacketsLost",2);
               DMPackCreateParam(P13,"PacketsDiscarded",2);
               DMPackCreateParam(P13,"BytesReceived",2);
               DMPackCreateParam(P13,"BytesSent",2);
               DMPackCreateParam(P13,"ReceivePacketLossRate",2);
               DMPackCreateParam(P13,"FarEndPacketLossRate",2);
               DMPackCreateParam(P13,"ReceiveInterarrivalJitter",1);
               DMPackCreateParam(P13,"FarEndInterarrivalJitter",1);
               DMPackCreateParam(P13,"AverageReceiveInterarrivalJitter",1);
               DMPackCreateParam(P13,"AverageFarEndInterarrivalJitter",1);
               DMPackCreateParam(P13,"RoundTripDelay",1);
               DMPackCreateParam(P13,"AverageRoundTripDelay",1);
               DMPackCreateParam(P13,"SamplingFrequency",2);
             P12=DMPackCreateObject(P11, 0,"DSP",0);
              P13=DMPackCreatePNode(P12,"objects");
               P14=DMPackCreateObject(P13, 0,"ReceiveCodec",0);
                DMPackCreateFunctions(P14,"TelcoVoiceMgrDml_CallLogList_SessionList_source_DSP_RecvCodec",3,12,13,10);
                P15=DMPackCreatePNode(P14,"parameters");
                 DMPackCreateParamTS(P15,"Codec","String(256)","string");
                 DMPackCreateParam(P15,"SilenceSuppression",0);
                 DMPackCreateParam(P15,"Overruns",2);
                 DMPackCreateParam(P15,"Underruns",2);
               P14=DMPackCreateObject(P13, 0,"TransmitCodec",0);
                DMPackCreateFunctions(P14,"TelcoVoiceMgrDml_CallLogList_SessionList_source_DSP_TXCodec",3,12,13,10);
                P15=DMPackCreatePNode(P14,"parameters");
                 DMPackCreateParamTS(P15,"Codec","String(256)","string");
                 DMPackCreateParam(P15,"SilenceSuppression",0);
                 DMPackCreateParam(P15,"PacketizationPeriod",2);
                 DMPackCreateParam(P15,"Overruns",2);
                 DMPackCreateParam(P15,"Underruns",2);
             P12=DMPackCreateObject(P11, 0,"VoiceQuality",0);
              DMPackCreateFunctions(P12,"TelcoVoiceMgrDml_CallLogList_SessionList_source_VoiceQuality",2,13,12);
              P13=DMPackCreatePNode(P12,"parameters");
               DMPackCreateParamTS(P13,"VoIPQualityIndicator","String(255)","string");
               DMPackCreateParamTS(P13,"WorstVoIPQualityIndicatorsValues","String(255)","string");
               DMPackCreateParamTS(P13,"WorstVoIPQualityIndicatorTimestamps","String(255)","string");
           P10=DMPackCreateObject(P9, 0,"Destination",0);
            P11=DMPackCreatePNode(P10,"objects");
             P12=DMPackCreateObject(P11, 0,"RTP",0);
              DMPackCreateFunctions(P12,"TelcoVoiceMgrDml_CallLogList_SessionList_Dest_RTP",3,12,13,11);
              P13=DMPackCreatePNode(P12,"parameters");
               DMPackCreateParamTS(P13,"FarEndIPAddress","String(45)","string");
               DMPackCreateParam(P13,"FarEndUDPPort",2);
               DMPackCreateParam(P13,"LocalUDPPort",2);
               DMPackCreateParam(P13,"MinJitter",1);
               DMPackCreateParam(P13,"MaxJitter",1);
               DMPackCreateParam(P13,"MeanJitter",1);
               DMPackCreateParam(P13,"PacketDelayVariation",1);
               DMPackCreateParam(P13,"BufferDelay",1);
               DMPackCreateParam(P13,"BurstCount",2);
               DMPackCreateParam(P13,"PacketsReceived",2);
               DMPackCreateParam(P13,"PacketsSent",2);
               DMPackCreateParam(P13,"PacketsLost",2);
               DMPackCreateParam(P13,"PacketsDiscarded",2);
               DMPackCreateParam(P13,"BytesReceived",2);
               DMPackCreateParam(P13,"BytesSent",2);
               DMPackCreateParam(P13,"ReceivePacketLossRate",2);
               DMPackCreateParam(P13,"FarEndPacketLossRate",2);
               DMPackCreateParam(P13,"ReceiveInterarrivalJitter",1);
               DMPackCreateParam(P13,"FarEndInterarrivalJitter",1);
               DMPackCreateParam(P13,"AverageReceiveInterarrivalJitter",1);
               DMPackCreateParam(P13,"AverageFarEndInterarrivalJitter",1);
               DMPackCreateParam(P13,"RoundTripDelay",1);
               DMPackCreateParam(P13,"AverageRoundTripDelay",1);
               DMPackCreateParam(P13,"SamplingFrequency",2);
             P12=DMPackCreateObject(P11, 0,"DSP",0);
              P13=DMPackCreatePNode(P12,"objects");
               P14=DMPackCreateObject(P13, 0,"ReceiveCodec",0);
                DMPackCreateFunctions(P14,"TelcoVoiceMgrDml_CallLogList_SessionList_Dest_DSP_RxCodec",3,12,13,10);
                P15=DMPackCreatePNode(P14,"parameters");
                 DMPackCreateParamTS(P15,"Codec","String(256)","string");
                 DMPackCreateParam(P15,"SilenceSuppression",0);
                 DMPackCreateParam(P15,"Overruns",2);
                 DMPackCreateParam(P15,"Underruns",2);
               P14=DMPackCreateObject(P13, 0,"TransmitCodec",0);
                DMPackCreateFunctions(P14,"TelcoVoiceMgrDml_CallLogList_SessionList_Dest_DSP_TxCodec",3,12,13,10);
                P15=DMPackCreatePNode(P14,"parameters");
                 DMPackCreateParamTS(P15,"Codec","String(256)","string");
                 DMPackCreateParam(P15,"SilenceSuppression",0);
                 DMPackCreateParam(P15,"PacketizationPeriod",2);
                 DMPackCreateParam(P15,"Overruns",2);
                 DMPackCreateParam(P15,"Underruns",2);
             P12=DMPackCreateObject(P11, 0,"VoiceQuality",0);
              DMPackCreateFunctions(P12,"TelcoVoiceMgrDml_CallLogList_SessionList_Dest_VoiceQuality",1,13);
              P13=DMPackCreatePNode(P12,"parameters");
               DMPackCreateParamTS(P13,"VoIPQualityIndicator","String(255)","string");
               DMPackCreateParamTS(P13,"WorstVoIPQualityIndicatorsValues","String(255)","string");
               DMPackCreateParamTS(P13,"WorstVoIPQualityIndicatorTimestamps","String(255)","string");
       P6=DMPackCreateObject(P5, 2,"VoIPProfile","128");
        DMPackCreateFunctions(P6,"TelcoVoiceMgrDml_VoipProfileList",13,5,6,0,2,12,17,13,18,10,15,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"Enable",0,1);
         DMPackCreateW(P7,"QuiescentMode",0,1);
         DMPackCreateParamTSW(P7,"Name","String(64)","string",1);
         DMPackCreateParamTSW(P7,"Alias","string(64)","string",1);
         DMPackCreateParamTSW(P7,"DTMFMethod","string: InBand(0),RFC4733(1),SIPInfo(2)","uint32/mapped",1);
         DMPackCreateParamTSW(P7,"DTMFMethodG711","string: InBand(0),RFC4733(1),SIPInfo(2),NULL(3)","uint32/mapped",1);
         DMPackCreateParamTSW(P7,"QIModelUsed","String(128)","string",1);
         DMPackCreateW(P7,"QICalculationInterval",2,1);
         DMPackCreateW(P7,"NumberOfWorstQIValues",2,1);
         DMPackCreateParamTSW(P7,"X_RDK-Central_COM_DigitMap","string(2048)","string",1);
         DMPackCreateParamTSW(P7,"X_RDK-Central_COM_EmergencyDigitMap","string(2048)","string",1);
         DMPackCreateW(P7,"X_RDK-Central_COM_SDigitTimer",2,1);
         DMPackCreateW(P7,"X_RDK-Central_COM_ZDigitTimer",2,1);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 0,"RTP",0);
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_VoipProfileList_RTP",5,12,17,13,11,16);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"LocalPortMin",2,1);
           DMPackCreateW(P9,"LocalPortMax",2,1);
           DMPackCreateW(P9,"Gmin",2,1);
           DMPackCreateW(P9,"DSCPMark",2,1);
           DMPackCreateW(P9,"VLANIDMark",1,1);
           DMPackCreateW(P9,"EthernetPriorityMark",1,1);
           DMPackCreateW(P9,"TelephoneEventPayloadType",2,1);
           DMPackCreateParamTSW(P9,"JitterBufferType","string: Static(0),Dynamic(1)","uint32/mapped",1);
           DMPackCreateW(P9,"JitterBufferMaxSize",2,1);
           DMPackCreateW(P9,"JitterBufferMinSize",2,1);
           DMPackCreateW(P9,"JitterBufferActualSize",2,1);
           DMPackCreateParam(P9,"X_RDK_SKBMark",2);
          P9=DMPackCreatePNode(P8,"objects");
           P10=DMPackCreateObject(P9, 0,"RTCP",0);
            DMPackCreateFunctions(P10,"TelcoVoiceMgrDml_VoipProfileList_RTP_RTCP",6,12,17,13,18,10,15);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateW(P11,"Enable",0,1);
             DMPackCreateW(P11,"TxRepeatInterval",2,1);
             DMPackCreateParamTSW(P11,"LocalCName","String(64)","string",1);
           P10=DMPackCreateObject(P9, 0,"SRTP",0);
            DMPackCreateFunctions(P10,"TelcoVoiceMgrDml_VoipProfileList_RTP_SRTP",6,12,17,13,18,10,15);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateW(P11,"Enable",0,1);
             DMPackCreateParamTSW(P11,"KeyingMethods","string: Null(0),Static(1),SDP(2),IKE(3)","uint32/mapped",1);
             DMPackCreateParamTSW(P11,"EncryptionKeySizes","String(255)","string",1);
           P10=DMPackCreateObject(P9, 0,"Redundancy",0);
            DMPackCreateFunctions(P10,"TelcoVoiceMgrDml_VoipProfileList_RTP_Redundancy",6,12,17,11,16,10,15);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateW(P11,"Enable",0,1);
             DMPackCreateW(P11,"PayloadType",2,1);
             DMPackCreateParam(P11,"BlockPayloadType",2);
             DMPackCreateW(P11,"FaxAndModemRedundancy",1,1);
             DMPackCreateW(P11,"ModemRedundancy",1,1);
             DMPackCreateW(P11,"DTMFRedundancy",1,1);
             DMPackCreateW(P11,"VoiceRedundancy",1,1);
             DMPackCreateW(P11,"MaxSessionsUsingRedundancy",2,1);
         P8=DMPackCreateObject(P7, 0,"FaxT38",0);
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_VoipProfileList_FaxT38",2,12,17);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"MaxBitRate",2,1);
           DMPackCreateW(P9,"HighSpeedRedundancy",2,1);
           DMPackCreateW(P9,"LowSpeedRedundancy",2,1);
           DMPackCreateParamTSW(P9,"TCFMethod","string: Local(0),Network(1)","uint32/mapped",1);
       P6=DMPackCreateObject(P5, 2,"CodecProfile","128");
        DMPackCreateFunctions(P6,"TelcoVoiceMgrDml_CodecProfileList",11,5,6,0,2,13,18,10,15,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"Enable",0,1);
         DMPackCreateParamTSW(P7,"Alias","string(64)","string",1);
         DMPackCreateParamTS(P7,"Codec","String(256)","string");
         DMPackCreateParamTSW(P7,"PacketizationPeriod","String(255)","string",1);
         DMPackCreateW(P7,"SilenceSuppression",0,1);
       P6=DMPackCreateObject(P5, 0,"Tone",0);
        DMPackCreateFunctions(P6,"TelcoVoiceMgrDml_Tone",2,13,18);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateParamTSW(P7,"DefautEventProfile","String(256)","string",1);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 2,"Description","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_Tone_DescList",13,5,6,0,2,12,17,13,18,10,15,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"ToneEnable",0,1);
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateParamTSW(P9,"ToneName","String(64)","string",1);
           DMPackCreateParamTSW(P9,"TonePattern","String(256)","string",1);
           DMPackCreateParamTSW(P9,"ToneFile","String(256)","string",1);
           DMPackCreateW(P9,"ToneRepetitions",2,1);
           DMPackCreateParamTSW(P9,"ToneText","String(64)","string",1);
         P8=DMPackCreateObject(P7, 2,"Pattern","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_Tone_PatternList",15,5,6,0,2,12,17,13,18,11,16,10,15,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateW(P9,"ToneOn",0,1);
           DMPackCreateW(P9,"Frequency1",2,1);
           DMPackCreateW(P9,"Power1",1,1);
           DMPackCreateW(P9,"Frequency2",2,1);
           DMPackCreateW(P9,"Power2",1,1);
           DMPackCreateW(P9,"Frequency3",2,1);
           DMPackCreateW(P9,"Power3",1,1);
           DMPackCreateW(P9,"Frequency4",2,1);
           DMPackCreateW(P9,"Power4",1,1);
           DMPackCreateW(P9,"ModulationFrequency",2,1);
           DMPackCreateW(P9,"ModulationPower",1,1);
           DMPackCreateW(P9,"Duration",2,1);
           DMPackCreateParamTSW(P9,"NextPattern","String(256)","string",1);
         P8=DMPackCreateObject(P7, 2,"EventProfile","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_Tone_EventProfileList",9,5,6,0,2,13,18,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
          P9=DMPackCreatePNode(P8,"objects");
           P10=DMPackCreateObject(P9, 2,"Event","128");
            DMPackCreateFunctions(P10,"TelcoVoiceMgrDml_Tone_EventProfileList_EvtList",9,5,6,0,2,13,18,20,21,22);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateParamTSW(P11,"Alias","string(64)","string",1);
             DMPackCreateParamTSW(P11,"Function","String(255)","string",1);
             DMPackCreateParamTSW(P11,"Tone","String(256)","string",1);
       P6=DMPackCreateObject(P5, 2,"Terminal","128");
        DMPackCreateFunctions(P6,"TelcoVoiceMgrDml_TerminalList",12,5,6,0,2,12,13,18,10,15,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"Enable",0,1);
         DMPackCreateW(P7,"QuiescentMode",0,1);
         DMPackCreateParamTS(P7,"Status","string: Up(0),Initializing(1),Registering(2),Unregistering(3),Error(4),Testing(5),Quiescent(6),Disabled(7)","uint32/mapped");
         DMPackCreateParamTSW(P7,"Alias","string(64)","string",1);
         DMPackCreateParamTSW(P7,"ToneEventProfile","String(256)","string",1);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 2,"Audio","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_TerminalList_AudioList",9,5,6,0,2,13,18,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateParamTSW(P9,"Name","String(256)","string",1);
          P9=DMPackCreatePNode(P8,"objects");
           P10=DMPackCreateObject(P9, 0,"VoiceProcessing",0);
            DMPackCreateFunctions(P10,"TelcoVoiceMgrDml_TerminalList_AudioList_VoiceProcessing",5,12,11,16,10,15);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateW(P11,"TransmitGain",1,1);
             DMPackCreateW(P11,"ReceiveGain",1,1);
             DMPackCreateW(P11,"EchoCancellationEnable",0,1);
             DMPackCreateParam(P11,"EchoCancellationInUse",0);
             DMPackCreateParam(P11,"EchoCancellationTail",2);
         P8=DMPackCreateObject(P7, 0,"ButtonMap",0);
          P9=DMPackCreatePNode(P8,"objects");
           P10=DMPackCreateObject(P9, 2,"Button","128");
            DMPackCreateFunctions(P10,"TelcoVoiceMgrDml_TerminalList_ButtonMap_ButtonList",11,5,6,0,2,13,18,10,15,20,21,22);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateParamTSW(P11,"Alias","string(64)","string",1);
             DMPackCreateParamTS(P11,"ButtonName","String(16)","string");
             DMPackCreateParamTSW(P11,"FacilityAction","String(64)","string",1);
             DMPackCreateParamTSW(P11,"FacilityActionArgument","String(256)","string",1);
             DMPackCreateParamTSW(P11,"QuickDialNumber","String(40)","string",1);
             DMPackCreateParamTSW(P11,"ButtonMessage","String(64)","string",1);
             DMPackCreateW(P11,"UserAccess",0,1);
         P8=DMPackCreateObject(P7, 0,"Ringer",0);
          P9=DMPackCreatePNode(P8,"objects");
           P10=DMPackCreateObject(P9, 2,"Description","128");
            DMPackCreateFunctions(P10,"TelcoVoiceMgrDml_TerminalList_Ringer_DescList",11,5,6,0,2,13,18,10,15,20,21,22);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateW(P11,"RingEnable",0,1);
             DMPackCreateParamTSW(P11,"Alias","string(64)","string",1);
             DMPackCreateParamTSW(P11,"RingName","String(64)","string",1);
             DMPackCreateParamTSW(P11,"RingPattern","String(256)","string",1);
             DMPackCreateParamTSW(P11,"RingFile","String(256)","string",1);
           P10=DMPackCreateObject(P9, 2,"Pattern","128");
            DMPackCreateFunctions(P10,"TelcoVoiceMgrDml_TerminalList_Ringer_PatternList",13,5,6,0,2,12,17,13,18,10,15,20,21,22);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateW(P11,"Enable",0,1);
             DMPackCreateParamTSW(P11,"Alias","string(64)","string",1);
             DMPackCreateW(P11,"RingerOn",0,1);
             DMPackCreateW(P11,"Duration",2,1);
             DMPackCreateParamTSW(P11,"NextPattern","String(256)","string",1);
         P8=DMPackCreateObject(P7, 0,"DiagTests",0);
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_TerminalList_DiagTests",5,13,18,10,12,17);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateParamTSW(P9,"DiagnosticsState","string: None(0),Requested(1),Complete(2),Error_Internal(3),Error_Other(4)","uint32/mapped",1);
           DMPackCreateParamTSW(P9,"TestSelector","String(255)","string",1);
           DMPackCreateParam(P9,"PhoneRinging",0);
           DMPackCreateParamTS(P9,"X_RDK_TestResult","string(64)","string");
       P6=DMPackCreateObject(P5, 0,"ClockSynchronization",0);
        DMPackCreateFunctions(P6,"TelcoVoiceMgrDml_ClkSync",4,13,18,10,15);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateParamTSW(P7,"CurrentSource","String(256)","string",1);
         DMPackCreateParamTS(P7,"Description","String(64)","string");
         DMPackCreateW(P7,"AutoRevert",0,1);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 2,"ClockSource","128");
          DMPackCreateFunctions(P8,"TelcoVoiceMgrDml_ClkSync_ClkSourceList",13,5,6,0,2,12,17,13,18,10,15,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateW(P9,"Order",2,1);
           DMPackCreateParamTSW(P9,"Interface","String(256)","string",1);
 return P0;
}
