/*
DM PACK
created with:
python /workspace/home/himal.d/MatterProtocol/build-raspberrypi4-64-rdk-broadband/tmp/work/cortexa72-rdk-linux/ccsp-mta-agent/rdkb-2024q3-kirkstone+git999-r0/recipe-sysroot-native/usr/bin/dm_pack_code_gen.py /workspace/home/himal.d/MatterProtocol/meta-cmf/../rdkb/components/opensource/ccsp/CcspMtaAgent/config/CcspMtaAgent.xml /workspace/home/himal.d/MatterProtocol/meta-cmf/../rdkb/components/opensource/ccsp/CcspMtaAgent/source/MtaAgentSsp/dm_pack_datamodel.c
*/

#include "ansc_platform.h"
#include "ansc_xml_dom_parser_interface.h"
#include "dm_pack_xml_helper.h"
PVOID DMPackCreateDataModelXML(){
 PANSC_XML_DOM_NODE_OBJECT P0,P1,P2,P3,P4,P5,P6,P7,P8,P9;
 P0=DMPackCreatePNode(0,"dataModelInfo");
  P1=DMPackCreateNode(P0,"version","1",1);
  P1=DMPackCreateNode(P0,"moduleName","CCSP MTA Agent",14);
  P1=DMPackCreateNode(P0,"author","Ruiqi Tian",10);
  P1=DMPackCreatePNode(P0,"description");
  P1=DMPackCreatePNode(P0,"library");
   P2=DMPackCreateNode(P1,"path","libmta_tr181",12);
   P2=DMPackCreateNode(P1,"func_Init","COSA_Init",9);
   P2=DMPackCreateNode(P1,"func_Async_Init","COSA_Async_Init",15);
   P2=DMPackCreateNode(P1,"func_Unload","COSA_Unload",11);
   P2=DMPackCreateNode(P1,"func_MemoryCheck","COSA_MemoryCheck",16);
   P2=DMPackCreateNode(P1,"func_MemoryUsage","COSA_MemoryUsage",16);
   P2=DMPackCreateNode(P1,"func_MemoryTable","COSA_MemoryTable",16);
  P1=DMPackCreatePNode(P0,"objects");
   P2=DMPackCreateObject(P1, 0,"X_CISCO_COM_MTA_V6",0);
    DMPackCreateFunctions(P2,"X_CISCO_COM_MTA_V6",5,12,13,20,21,22);
    P3=DMPackCreatePNode(P2,"parameters");
     DMPackCreateParam(P3,"PrimaryDHCPv6Server",3);
     DMPackCreateParam(P3,"SecondaryDHCPv6Server",3);
     DMPackCreateParam(P3,"IPV6Address",3);
     DMPackCreateParam(P3,"Prefix",3);
     DMPackCreateParamTS(P3,"BootFileName","string(64)","string");
     DMPackCreateParamTS(P3,"FQDN","string(64)","string");
     DMPackCreateParam(P3,"Gateway",3);
     DMPackCreateParam(P3,"LeaseTimeRemaining",2);
     DMPackCreateParamTS(P3,"RebindTimeRemaining","string(64)","string");
     DMPackCreateParamTS(P3,"RenewTimeRemaining","string(64)","string");
     DMPackCreateParam(P3,"PrimaryDNS",3);
     DMPackCreateParam(P3,"SecondaryDNS",3);
     DMPackCreateParamTS(P3,"DHCPOption3","string(64)","string");
     DMPackCreateParamTS(P3,"DHCPOption6","string(64)","string");
     DMPackCreateParamTS(P3,"DHCPOption7","string(64)","string");
     DMPackCreateParamTS(P3,"DHCPOption8","string(64)","string");
     DMPackCreateParamTS(P3,"PCVersion","string(64)","string");
     DMPackCreateParamTS(P3,"MACAddress","string(64)","string");
   P2=DMPackCreateObject(P1, 0,"X_CISCO_COM_MTA",0);
    DMPackCreateFunctions(P2,"X_CISCO_COM_MTA",11,10,11,12,13,15,16,17,18,20,21,22);
    P3=DMPackCreatePNode(P2,"parameters");
     DMPackCreateParamS(P3,"PrimaryDHCPServer",3,"uint32/ip4_addr");
     DMPackCreateParamS(P3,"SecondaryDHCPServer",3,"uint32/ip4_addr");
     DMPackCreateW(P3,"pktcMtaDevEnabled",0,1);
     DMPackCreateW(P3,"DSXLogEnable",0,1);
     DMPackCreateW(P3,"ClearDSXLog",0,1);
     DMPackCreateW(P3,"CallSignallingLogEnable",0,1);
     DMPackCreateW(P3,"ClearCallSignallingLog",0,1);
     DMPackCreateW(P3,"EnableDECTLog",0,1);
     DMPackCreateW(P3,"EnableMTALog",0,1);
     DMPackCreateW(P3,"pktcSigDefCallSigTos",2,1);
     DMPackCreateW(P3,"pktcSigDefMediaStreamTos",2,1);
     DMPackCreateParam(P3,"pktcMtaDevRealmOrgName",2);
     DMPackCreateParam(P3,"pktcMtaDevCmsKerbRealmName",2);
     DMPackCreateParam(P3,"pktcMtaDevCmsIpsecCtrl",2);
     DMPackCreateParam(P3,"pktcMtaDevCmsSolicitedKeyTimeout",2);
     DMPackCreateParam(P3,"pktcMtaDevRealmPkinitGracePeriod",2);
     DMPackCreateParamS(P3,"IPAddress",3,"uint32/ip4_addr");
     DMPackCreateParamTS(P3,"BootFileName","string(64)","string");
     DMPackCreateParamTS(P3,"FQDN","string(64)","string");
     DMPackCreateParamS(P3,"SubnetMask",3,"uint32/ip4_addr");
     DMPackCreateParamS(P3,"Gateway",3,"uint32/ip4_addr");
     DMPackCreateParam(P3,"LeaseTimeRemaining",2);
     DMPackCreateParamTS(P3,"RebindTimeRemaining","string(64)","string");
     DMPackCreateParamTS(P3,"RenewTimeRemaining","string(64)","string");
     DMPackCreateParamS(P3,"PrimaryDNS",3,"uint32/ip4_addr");
     DMPackCreateParamS(P3,"SecondaryDNS",3,"uint32/ip4_addr");
     DMPackCreateParamTS(P3,"DHCPOption3","string(64)","string");
     DMPackCreateParamTS(P3,"DHCPOption6","string(64)","string");
     DMPackCreateParamTS(P3,"DHCPOption7","string(64)","string");
     DMPackCreateParamTS(P3,"DHCPOption8","string(64)","string");
     DMPackCreateParamTS(P3,"PCVersion","string(64)","string");
     DMPackCreateParamTS(P3,"MACAddress","string(64)","string");
     DMPackCreateParam(P3,"LineTableNumberOfEntries",2);
     DMPackCreateParam(P3,"ServiceFlowNumberOfEntries",2);
     DMPackCreateParam(P3,"DSXLogNumberOfEntries",2);
     DMPackCreateParam(P3,"MTAResetCount",2);
     DMPackCreateParam(P3,"LineResetCount",2);
     DMPackCreateW(P3,"ClearLineStats",2,1);
    P3=DMPackCreatePNode(P2,"objects");
     P4=DMPackCreateObject(P3, 2,"DSXLog","128");
      DMPackCreateFunctions(P4,"DSXLog",6,0,2,5,6,12,13);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParam(P5,"ID",2);
       DMPackCreateParamTS(P5,"Time","string(64)","string");
       DMPackCreateParamTS(P5,"Description","string(128)","string");
       DMPackCreateParam(P5,"Level",2);
     P4=DMPackCreateObject(P3, 1,"LineTable","128");
      DMPackCreateFunctions(P4,"LineTable",13,0,2,10,11,12,13,15,16,17,18,20,21,22);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParam(P5,"LineNumber",2);
       DMPackCreateParamTS(P5,"Status","string: On-Hook(1),Off-Hook(2)","uint32/mapped");
       DMPackCreateParamTS(P5,"HazardousPotential","string(64)","string");
       DMPackCreateParamTS(P5,"ForeignEMF","string(64)","string");
       DMPackCreateParamTS(P5,"ResistiveFaults","string(64)","string");
       DMPackCreateParamTS(P5,"ReceiverOffHook","string(64)","string");
       DMPackCreateParamTS(P5,"RingerEquivalency","string(64)","string");
       DMPackCreateW(P5,"TriggerDiagnostics",0,1);
       DMPackCreateParamTS(P5,"CAName","string(64)","string");
       DMPackCreateParam(P5,"CAPort",2);
       DMPackCreateParam(P5,"MWD",2);
       DMPackCreateParamTS(P5,"OverCurrentFault","string: Normal(1),Fault(2)","uint32/mapped");
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 0,"CALLP",0);
        DMPackCreateFunctions(P6,"CALLP",1,13);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateParamTS(P7,"LCState","string(64)","string");
         DMPackCreateParamTS(P7,"CallPState","string(64)","string");
         DMPackCreateParamTS(P7,"LoopCurrent","string(64)","string");
       P6=DMPackCreateObject(P5, 0,"VQM",0);
        DMPackCreateFunctions(P6,"VQM",5,10,15,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"ResetStats",0,1);
         DMPackCreateParam(P7,"CallsNumberOfEntries",2);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 2,"Calls","128");
          DMPackCreateFunctions(P8,"Calls",8,0,2,5,6,10,11,12,13);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateParamTS(P9,"Codec","string(64)","string");
           DMPackCreateParamTS(P9,"RemoteCodec","string(64)","string");
           DMPackCreateParamTS(P9,"CallEndTime","string(64)","string");
           DMPackCreateParamTS(P9,"CallStartTime","string(64)","string");
           DMPackCreateParamTS(P9,"CWErrorRate","string(16)","string");
           DMPackCreateParamTS(P9,"PktLossConcealment","string(16)","string");
           DMPackCreateParam(P9,"JitterBufferAdaptive",0);
           DMPackCreateParam(P9,"Originator",0);
           DMPackCreateParamS(P9,"RemoteIPAddress",3,"uint32/ip4_addr");
           DMPackCreateParam(P9,"CallDuration",2);
           DMPackCreateParamTS(P9,"CWErrors","string(16)","string");
           DMPackCreateParamTS(P9,"SNR","string(16)","string");
           DMPackCreateParamTS(P9,"MicroReflections","string(16)","string");
           DMPackCreateParamTS(P9,"DownstreamPower","string(16)","string");
           DMPackCreateParamTS(P9,"UpstreamPower","string(16)","string");
           DMPackCreateParamTS(P9,"EQIAverage","string(16)","string");
           DMPackCreateParamTS(P9,"EQIMinimum","string(16)","string");
           DMPackCreateParamTS(P9,"EQIMaximum","string(16)","string");
           DMPackCreateParamTS(P9,"EQIInstantaneous","string(16)","string");
           DMPackCreateParamTS(P9,"MOS-LQ","string(16)","string");
           DMPackCreateParamTS(P9,"MOS-CQ","string(16)","string");
           DMPackCreateParamTS(P9,"EchoReturnLoss","string(16)","string");
           DMPackCreateParamTS(P9,"SignalLevel","string(16)","string");
           DMPackCreateParamTS(P9,"NoiseLevel","string(16)","string");
           DMPackCreateParamTS(P9,"LossRate","string(16)","string");
           DMPackCreateParamTS(P9,"DiscardRate","string(16)","string");
           DMPackCreateParamTS(P9,"BurstDensity","string(16)","string");
           DMPackCreateParamTS(P9,"GapDensity","string(16)","string");
           DMPackCreateParamTS(P9,"BurstDuration","string(16)","string");
           DMPackCreateParamTS(P9,"GapDuration","string(16)","string");
           DMPackCreateParamTS(P9,"RoundTripDelay","string(16)","string");
           DMPackCreateParamTS(P9,"Gmin","string(16)","string");
           DMPackCreateParamTS(P9,"RFactor","string(16)","string");
           DMPackCreateParamTS(P9,"ExternalRFactor","string(16)","string");
           DMPackCreateParamTS(P9,"JitterBufRate","string(16)","string");
           DMPackCreateParamTS(P9,"JBNominalDelay","string(16)","string");
           DMPackCreateParamTS(P9,"JBMaxDelay","string(16)","string");
           DMPackCreateParamTS(P9,"JBAbsMaxDelay","string(16)","string");
           DMPackCreateParamTS(P9,"RemoteMOS-LQ","string(16)","string");
           DMPackCreateParamTS(P9,"RemoteMOS-CQ","string(16)","string");
           DMPackCreateParamTS(P9,"RemoteEchoReturnLoss","string(16)","string");
           DMPackCreateParamTS(P9,"RemoteSignalLevel","string(16)","string");
           DMPackCreateParamTS(P9,"RemoteNoiseLevel","string(16)","string");
           DMPackCreateParamTS(P9,"RemoteLossRate","string(16)","string");
           DMPackCreateParamTS(P9,"RemotePktLossConcealment","string(16)","string");
           DMPackCreateParamTS(P9,"RemoteDiscardRate","string(16)","string");
           DMPackCreateParamTS(P9,"RemoteBurstDensity","string(16)","string");
           DMPackCreateParamTS(P9,"RemoteGapDensity","string(16)","string");
           DMPackCreateParamTS(P9,"RemoteBurstDuration","string(16)","string");
           DMPackCreateParamTS(P9,"RemoteGapDuration","string(16)","string");
           DMPackCreateParamTS(P9,"RemoteRoundTripDelay","string(16)","string");
           DMPackCreateParamTS(P9,"RemoteGmin","string(16)","string");
           DMPackCreateParamTS(P9,"RemoteRFactor","string(16)","string");
           DMPackCreateParamTS(P9,"RemoteExternalRFactor","string(16)","string");
           DMPackCreateParam(P9,"RemoteJitterBufferAdaptive",0);
           DMPackCreateParamTS(P9,"RemoteJitterBufRate","string(16)","string");
           DMPackCreateParamTS(P9,"RemoteJBNominalDelay","string(16)","string");
           DMPackCreateParamTS(P9,"RemoteJBMaxDelay","string(16)","string");
           DMPackCreateParamTS(P9,"RemoteJBAbsMaxDelay","string(16)","string");
           DMPackCreateParamTS(P9,"TxPackets","string(16)","string");
           DMPackCreateParamTS(P9,"TxOctets","string(16)","string");
           DMPackCreateParamTS(P9,"RxPackets","string(16)","string");
           DMPackCreateParamTS(P9,"RxOctets","string(16)","string");
           DMPackCreateParamTS(P9,"PacketLoss","string(16)","string");
           DMPackCreateParamTS(P9,"IntervalJitter","string(16)","string");
           DMPackCreateParamTS(P9,"RemoteIntervalJitter","string(16)","string");
     P4=DMPackCreateObject(P3, 2,"ServiceClass","128");
      DMPackCreateFunctions(P4,"ServiceClass",5,0,2,5,6,13);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParamTS(P5,"ServiceClassName","string(64)","string");
     P4=DMPackCreateObject(P3, 2,"ServiceFlow","128");
      DMPackCreateFunctions(P4,"ServiceFlow",7,0,2,5,6,12,13,10);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParam(P5,"SFID",2);
       DMPackCreateParamTS(P5,"ServiceClassName","string(256)","string");
       DMPackCreateParamTS(P5,"Direction","string(16)","string");
       DMPackCreateParam(P5,"ScheduleType",2);
       DMPackCreateParam(P5,"DefaultFlow",0);
       DMPackCreateParam(P5,"NomGrantInterval",2);
       DMPackCreateParam(P5,"UnsolicitGrantSize",2);
       DMPackCreateParam(P5,"TolGrantJitter",2);
       DMPackCreateParam(P5,"NomPollInterval",2);
       DMPackCreateParam(P5,"MinReservedPkt",2);
       DMPackCreateParam(P5,"MaxTrafficRate",2);
       DMPackCreateParam(P5,"MinReservedRate",2);
       DMPackCreateParam(P5,"MaxTrafficBurst",2);
       DMPackCreateParamTS(P5,"TrafficType","string(64)","string");
       DMPackCreateParam(P5,"NumberOfPackets",2);
     P4=DMPackCreateObject(P3, 0,"Dect","128");
      DMPackCreateFunctions(P4,"Dect",10,10,11,12,13,15,17,18,20,21,22);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParamTS(P5,"HardwareVersion","string(64)","string");
       DMPackCreateParamTS(P5,"RFPI","string(64)","string");
       DMPackCreateParamTS(P5,"SoftwareVersion","string(64)","string");
       DMPackCreateW(P5,"RegistrationMode",0,1);
       DMPackCreateW(P5,"RegisterDectHandset",2,1);
       DMPackCreateW(P5,"DeregisterDectHandset",2,1);
       DMPackCreateW(P5,"Enable",0,1);
       DMPackCreateParamTSW(P5,"PIN","string(64)","string",1);
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 2,"Handsets","128");
        DMPackCreateFunctions(P6,"Handsets",15,0,2,5,6,10,11,12,13,15,16,17,18,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateParam(P7,"Status",0);
         DMPackCreateParamTS(P7,"LastActiveTime","string(64)","string");
         DMPackCreateParamTS(P7,"HandsetName","string(64)","string");
         DMPackCreateParamTSW(P7,"OperatingTN","string(64)","string",1);
         DMPackCreateParamTS(P7,"SupportedTN","string(64)","string");
         DMPackCreateParamTS(P7,"HandsetFirmware","string(64)","string");
     P4=DMPackCreateObject(P3, 2,"MTALog","128");
      DMPackCreateFunctions(P4,"MTALog",6,0,2,5,6,12,13);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParam(P5,"Time",3);
       DMPackCreateParam(P5,"Index",2);
       DMPackCreateParam(P5,"EventID",2);
       DMPackCreateParam(P5,"EventLevel",3);
       DMPackCreateParam(P5,"Description",3);
     P4=DMPackCreateObject(P3, 2,"DECTLog","128");
      DMPackCreateFunctions(P4,"DECTLog",6,0,2,5,6,12,13);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParam(P5,"Time",3);
       DMPackCreateParam(P5,"Index",2);
       DMPackCreateParam(P5,"EventID",2);
       DMPackCreateParam(P5,"EventLevel",2);
       DMPackCreateParam(P5,"Description",3);
     P4=DMPackCreateObject(P3, 0,"Battery",0);
      DMPackCreateFunctions(P4,"Battery",4,10,11,12,13);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParam(P5,"Installed",0);
       DMPackCreateParamTS(P5,"PowerStatus","string(16)","string");
       DMPackCreateParamTS(P5,"Condition","string(16)","string");
       DMPackCreateParamTS(P5,"Status","string(16)","string");
       DMPackCreateParamTS(P5,"Life","string(32)","string");
       DMPackCreateParam(P5,"TotalCapacity",2);
       DMPackCreateParam(P5,"ActualCapacity",2);
       DMPackCreateParam(P5,"RemainingCharge",2);
       DMPackCreateParam(P5,"RemainingTime",2);
       DMPackCreateParam(P5,"NumberofCycles",2);
       DMPackCreateParamTS(P5,"ModelNumber","string(32)","string");
       DMPackCreateParamTS(P5,"SerialNumber","string(32)","string");
       DMPackCreateParamTS(P5,"PartNumber","string(32)","string");
       DMPackCreateParamTS(P5,"ChargerFirmwareRevision","string(32)","string");
   P2=DMPackCreateObject(P1, 0,"VoiceService",0);
    DMPackCreateFunctions(P2,"VoiceService",2,18,13);
    P3=DMPackCreatePNode(P2,"parameters");
     DMPackCreateW(P3,"Data",3,1);
   P2=DMPackCreateObject(P1, 0,"X_RDKCENTRAL-COM_MTA",0);
    DMPackCreateFunctions(P2,"X_RDKCENTRAL_COM_MTA",4,12,13,10,15);
    P3=DMPackCreatePNode(P2,"parameters");
     DMPackCreateW(P3,"pktcMtaDevResetNow",0,1);
     DMPackCreateParamTS(P3,"Ipv4DhcpStatus","string: Init(0),Start(1),Complete(2),Error(3)","uint32/mapped");
     DMPackCreateParamTS(P3,"Ipv6DhcpStatus","string: Init(0),Start(1),Complete(2),Error(3)","uint32/mapped");
     DMPackCreateParamTS(P3,"ConfigFileStatus","string: Init(0),Start(1),Complete(2),Error(3)","uint32/mapped");
     DMPackCreateParam(P3,"LineRegisterStatus",3);
   P2=DMPackCreateObject(P1, 0,"X_RDKCENTRAL-COM_EthernetWAN_MTA",0);
    DMPackCreateFunctions(P2,"EthernetWAN_MTA",4,11,16,13,18);
    P3=DMPackCreatePNode(P2,"parameters");
     DMPackCreateW(P3,"StartupIPMode",1,1);
     DMPackCreateW(P3,"IPv4PrimaryDhcpServerOptions",3,1);
     DMPackCreateW(P3,"IPv4SecondaryDhcpServerOptions",3,1);
     DMPackCreateW(P3,"IPv6PrimaryDhcpServerOptions",3,1);
     DMPackCreateW(P3,"IPv6SecondaryDhcpServerOptions",3,1);
 return P0;
}
