/*
DM PACK
created with:
python /workspace/home/himal.d/MatterProtocol/build-raspberrypi4-64-rdk-broadband/tmp/work/cortexa72-rdk-linux/ccsp-adv-security/rdkb-2024q3-kirkstone+git999-r0/recipe-sysroot-native/usr/bin/dm_pack_code_gen.py /workspace/home/himal.d/MatterProtocol/meta-cmf/../rdkb/components/opensource/ccsp/CcspAdvSecurity/config/TR181-AdvSecurity.xml /workspace/home/himal.d/MatterProtocol/meta-cmf/../rdkb/components/opensource/ccsp/CcspAdvSecurity/source/AdvSecuritySsp/dm_pack_datamodel.c
*/

#include "ansc_platform.h"
#include "ansc_xml_dom_parser_interface.h"
#include "dm_pack_xml_helper.h"
PVOID DMPackCreateDataModelXML(){
 PANSC_XML_DOM_NODE_OBJECT P0,P1,P2,P3,P4,P5,P6,P7,P8,P9;
 P0=DMPackCreatePNode(0,"dataModelInfo");
  P1=DMPackCreateNode(P0,"version","1",1);
  P1=DMPackCreateNode(P0,"moduleName","RDKCENTRAL_AdvSecurity",22);
  P1=DMPackCreatePNode(P0,"author");
  P1=DMPackCreateNode(P0,"description","Advanced Security component",27);
  P1=DMPackCreatePNode(P0,"library");
   P2=DMPackCreateNode(P1,"path","libdmlasecurity",15);
   P2=DMPackCreateNode(P1,"func_Init","COSA_Init",9);
  P1=DMPackCreatePNode(P0,"objects");
   P2=DMPackCreateObject(P1, 0,"DeviceInfo",0);
    P3=DMPackCreatePNode(P2,"objects");
     P4=DMPackCreateObject(P3, 0,"X_RDKCENTRAL-COM_DeviceFingerPrint",0);
      DMPackCreateFunctions(P4,"DeviceFingerPrint",6,10,15,12,17,13,18);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"Enable",0,1);
       DMPackCreateW(P5,"LoggingPeriod",2,1);
       DMPackCreateW(P5,"EndpointURL",3,1);
       DMPackCreateW(P5,"LogLevel",2,1);
     P4=DMPackCreateObject(P3, 0,"X_RDKCENTRAL-COM_AdvancedSecurity",0);
      DMPackCreateFunctions(P4,"AdvancedSecurity",1,18);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"Data",3,1);
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 0,"SafeBrowsing",0);
        DMPackCreateFunctions(P6,"SafeBrowsing",8,10,15,12,17,13,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"Enable",0,1);
         DMPackCreateW(P7,"LookupTimeout",2,1);
         DMPackCreateW(P7,"LookupTimeoutExceededCount",2,0);
         DMPackCreateW(P7,"Threshold",2,0);
         DMPackCreateW(P7,"Timeout",2,0);
         DMPackCreateW(P7,"Cachettl",2,0);
         DMPackCreateW(P7,"Ttl",2,0);
         DMPackCreateW(P7,"WhitelistMaxEntries",2,0);
         DMPackCreateW(P7,"Endpoint",3,0);
         DMPackCreateW(P7,"Blockpage",3,0);
         DMPackCreateW(P7,"Warnpage",3,0);
         DMPackCreateW(P7,"Cacheurl",3,0);
         DMPackCreateW(P7,"OtmDedupFqdn",3,0);
       P6=DMPackCreateObject(P5, 0,"Softflowd",0);
        DMPackCreateFunctions(P6,"Softflowd",5,10,15,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"Enable",0,1);
     P4=DMPackCreateObject(P3, 0,"X_RDKCENTRAL-COM_AdvancedParentalControl",0);
      DMPackCreateFunctions(P4,"AdvancedParentalControl",2,10,15);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"Activate",0,1);
     P4=DMPackCreateObject(P3, 0,"X_RDKCENTRAL-COM_PrivacyProtection",0);
      DMPackCreateFunctions(P4,"PrivacyProtection",2,10,15);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"Activate",0,1);
     P4=DMPackCreateObject(P3, 0,"X_RDKCENTRAL-COM_RFC",0);
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 0,"Feature",0);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 0,"RabidFramework",0);
          DMPackCreateFunctions(P8,"RabidFramework",2,12,17);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"MemoryLimit",2,1);
           DMPackCreateW(P9,"MacCacheSize",2,1);
           DMPackCreateW(P9,"DNSCacheSize",2,1);
         P8=DMPackCreateObject(P7, 0,"AdvancedParentalControl",0);
          DMPackCreateFunctions(P8,"AdvancedParentalControl_RFC",2,10,15);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
         P8=DMPackCreateObject(P7, 0,"PrivacyProtection",0);
          DMPackCreateFunctions(P8,"PrivacyProtection_RFC",2,10,15);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
         P8=DMPackCreateObject(P7, 0,"DeviceFingerPrintICMPv6",0);
          DMPackCreateFunctions(P8,"DeviceFingerPrintICMPv6_RFC",2,10,15);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
         P8=DMPackCreateObject(P7, 0,"WS-Discovery_Analysis",0);
          DMPackCreateFunctions(P8,"WS_Discovery_Analysis_RFC",2,10,15);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
         P8=DMPackCreateObject(P7, 0,"AdvancedSecurityOTM",0);
          DMPackCreateFunctions(P8,"AdvancedSecurityOTM_RFC",2,10,15);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
         P8=DMPackCreateObject(P7, 0,"AdvanceSecurityUserSpace",0);
          DMPackCreateFunctions(P8,"AdvanceSecurityUserSpace_RFC",2,10,15);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
         P8=DMPackCreateObject(P7, 0,"AdvanceSecurityCujoTracer",0);
          DMPackCreateFunctions(P8,"AdvanceSecurityCujoTracer_RFC",2,10,15);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
         P8=DMPackCreateObject(P7, 0,"AdvanceSecurityCujoTelemetry",0);
          DMPackCreateFunctions(P8,"AdvanceSecurityCujoTelemetry_RFC",2,10,15);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
         P8=DMPackCreateObject(P7, 0,"WifiDataCollection",0);
          DMPackCreateFunctions(P8,"WifiDataCollection_RFC",2,10,15);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
         P8=DMPackCreateObject(P7, 0,"Levl",0);
          DMPackCreateFunctions(P8,"Levl_RFC",2,10,15);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
         P8=DMPackCreateObject(P7, 0,"AdvSecAgent",0);
          DMPackCreateFunctions(P8,"AdvSecAgent_RFC",2,10,15);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
         P8=DMPackCreateObject(P7, 0,"AdvSecSafeBrowsing",0);
          DMPackCreateFunctions(P8,"AdvSecSafeBrowsing_RFC",2,10,15);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
         P8=DMPackCreateObject(P7, 0,"AdvSecCujoTelemetryWiFiFP",0);
          DMPackCreateFunctions(P8,"AdvSecCujoTelemetryWiFiFP_RFC",2,10,15);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
         P8=DMPackCreateObject(P7, 0,"AdvSecAgentRaptr",0);
          DMPackCreateFunctions(P8,"AdvSecAgentRaptr_RFC",2,10,15);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
 return P0;
}
