/*
DM PACK
created with:
python /workspace/home/himal.d/MatterProtocol/build-raspberrypi4-64-rdk-broadband/tmp/work/cortexa72-rdk-linux/ccsp-one-wifi/rdkb-2024q3-kirkstone+git999-r0/recipe-sysroot-native/usr/bin/dm_pack_code_gen.py /workspace/home/himal.d/MatterProtocol/meta-cmf/../rdkb/components/opensource/ccsp/OneWifi/config/TR181-WiFi-USGv2.XML /workspace/home/himal.d/MatterProtocol/meta-cmf/../rdkb/components/opensource/ccsp/OneWifi/source/dml/wifi_ssp/dm_pack_datamodel.c
*/

#include "ansc_platform.h"
#include "ansc_xml_dom_parser_interface.h"
#include "dm_pack_xml_helper.h"
PVOID DMPackCreateDataModelXML(){
 PANSC_XML_DOM_NODE_OBJECT P0,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13;
 P0=DMPackCreatePNode(0,"dataModelInfo");
  P1=DMPackCreateNode(P0,"version","1",1);
  P1=DMPackCreateNode(P0,"moduleName","COSA_TR181_WiFi_USGv2",21);
  P1=DMPackCreatePNode(P0,"author");
  P1=DMPackCreateNode(P0,"description","COSA TR181 WiFi and extension for USGv2",39);
  P1=DMPackCreatePNode(P0,"library");
   P2=DMPackCreateNode(P1,"path","libwifi",7);
   P2=DMPackCreateNode(P1,"func_Init","COSA_Init",9);
   P2=DMPackCreateNode(P1,"func_Async_Init","COSA_Async_Init",15);
   P2=DMPackCreateNode(P1,"func_Unload","COSA_Unload",11);
   P2=DMPackCreateNode(P1,"func_MemoryCheck","COSA_MemoryCheck",16);
   P2=DMPackCreateNode(P1,"func_MemoryUsage","COSA_MemoryUsage",16);
   P2=DMPackCreateNode(P1,"func_MemoryTable","COSA_MemoryTable",16);
  P1=DMPackCreatePNode(P0,"objects");
   P2=DMPackCreateObject(P1, 0,"WiFi",0);
    DMPackCreateFunctions(P2,"WiFi",8,10,11,16,12,13,15,17,18);
    P3=DMPackCreatePNode(P2,"parameters");
     DMPackCreateParam(P3,"RadioNumberOfEntries",2);
     DMPackCreateParam(P3,"SSIDNumberOfEntries",2);
     DMPackCreateParam(P3,"AccessPointNumberOfEntries",2);
     DMPackCreateW(P3,"ApplyRadioSettings",0,1);
     DMPackCreateW(P3,"ApplyAccessPointSettings",0,1);
     DMPackCreateW(P3,"X_CISCO_COM_FactoryReset",0,1);
     DMPackCreateW(P3,"X_CISCO_COM_RadioPower",3,1);
     DMPackCreateW(P3,"X_CISCO_COM_EnableTelnet",0,1);
     DMPackCreateW(P3,"X_CISCO_COM_ResetRadios",0,1);
     DMPackCreateW(P3,"X_CISCO_COM_FactoryResetRadioAndAp",3,1);
     DMPackCreateW(P3,"X_RDK_VapData",3,1);
     DMPackCreateW(P3,"X_RDK_RadioData",3,1);
     DMPackCreateW(P3,"WiFiStuckDetect",0,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_WiFi_Notification",3,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_Connected-Client",3,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_WiFiHost_Sync",0,1);
     DMPackCreateW(P3,"2G80211axEnable",0,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_PreferPrivate",0,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_Br0_Sync",3,1);
     DMPackCreateParamTSW(P3,"X_RDKCENTRAL-COM_GoodRssiThreshold","int[-100:-30]","int",1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_RapidReconnectIndicationEnable",0,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_AssocCountThreshold",1,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_AssocMonitorDuration",1,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_AssocGateTime",1,1);
     DMPackCreateParamTSW(P3,"WHIX_LogInterval","int[300:3600]","int",1);
     DMPackCreateParamTSW(P3,"WHIX_ChUtility_LogInterval","int[5:3600]","int",1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_vAPStatsEnable",0,1);
     DMPackCreateW(P3,"FeatureMFPConfig",0,1);
     DMPackCreateW(P3,"TxOverflowSelfheal",0,1);
     DMPackCreateW(P3,"X_RDK-CENTRAL_COM_ForceDisable",0,1);
     DMPackCreateParamTSW(P3,"Status","string: Down(1),Up(2)","uint32/mapped",1);
     DMPackCreateW(P3,"Managed_WiFi_Enabled",0,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_GASConfiguration",3,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_EnableRadiusGreyList",0,1);
     DMPackCreateW(P3,"X_RDKCENTRAL-COM_EnableHostapdAuthenticator",0,1);
     DMPackCreateW(P3,"DFS",0,1);
     DMPackCreateW(P3,"Levl",0,1);
     DMPackCreateW(P3,"DFSatBootUp",0,1);
     DMPackCreateW(P3,"WiFi-Interworking",0,1);
     DMPackCreateW(P3,"WiFi-Passpoint",0,1);
     DMPackCreateW(P3,"WiFi-OffChannelScan",0,1);
     DMPackCreateW(P3,"WPA3_Personal_Transition",0,1);
     DMPackCreateW(P3,"Log_Enable",3,1);
     DMPackCreateW(P3,"Log_Upload",0,1);
    P3=DMPackCreatePNode(P2,"objects");
     P4=DMPackCreateObject(P3, 2,"X_RDKCENTRAL-COM_GASConfig","256");
      DMPackCreateFunctions(P4,"GASConfig",6,0,2,3,4,10,12);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"AdvertisementID",2,0);
       DMPackCreateW(P5,"PauseForServerResponse",0,0);
       DMPackCreateParamTSW(P5,"ResponseTimeout","unsignedInt[1000:65535]","uint32",0);
       DMPackCreateParamTSW(P5,"ComeBackDelay","unsignedInt[0:65535]","uint32",0);
       DMPackCreateParamTSW(P5,"ResponseBufferingTime","unsignedInt[0:65535]","uint32",0);
       DMPackCreateParamTSW(P5,"QueryResponseLengthLimit","unsignedInt[1:127]","uint32",0);
     P4=DMPackCreateObject(P3, 2,"X_RDKCENTRAL-COM_GASStats","256");
      DMPackCreateFunctions(P4,"GASStats",5,0,2,3,4,12);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"Queries",2,0);
       DMPackCreateW(P5,"QueryRate",2,0);
       DMPackCreateW(P5,"Responses",2,0);
       DMPackCreateW(P5,"ResponseRate",2,0);
       DMPackCreateW(P5,"NoRequestOutstanding",2,0);
       DMPackCreateW(P5,"ResponsesDiscarded",2,0);
       DMPackCreateW(P5,"FailedResponses",2,0);
     P4=DMPackCreateObject(P3, 0,"X_RDKCENTRAL-COM_Report",0);
      DMPackCreateFunctions(P4,"",0);
      P5=DMPackCreatePNode(P4,"parameters");
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 0,"WifiClient",0);
        DMPackCreateFunctions(P6,"WifiClient",9,10,12,13,15,17,18,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"Enabled",0,1);
         DMPackCreateW(P7,"ReportingPeriod",2,1);
         DMPackCreateW(P7,"MacAddress",3,1);
         DMPackCreateW(P7,"Schema",3,0);
         DMPackCreateW(P7,"SchemaID",3,0);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 0,"Default",0);
          DMPackCreateFunctions(P8,"WifiClient_Default",5,12,17,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"ReportingPeriod",2,1);
           DMPackCreateW(P9,"OverrideTTL",2,1);
         P8=DMPackCreateObject(P7, 0,"ActiveMeasurements",0);
          DMPackCreateFunctions(P8,"WifiClient_ActiveMeasurements",7,10,15,12,17,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
           DMPackCreateW(P9,"PacketSize",2,1);
           DMPackCreateW(P9,"SampleDuration",2,1);
           DMPackCreateW(P9,"NumberOfSamples",2,1);
          P9=DMPackCreatePNode(P8,"objects");
           P10=DMPackCreateObject(P9, 0,"Plan",0);
            DMPackCreateFunctions(P10,"ActiveMeasurements_Plan",5,13,18,20,21,22);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateW(P11,"PlanID",3,1);
            P11=DMPackCreatePNode(P10,"objects");
             P12=DMPackCreateObject(P11, 1,"Step","256");
              DMPackCreateFunctions(P12,"ActiveMeasurement_Step",9,0,2,12,17,13,18,20,21,22);
              P13=DMPackCreatePNode(P12,"parameters");
               DMPackCreateW(P13,"StepID",2,1);
               DMPackCreateW(P13,"SourceMac",3,1);
               DMPackCreateW(P13,"DestMac",3,1);
     P4=DMPackCreateObject(P3, 0,"X_RDKCENTRAL-COM_Syndication",0);
      DMPackCreateFunctions(P4,"",0);
      P5=DMPackCreatePNode(P4,"parameters");
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 0,"WiFiRegion",0);
        DMPackCreateFunctions(P6,"WiFiRegion",2,13,18);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"Code",3,1);
     P4=DMPackCreateObject(P3, 1,"Radio","128");
      DMPackCreateFunctions(P4,"Radio",13,0,2,10,11,12,13,15,16,17,18,20,21,22);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"Enable",0,1);
       DMPackCreateParamTSW(P5,"X_RDK_OffChannelTscan","unsignedInt[0:63]","uint32",1);
       DMPackCreateParamTSW(P5,"X_RDK_OffChannelNscan","unsignedInt[0:15]","uint32",1);
       DMPackCreateW(P5,"X_RDK_OffChannelNchannel",2,0);
       DMPackCreateParamTSW(P5,"X_RDK_OffChannelTidle","unsignedInt[0:63]","uint32",1);
       DMPackCreateParamTS(P5,"Status","string: Up(1),Down(2),Unknown(3),Dormant(4),NotPresent(5),LowerLayerDown(6),Error(7),DeepSleep(8)","uint32/mapped");
       DMPackCreateParamTSW(P5,"Alias","string(64)","string",1);
       DMPackCreateParamTS(P5,"Name","string(64)","string");
       DMPackCreateN(P5,"LastChange",2,0);
       DMPackCreateParamTSW(P5,"LowerLayers","string(1024)","string",1);
       DMPackCreateParam(P5,"Upstream",0);
       DMPackCreateParam(P5,"MaxBitRate",2);
       DMPackCreateParamTS(P5,"SupportedFrequencyBands","string: 2.4GHz(1),5GHz(2),5GHz Low(4),5GHz High(8),6GHz(16),60GHz(32)","uint32/mapped");
       DMPackCreateParam(P5,"OperatingFrequencyBand",3);
       DMPackCreateParam(P5,"SupportedStandards",3);
       DMPackCreateW(P5,"OperatingStandards",3,1);
       DMPackCreateParamTS(P5,"PossibleChannels","string(1024)","string");
       DMPackCreateParamTSN(P5,"ChannelsInUse","string(1024)","string",0);
       DMPackCreateParamTSN(P5,"X_CISCO_COM_ApChannelScan","string(16384)","string",0);
       DMPackCreateParamTSW(P5,"Channel","unsignedInt[1:255]","uint32",1);
       DMPackCreateParam(P5,"AutoChannelSupported",0);
       DMPackCreateW(P5,"AutoChannelEnable",0,1);
       DMPackCreateW(P5,"AutoChannelRefreshPeriod",2,1);
       DMPackCreateParamTSW(P5,"OperatingChannelBandwidth","string: Auto(0),20MHz(1),40MHz(2),80MHz(3),160MHz(4),80_80MHz(5),320MHz(6)","uint32/mapped",1);
       DMPackCreateParamTSW(P5,"ExtensionChannel","string: AboveControlChannel(1),BelowControlChannel(2),Auto(3)","uint32/mapped",1);
       DMPackCreateParamTSW(P5,"GuardInterval","string: 400nsec(1),800nsec(2),Auto(3),1600nsec(4),3200nsec(5)","uint32/mapped",1);
       DMPackCreateParamTSW(P5,"MCS","int[-1:15]","int",1);
       DMPackCreateParamTS(P5,"TransmitPowerSupported","string(64)","string");
       DMPackCreateParamTSW(P5,"TransmitPower","int[-1:100]","int",1);
       DMPackCreateParam(P5,"IEEE80211hSupported",0);
       DMPackCreateW(P5,"IEEE80211hEnabled",0,1);
       DMPackCreateParamTSW(P5,"RegulatoryDomain","string(3)","string",1);
       DMPackCreateW(P5,"X_CISCO_COM_RTSThreshold",2,1);
       DMPackCreateW(P5,"X_CISCO_COM_FragmentationThreshold",2,1);
       DMPackCreateW(P5,"X_CISCO_COM_DTIMInterval",2,1);
       DMPackCreateW(P5,"X_COMCAST-COM_BeaconInterval",2,1);
       DMPackCreateParamTSW(P5,"X_CISCO_COM_CTSProtectionMode","string: Disabled(0),Auto(1)","uint32/mapped",1);
       DMPackCreateParamTSW(P5,"X_CISCO_COM_TxRate","string: Auto(1),6000000(2),9000000(3),12000000(4),18000000(5),24000000(6),36000000(7),48000000(8),54000000(9)","uint32/mapped",1);
       DMPackCreateW(P5,"X_CISCO_COM_FrameBurst",0,1);
       DMPackCreateW(P5,"X_CISCO_COM_APIsolation",0,1);
       DMPackCreateParamTSW(P5,"X_CISCO_COM_BasicRate","string: Default(1),1-2Mbps(2),All(3)","uint32/mapped",1);
       DMPackCreateW(P5,"X_CISCO_COM_MbssUserControl",1,1);
       DMPackCreateW(P5,"X_CISCO_COM_AdminControl",1,1);
       DMPackCreateW(P5,"X_CISCO_COM_OnOffPushButtonTime",1,1);
       DMPackCreateW(P5,"X_CISCO_COM_ObssCoex",1,1);
       DMPackCreateW(P5,"X_CISCO_COM_MulticastRate",1,1);
       DMPackCreateW(P5,"X_CISCO_COM_ApplySetting",0,1);
       DMPackCreateW(P5,"X_RDKCENTRAL-COM_AutoChannelRefreshPeriodSupported",0,0);
       DMPackCreateW(P5,"X_RDKCENTRAL-COM_RtsThresholdSupported",0,0);
       DMPackCreateW(P5,"X_RDKCENTRAL-COM_ReverseDirectionGrantSupported",0,0);
       DMPackCreateW(P5,"X_CISCO_COM_ReverseDirectionGrant",0,1);
       DMPackCreateW(P5,"X_CISCO_COM_AggregationMSDU",0,1);
       DMPackCreateW(P5,"X_CISCO_COM_AutoBlockAck",0,1);
       DMPackCreateW(P5,"X_CISCO_COM_DeclineBARequest",0,1);
       DMPackCreateW(P5,"X_CISCO_COM_STBCEnable",0,1);
       DMPackCreateW(P5,"X_CISCO_COM_11nGreenfieldEnabled",0,1);
       DMPackCreateW(P5,"X_CISCO_COM_WirelessOnOffButton",0,1);
       DMPackCreateW(P5,"X_COMCAST_COM_DFSSupport",0,0);
       DMPackCreateW(P5,"X_COMCAST_COM_DFSEnable",0,1);
       DMPackCreateW(P5,"X_COMCAST-COM_DCSSupported",0,0);
       DMPackCreateW(P5,"X_COMCAST-COM_DCSEnable",0,1);
       DMPackCreateW(P5,"X_COMCAST_COM_RadioUpTime",2,0);
       DMPackCreateW(P5,"X_COMCAST_COM_IGMPSnoopingEnable",0,1);
       DMPackCreateW(P5,"X_COMCAST-COM_CarrierSenseThresholdRange",1,0);
       DMPackCreateW(P5,"X_COMCAST-COM_CarrierSenseThresholdInUse",1,1);
       DMPackCreateW(P5,"X_COMCAST-COM_ChannelSwitchingCount",1,0);
       DMPackCreateW(P5,"X_COMCAST-COM_AutoChannelRefreshPeriodSupported",0,0);
       DMPackCreateW(P5,"X_COMCAST-COM_IEEE80211hSupported",0,0);
       DMPackCreateW(P5,"X_COMCAST-COM_ReverseDirectionGrantSupported",0,0);
       DMPackCreateW(P5,"X_COMCAST-COM_RtsThresholdSupported",0,0);
       DMPackCreateW(P5,"X_RDKCENTRAL-COM_ChannelUtilThreshold",2,1);
       DMPackCreateW(P5,"X_RDKCENTRAL-COM_ChanUtilSelfHealEnable",2,1);
       DMPackCreateW(P5,"BeaconPeriod",2,1);
       DMPackCreateParamTSW(P5,"BasicDataTransmitRates","string(256)","string",1);
       DMPackCreateParamTSW(P5,"SupportedDataTransmitRates","string(256)","string",0);
       DMPackCreateParamTSW(P5,"OperationalDataTransmitRates","string(256)","string",1);
       DMPackCreateParam(P5,"RadioResetCount",2);
       DMPackCreateW(P5,"X_RDKCENTRAL-COM_clientInactivityTimeout",1,0);
       DMPackCreateW(P5,"X_RDK_EcoPowerDown",0,1);
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 0,"Stats",0);
        DMPackCreateFunctions(P6,"Stats3",11,5,6,10,15,11,16,12,13,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateN(P7,"BytesSent",2,0);
         DMPackCreateN(P7,"BytesReceived",2,0);
         DMPackCreateN(P7,"PacketsSent",2,0);
         DMPackCreateN(P7,"PacketsReceived",2,0);
         DMPackCreateN(P7,"ErrorsSent",2,0);
         DMPackCreateN(P7,"ErrorsReceived",2,0);
         DMPackCreateN(P7,"DiscardPacketsSent",2,0);
         DMPackCreateN(P7,"DiscardPacketsReceived",2,0);
         DMPackCreateN(P7,"PLCPErrorCount",2,0);
         DMPackCreateN(P7,"FCSErrorCount",2,0);
         DMPackCreateN(P7,"InvalidMACCount",2,0);
         DMPackCreateN(P7,"PacketsOtherReceived",2,0);
         DMPackCreateW(P7,"X_COMCAST-COM_NoiseFloor",1,0);
         DMPackCreateW(P7,"Noise",1,0);
         DMPackCreateN(P7,"X_COMCAST-COM_ChannelUtilization",2,0);
         DMPackCreateW(P7,"X_COMCAST-COM_ActivityFactor",1,0);
         DMPackCreateW(P7,"X_RDKCENTRAL-COM_AF",1,0);
         DMPackCreateW(P7,"X_RDKCENTRAL-COM_AFTX",1,0);
         DMPackCreateW(P7,"X_RDKCENTRAL-COM_AFRX",1,0);
         DMPackCreateW(P7,"X_COMCAST-COM_CarrierSenseThreshold_Exceeded",1,0);
         DMPackCreateW(P7,"X_RDKCENTRAL-COM_CSTE",1,0);
         DMPackCreateW(P7,"X_COMCAST-COM_RetransmissionMetric",1,0);
         DMPackCreateW(P7,"X_COMCAST-COM_MaximumNoiseFloorOnChannel",1,0);
         DMPackCreateW(P7,"X_COMCAST-COM_MinimumNoiseFloorOnChannel",1,0);
         DMPackCreateW(P7,"X_COMCAST-COM_MedianNoiseFloorOnChannel",1,0);
         DMPackCreateW(P7,"X_COMCAST-COM_RadioStatisticsMeasuringRate",1,1);
         DMPackCreateW(P7,"X_COMCAST-COM_RadioStatisticsMeasuringInterval",1,1);
         DMPackCreateW(P7,"X_COMCAST-COM_StatisticsStartTime",2,0);
         DMPackCreateW(P7,"X_COMCAST-COM_RadioStatisticsEnable",0,1);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 2,"X_COMCAST-COM_ReceivedSignalLevel","128");
          DMPackCreateFunctions(P8,"ReceivedSignalLevel",3,0,2,11);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"ReceivedSignalLevel",1,0);
     P4=DMPackCreateObject(P3, 0,"X_RDKCENTRAL-COM_BandSteering",0);
      DMPackCreateFunctions(P4,"BandSteering",7,10,15,13,18,20,21,22);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"Enable",0,1);
       DMPackCreateW(P5,"APGroup",3,1);
       DMPackCreateW(P5,"Capability",0,0);
       DMPackCreateW(P5,"History",3,0);
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 1,"BandSetting","128");
        DMPackCreateFunctions(P6,"BandSetting",7,0,2,11,16,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"UtilizationThreshold",1,1);
         DMPackCreateW(P7,"RSSIThreshold",1,1);
         DMPackCreateW(P7,"PhyRateThreshold",1,1);
         DMPackCreateW(P7,"OverloadInactiveTime",1,1);
         DMPackCreateW(P7,"IdleInactiveTime",1,1);
     P4=DMPackCreateObject(P3, 1,"SSID","128");
      DMPackCreateFunctions(P4,"SSID",13,0,2,10,11,12,13,15,16,17,18,20,21,22);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"Enable",0,1);
       DMPackCreateParamTS(P5,"Status","string: Up(1),Down(2),Unknown(3),Dormant(4),NotPresent(5),LowerLayerDown(6),Error(7)","uint32/mapped");
       DMPackCreateParamTSW(P5,"Alias","string(64)","string",1);
       DMPackCreateParamTS(P5,"Name","string(64)","string");
       DMPackCreateN(P5,"LastChange",2,0);
       DMPackCreateParamTSW(P5,"LowerLayers","string(1024)","string",1);
       DMPackCreateParam(P5,"BSSID",3);
       DMPackCreateParam(P5,"MACAddress",3);
       DMPackCreateParamTSW(P5,"SSID","string(32)","string",1);
       DMPackCreateParamTS(P5,"X_COMCAST-COM_DefaultSSID","string(32)","string");
       DMPackCreateW(P5,"X_CISCO_COM_EnableOnline",0,1);
       DMPackCreateW(P5,"X_CISCO_COM_RouterEnabled",0,1);
       DMPackCreateParamTS(P5,"Repurposed_VapName","string(64)","string");
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 0,"Stats",0);
        DMPackCreateFunctions(P6,"Stats4",4,10,11,12,13);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateN(P7,"BytesSent",2,0);
         DMPackCreateN(P7,"BytesReceived",2,0);
         DMPackCreateN(P7,"PacketsSent",2,0);
         DMPackCreateN(P7,"PacketsReceived",2,0);
         DMPackCreateN(P7,"ErrorsSent",2,0);
         DMPackCreateN(P7,"ErrorsReceived",2,0);
         DMPackCreateN(P7,"UnicastPacketsSent",2,0);
         DMPackCreateN(P7,"UnicastPacketsReceived",2,0);
         DMPackCreateN(P7,"DiscardPacketsSent",2,0);
         DMPackCreateN(P7,"DiscardPacketsReceived",2,0);
         DMPackCreateN(P7,"MulticastPacketsSent",2,0);
         DMPackCreateN(P7,"MulticastPacketsReceived",2,0);
         DMPackCreateN(P7,"BroadcastPacketsSent",2,0);
         DMPackCreateN(P7,"BroadcastPacketsReceived",2,0);
         DMPackCreateN(P7,"UnknownProtoPacketsReceived",2,0);
         DMPackCreateN(P7,"RetransCount",2,0);
         DMPackCreateN(P7,"FailedRetransCount",2,0);
         DMPackCreateN(P7,"RetryCount",2,0);
         DMPackCreateN(P7,"MultipleRetryCount",2,0);
         DMPackCreateN(P7,"ACKFailureCount",2,0);
         DMPackCreateN(P7,"AggregatedPacketCount",2,0);
     P4=DMPackCreateObject(P3, 1,"AccessPoint","128");
      DMPackCreateFunctions(P4,"AccessPoint",13,0,2,10,11,12,13,15,16,17,18,20,21,22);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"Enable",0,1);
       DMPackCreateParamTS(P5,"Status","string: Disabled(1),Enabled(2),Error_Misconfigured(3),Error(4)","uint32/mapped");
       DMPackCreateParamTSW(P5,"Alias","string(64)","string",1);
       DMPackCreateParamTSW(P5,"SSIDReference","string(256)","string",1);
       DMPackCreateW(P5,"SSIDAdvertisementEnabled",0,1);
       DMPackCreateParamTSW(P5,"RetryLimit","unsignedInt[0:255]","uint32",1);
       DMPackCreateParamTSW(P5,"X_CISCO_COM_LongRetryLimit","unsignedInt[0:255]","uint32",1);
       DMPackCreateParam(P5,"WMMCapability",0);
       DMPackCreateParam(P5,"UAPSDCapability",0);
       DMPackCreateW(P5,"WMMEnable",0,1);
       DMPackCreateW(P5,"UAPSDEnable",0,1);
       DMPackCreateParam(P5,"AssociatedDeviceNumberOfEntries",2);
       DMPackCreateW(P5,"X_CISCO_COM_WmmNoAck",1,1);
       DMPackCreateW(P5,"X_CISCO_COM_MulticastRate",1,1);
       DMPackCreateW(P5,"IsolationEnable",0,1);
       DMPackCreateW(P5,"X_CISCO_COM_BssMaxNumSta",1,1);
       DMPackCreateW(P5,"X_CISCO_COM_BssCountStaAsCpe",0,1);
       DMPackCreateParam(P5,"X_CISCO_COM_BssUserStatus",1);
       DMPackCreateW(P5,"X_CISCO_COM_BssHotSpot",0,1);
       DMPackCreateParamTSW(P5,"X_RDKCENTRAL-COM_BeaconRate","string(32)","string",1);
       DMPackCreateW(P5,"X_CISCO_COM_KickAssocDevices",0,1);
       DMPackCreateW(P5,"MaxAssociatedDevices",2,1);
       DMPackCreateW(P5,"X_COMCAST-COM_AssociatedDevicesHighWatermarkThreshold",2,1);
       DMPackCreateParam(P5,"X_COMCAST-COM_AssociatedDevicesHighWatermarkThresholdReached",2);
       DMPackCreateParam(P5,"X_COMCAST-COM_AssociatedDevicesHighWatermark",2);
       DMPackCreateParam(P5,"X_COMCAST-COM_AssociatedDevicesHighWatermarkDate",2);
       DMPackCreateParam(P5,"X_RDKCENTRAL-COM_InterworkingServiceCapability",0);
       DMPackCreateW(P5,"X_RDKCENTRAL-COM_InterworkingServiceEnable",0,1);
       DMPackCreateW(P5,"X_RDKCENTRAL-COM_InterworkingApplySettings",0,1);
       DMPackCreateParam(P5,"X_COMCAST-COM_MAC_FilteringMode",3);
       DMPackCreateW(P5,"X_RDKCENTRAL-COM_ManagementFramePowerControl",1,1);
       DMPackCreateW(P5,"X_RDKCENTRAL-COM_rapidReconnectCountEnable",0,1);
       DMPackCreateParamTSW(P5,"X_RDKCENTRAL-COM_rapidReconnectMaxTime","int[15:1200]","int",1);
       DMPackCreateParam(P5,"X_COMCAST-COM_TXOverflow",2);
       DMPackCreateW(P5,"X_RDKCENTRAL-COM_StatsEnable",0,1);
       DMPackCreateParam(P5,"X_RDKCENTRAL-COM_WirelessManagementImplemented",0);
       DMPackCreateParam(P5,"X_RDKCENTRAL-COM_BSSTransitionImplemented",0);
       DMPackCreateW(P5,"X_RDKCENTRAL-COM_BSSTransitionActivated",0,1);
       DMPackCreateW(P5,"X_RDKCENTRAL-COM_NeighborReportActivated",0,1);
       DMPackCreateW(P5,"Connected_Building_Enabled",0,1);
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 0,"X_RDKCENTRAL-COM_InterworkingElement",0);
        DMPackCreateFunctions(P6,"InterworkingElement",8,10,11,12,13,15,16,17,18);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"AccessNetworkType",2,1);
         DMPackCreateW(P7,"Internet",0,1);
         DMPackCreateW(P7,"ASRA",0,1);
         DMPackCreateW(P7,"ESR",0,1);
         DMPackCreateW(P7,"UESA",0,1);
         DMPackCreateW(P7,"HESSOptionPresent",0,1);
         DMPackCreateW(P7,"HESSID",3,1);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 0,"VenueInfo",0);
          DMPackCreateFunctions(P8,"InterworkingElement_Venue",2,12,17);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Group",2,1);
           DMPackCreateW(P9,"Type",2,1);
       P6=DMPackCreateObject(P5, 0,"X_CISCO_COM_MACFilter",0);
        DMPackCreateFunctions(P6,"MacFilter",11,10,11,12,13,15,16,17,18,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"Enable",0,1);
         DMPackCreateW(P7,"FilterAsBlackList",0,1);
       P6=DMPackCreateObject(P5, 0,"Security",0);
        DMPackCreateFunctions(P6,"Security",11,10,11,12,13,15,16,17,18,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateParam(P7,"ModesSupported",3);
         DMPackCreateW(P7,"ModeEnabled",3,1);
         DMPackCreateParamSWN(P7,"WEPKey",3,"string/hex_string",1,-1);
         DMPackCreateParamSWN(P7,"X_CISCO_COM_WEPKey",3,"string/hex_string",1,-1);
         DMPackCreateParamSWN(P7,"X_COMCAST-COM_WEPKey",3,"string/hex_string",1,-1);
         DMPackCreateParamTSW(P7,"PreSharedKey","hexBinary(32)","string",1);
         DMPackCreateParamTSW(P7,"KeyPassphrase","string(64)","string",1);
         DMPackCreateW(P7,"X_RDKCENTRAL-COM_TransitionDisable",0,1);
         DMPackCreateParamTSW(P7,"SAEPassphrase","string(64)","string",1);
         DMPackCreateParamTS(P7,"X_COMCAST-COM_DefaultKeyPassphrase","string(64)","string");
         DMPackCreateParamTSW(P7,"X_COMCAST-COM_KeyPassphrase","string(64)","string",1);
         DMPackCreateW(P7,"RekeyingInterval",2,1);
         DMPackCreateParamTSW(P7,"X_CISCO_COM_EncryptionMethod","string: TKIP(1),AES(2),AES+TKIP(3)","uint32/mapped",1);
         DMPackCreateW(P7,"RadiusServerIPAddr",3,1);
         DMPackCreateW(P7,"RadiusServerPort",2,1);
         DMPackCreateParamTSW(P7,"RadiusSecret","string(63)","string",1);
         DMPackCreateW(P7,"SecondaryRadiusServerIPAddr",3,1);
         DMPackCreateW(P7,"SecondaryRadiusServerPort",2,1);
         DMPackCreateParamTSW(P7,"SecondaryRadiusSecret","string(63)","string",1);
         DMPackCreateW(P7,"RadiusDASIPAddr",3,1);
         DMPackCreateW(P7,"RadiusDASPort",2,1);
         DMPackCreateParamTSW(P7,"RadiusDASSecret","string(63)","string",1);
         DMPackCreateW(P7,"X_CISCO_COM_RadiusReAuthInterval",1,1);
         DMPackCreateW(P7,"X_CISCO_COM_DefaultKey",1,1);
         DMPackCreateW(P7,"MFPConfig",3,1);
         DMPackCreateW(P7,"Reset",0,1);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 1,"X_CISCO_COM_WEPKey64Bit","16");
          DMPackCreateFunctions(P8,"WEPKey64Bit",7,0,2,13,18,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"WEPKey",3,1);
         P8=DMPackCreateObject(P7, 1,"X_CISCO_COM_WEPKey128Bit","16");
          DMPackCreateFunctions(P8,"WEPKey128Bit",7,0,2,13,18,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"WEPKey",3,1);
         P8=DMPackCreateObject(P7, 0,"X_COMCAST-COM_RadiusSettings",0);
          DMPackCreateFunctions(P8,"RadiusSettings",6,10,11,15,16,20,21);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"RadiusServerRetries",1,1);
           DMPackCreateW(P9,"RadiusServerRequestTimeout",1,1);
           DMPackCreateW(P9,"PMKLifetime",1,1);
           DMPackCreateW(P9,"PMKCaching",0,1);
           DMPackCreateW(P9,"PMKCacheInterval",1,1);
           DMPackCreateW(P9,"MaxAuthenticationAttempts",1,1);
           DMPackCreateW(P9,"BlacklistTableTimeout",1,1);
           DMPackCreateW(P9,"IdentityRequestRetryInterval",1,1);
           DMPackCreateW(P9,"QuietPeriodAfterFailedAuthentication",1,1);
         P8=DMPackCreateObject(P7, 0,"X_RDKCENTRAL-COM_Authenticator",0);
          DMPackCreateFunctions(P8,"Authenticator",4,12,17,20,21);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateParamTSW(P9,"EAPOLKeyTimeout","unsignedInt[100:5000]","uint32",1);
           DMPackCreateW(P9,"EAPOLKeyRetries",2,1);
           DMPackCreateParamTSW(P9,"EAPIdentityRequestTimeout","unsignedInt[0:5000]","uint32",1);
           DMPackCreateW(P9,"EAPIdentityRequestRetries",2,1);
           DMPackCreateParamTSW(P9,"EAPRequestTimeout","unsignedInt[10:5000]","uint32",1);
           DMPackCreateW(P9,"EAPRequestRetries",2,1);
       P6=DMPackCreateObject(P5, 0,"ConnectionControl",0);
        DMPackCreateFunctions(P6,"ConnectionControl",11,10,11,12,13,15,16,17,18,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"ClientForceDisassociation",3,1);
         DMPackCreateW(P7,"ClientDenyAssociation",3,1);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 0,"PreAssocDeny",0);
          DMPackCreateFunctions(P8,"PreAssocDeny",11,10,11,12,13,15,16,17,18,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateParamTSW(P9,"RssiUpThresholdSupported","string(32)","string",0);
           DMPackCreateParamTSW(P9,"RssiUpThreshold","string(32)","string",1);
           DMPackCreateParamTSW(P9,"SnrThresholdSupported","string(32)","string",0);
           DMPackCreateParamTSW(P9,"SnrThreshold","string(32)","string",1);
           DMPackCreateParamTSW(P9,"CuThresholdSupported","string(32)","string",0);
           DMPackCreateParamTSW(P9,"CuThreshold","string(32)","string",1);
           DMPackCreateParamTSW(P9,"BasicDataTransmitRates","string(32)","string",1);
           DMPackCreateParamTSW(P9,"OperationalDataTransmitRates","string(32)","string",1);
           DMPackCreateParamTSW(P9,"SupportedDataTransmitRates","string(32)","string",1);
           DMPackCreateParamTSW(P9,"MinimumAdvertisedMCS","string(32)","string",1);
           DMPackCreateParamTSW(P9,"6GOpInfoMinRate","string(32)","string",1);
         P8=DMPackCreateObject(P7, 0,"PostAssocDisc",0);
          DMPackCreateFunctions(P8,"PostAssocDisc",11,10,11,12,13,15,16,17,18,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateParamTSW(P9,"RssiUpThresholdSupported","string(32)","string",0);
           DMPackCreateParamTSW(P9,"RssiUpThreshold","string(32)","string",1);
           DMPackCreateParamTSW(P9,"SamplingIntervalSupported","string(32)","string",0);
           DMPackCreateParamTSW(P9,"SamplingInterval","string(32)","string",1);
           DMPackCreateParamTSW(P9,"SnrThresholdSupported","string(32)","string",0);
           DMPackCreateParamTSW(P9,"SnrThreshold","string(32)","string",1);
           DMPackCreateParamTSW(P9,"SamplingCountSupported","string(32)","string",0);
           DMPackCreateParamTSW(P9,"SamplingCount","string(32)","string",1);
           DMPackCreateParamTSW(P9,"CuThresholdSupported","string(32)","string",0);
           DMPackCreateParamTSW(P9,"CuThreshold","string(32)","string",1);
       P6=DMPackCreateObject(P5, 0,"WPS",0);
        DMPackCreateFunctions(P6,"WPS",11,10,11,12,13,15,16,17,18,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"Enable",0,1);
         DMPackCreateParam(P7,"ConfigMethodsSupported",3);
         DMPackCreateW(P7,"ConfigMethodsEnabled",3,1);
         DMPackCreateW(P7,"X_CISCO_COM_WpsPushButton",1,1);
         DMPackCreateParam(P7,"X_CISCO_COM_Pin",3);
         DMPackCreateW(P7,"X_CISCO_COM_ActivatePushButton",0,1);
         DMPackCreateW(P7,"X_CISCO_COM_ClientPin",3,1);
         DMPackCreateParam(P7,"X_Comcast_com_Configured",0);
         DMPackCreateW(P7,"X_CISCO_COM_CancelSession",0,1);
       P6=DMPackCreateObject(P5, 2,"AssociatedDevice","128");
        DMPackCreateFunctions(P6,"AssociatedDevice1",8,0,2,5,6,10,11,12,13);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateN(P7,"MACAddress",3,0);
         DMPackCreateN(P7,"AuthenticationState",0,0);
         DMPackCreateParamTSN(P7,"LastDataDownlinkRate","unsignedInt[1000:600000]","uint32",0);
         DMPackCreateParamTSN(P7,"LastDataUplinkRate","unsignedInt[1000:600000]","uint32",0);
         DMPackCreateParamTS(P7,"SignalStrength","int[-200:0]","int");
         DMPackCreateParamTS(P7,"Retransmissions","unsignedInt[0:100]","uint32");
         DMPackCreateParam(P7,"Active",0);
         DMPackCreateParam(P7,"X_COMCAST-COM_OperatingStandard",3);
         DMPackCreateParam(P7,"X_COMCAST-COM_OperatingChannelBandwidth",3);
         DMPackCreateParamTS(P7,"X_COMCAST-COM_SNR","int[0:100]","int");
         DMPackCreateParamTS(P7,"X_RDKCENTRAL-COM_SNR","int[0:100]","int");
         DMPackCreateParam(P7,"X_COMCAST-COM_InterferenceSources",3);
         DMPackCreateParam(P7,"X_COMCAST-COM_DataFramesSentAck",2);
         DMPackCreateParam(P7,"X_COMCAST-COM_DataFramesSentNoAck",2);
         DMPackCreateParam(P7,"X_COMCAST-COM_BytesSent",2);
         DMPackCreateParam(P7,"X_COMCAST-COM_BytesReceived",2);
         DMPackCreateParam(P7,"X_COMCAST-COM_RSSI",1);
         DMPackCreateParam(P7,"X_COMCAST-COM_MinRSSI",1);
         DMPackCreateParam(P7,"X_COMCAST-COM_MaxRSSI",1);
         DMPackCreateParam(P7,"X_COMCAST-COM_Disassociations",2);
         DMPackCreateParam(P7,"X_COMCAST-COM_AuthenticationFailures",2);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 0,"Stats",0);
          DMPackCreateFunctions(P8,"Stats",3,12,15,10);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"InstantMeasurementsEnable",0,1);
           DMPackCreateN(P9,"BytesSent",2,0);
           DMPackCreateN(P9,"BytesReceived",2,0);
           DMPackCreateN(P9,"PacketsSent",2,0);
           DMPackCreateN(P9,"PacketsReceived",2,0);
           DMPackCreateN(P9,"ErrorsSent",2,0);
           DMPackCreateN(P9,"RetransCount",2,0);
           DMPackCreateN(P9,"FailedRetransCount",2,0);
           DMPackCreateN(P9,"RetryCount",2,0);
           DMPackCreateN(P9,"MultipleRetryCount",2,0);
       P6=DMPackCreateObject(P5, 4,"X_CISCO_COM_MacFilterTable","64");
        DMPackCreateFunctions(P6,"MacFiltTab",11,0,2,3,4,5,6,13,18,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"MACAddress",3,1);
         DMPackCreateW(P7,"DeviceName",3,1);
       P6=DMPackCreateObject(P5, 0,"X_RDKCENTRAL-COM_DPP",0);
        DMPackCreateFunctions(P6,"DPP",7,12,13,17,18,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateParamTSW(P7,"Version","unsignedInt[1:2]","uint32",1);
         DMPackCreateParamTSW(P7,"PrivateSigningKey","string(512)","string",1);
         DMPackCreateParamTSW(P7,"PrivateReconfigAccessKey","string(512)","string",1);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 1,"STA","128");
          DMPackCreateFunctions(P8,"DPP_STA",13,0,2,10,11,12,13,15,16,17,18,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateParamTSW(P9,"ClientMac","string(17)","string",1);
           DMPackCreateParamTSW(P9,"InitiatorBootstrapSubjectPublicKeyInfo","string(256)","string",1);
           DMPackCreateParamTSW(P9,"ResponderBootstrapSubjectPublicKeyInfo","string(256)","string",1);
           DMPackCreateParamTSW(P9,"Channels","string(256)","string",1);
           DMPackCreateParamTSW(P9,"MaxRetryCount","unsignedInt[5:120]","uint32",1);
           DMPackCreateW(P9,"Activate",0,1);
           DMPackCreateParamTSW(P9,"ActivationStatus","string(32)","string",0);
           DMPackCreateParamTSW(P9,"EnrolleeResponderStatus","string(32)","string",0);
          P9=DMPackCreatePNode(P8,"objects");
           P10=DMPackCreateObject(P9, 0,"Credential",0);
            DMPackCreateFunctions(P10,"DPP_STA_Credential",7,0,2,13,18,20,21,22);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateParamTSW(P11,"KeyManagement","string(32)","string",1);
             DMPackCreateParamTSW(P11,"psk_hex","string(64)","string",0);
             DMPackCreateParamTSW(P11,"password","string(64)","string",0);
       P6=DMPackCreateObject(P5, 0,"X_RDKCENTRAL-COM_InterworkingService",0);
        DMPackCreateFunctions(P6,"InterworkingService",2,13,18);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"Parameters",3,1);
       P6=DMPackCreateObject(P5, 0,"X_RDKCENTRAL-COM_Passpoint",0);
        DMPackCreateFunctions(P6,"Passpoint",4,10,13,15,18);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"Capability",0,0);
         DMPackCreateW(P7,"Enable",0,1);
         DMPackCreateW(P7,"Parameters",3,1);
         DMPackCreateW(P7,"WANMetrics",3,0);
         DMPackCreateW(P7,"Stats",3,0);
     P4=DMPackCreateObject(P3, 0,"NeighboringWiFiDiagnostic",0);
      DMPackCreateFunctions(P4,"NeighboringWiFiDiagnostic",4,10,13,15,18);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"Enable",0,1);
       DMPackCreateParamTSW(P5,"DiagnosticsState","string(64)","string",1);
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 2,"Result","128");
        DMPackCreateFunctions(P6,"NeighboringScanResult",6,0,2,5,11,12,13);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateParamTS(P7,"Radio","string(64)","string");
         DMPackCreateParamTS(P7,"SSID","string(32)","string");
         DMPackCreateParam(P7,"BSSID",3);
         DMPackCreateParam(P7,"Mode",3);
         DMPackCreateParamTS(P7,"Channel","unsignedInt[1:255]","uint32");
         DMPackCreateParamTS(P7,"SignalStrength","int[-200:0]","int");
         DMPackCreateParamTS(P7,"SecurityModeEnabled","string(64)","string");
         DMPackCreateParamTS(P7,"EncryptionMode","string(64)","string");
         DMPackCreateParam(P7,"OperatingFrequencyBand",3);
         DMPackCreateParamTS(P7,"SupportedStandards","string(64)","string");
         DMPackCreateParam(P7,"OperatingStandards",3);
         DMPackCreateParam(P7,"OperatingChannelBandwidth",3);
         DMPackCreateParam(P7,"BeaconPeriod",2);
         DMPackCreateParamTS(P7,"Noise","int[-200:0]","int");
         DMPackCreateParamTS(P7,"BasicDataTransferRates","string(256)","string");
         DMPackCreateParamTS(P7,"SupportedDataTransferRates","string(256)","string");
         DMPackCreateParam(P7,"DTIMPeriod",2);
         DMPackCreateParam(P7,"X_COMCAST-COM_ChannelUtilization",2);
     P4=DMPackCreateObject(P3, 0,"X_RDKCENTRAL-COM_ATM",0);
      DMPackCreateFunctions(P4,"ATM",5,10,15,20,21,22);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateParam(P5,"Capable",0);
       DMPackCreateW(P5,"Enable",0,1);
       DMPackCreateParam(P5,"APGroupNumberOfEntries",2);
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 1,"APGroup","4");
        DMPackCreateFunctions(P6,"APGroup",8,0,2,12,17,13,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateParam(P7,"APList",3);
         DMPackCreateW(P7,"AirTimePercent",2,1);
         DMPackCreateParam(P7,"StaNumberOfEntries",2);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 3,"Sta","128");
          DMPackCreateFunctions(P8,"Sta",11,0,2,3,4,12,13,17,18,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"MACAddress",3,1);
           DMPackCreateW(P9,"AirTimePercent",2,1);
   P2=DMPackCreateObject(P1, 0,"Logging",0);
    DMPackCreateFunctions(P2,"Logging",2,10,15);
    P3=DMPackCreatePNode(P2,"parameters");
     DMPackCreateW(P3,"FlushAllLogs",0,1);
 return P0;
}
