/*
DM PACK
created with:
python /workspace/home/himal.d/MatterProtocol/build-raspberrypi4-64-rdk-broadband/tmp/work/cortexa72-rdk-linux/ccsp-dhcp-mgr/rdkb-2024q3-kirkstone+git999-r0/recipe-sysroot-native/usr/bin/dm_pack_code_gen.py /workspace/home/himal.d/MatterProtocol/meta-cmf/../rdkb/components/opensource/ccsp/DhcpManager/config/TR181-DHCPMgr.XML /workspace/home/himal.d/MatterProtocol/meta-cmf/../rdkb/components/opensource/ccsp/DhcpManager/source/DHCPMgrSsp/dm_pack_datamodel.c
*/

#include "ansc_platform.h"
#include "ansc_xml_dom_parser_interface.h"
#include "dm_pack_xml_helper.h"
PVOID DMPackCreateDataModelXML(){
 PANSC_XML_DOM_NODE_OBJECT P0,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11;
 P0=DMPackCreatePNode(0,"dataModelInfo");
  P1=DMPackCreateNode(P0,"version","1",1);
  P1=DMPackCreateNode(P0,"moduleName","DHCPMgr",7);
  P1=DMPackCreatePNode(P0,"author");
  P1=DMPackCreatePNode(P0,"description");
  P1=DMPackCreatePNode(P0,"library");
   P2=DMPackCreateNode(P1,"func_Init","COSA_Init",9);
  P1=DMPackCreatePNode(P0,"objects");
   P2=DMPackCreateObject(P1, 0,"DHCPv4",0);
    DMPackCreateFunctions(P2,"DHCPv4",4,10,11,12,13);
    P3=DMPackCreatePNode(P2,"parameters");
     DMPackCreateParam(P3,"ClientNumberOfEntries",2);
    P3=DMPackCreatePNode(P2,"objects");
     P4=DMPackCreateObject(P3, 3,"Client","128");
      DMPackCreateFunctions(P4,"Client",15,0,2,3,4,10,11,12,13,15,16,17,18,20,21,22);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"Enable",0,1);
       DMPackCreateParamTS(P5,"Alias","string(64)","string");
       DMPackCreateParamTSW(P5,"X_RDK_LinuxInterface","string(256)","string",1);
       DMPackCreateParamTSW(P5,"X_CISCO_COM_BootFileName","string(256)","string",1);
       DMPackCreateParamTSW(P5,"Interface","string(256)","string",1);
       DMPackCreateParamTS(P5,"Status","string: Disabled(1),Enabled(2),Error_Misconfigured(3),Error(4)","uint32/mapped");
       DMPackCreateParamTS(P5,"DHCPStatus","string: Init(1),Selecting(2),Requesting(3),Rebinding(4),Bound(5),Renewing(6)","uint32/mapped");
       DMPackCreateW(P5,"Renew",0,1);
       DMPackCreateParamS(P5,"IPAddress",3,"uint32/ip4_addr");
       DMPackCreateParamS(P5,"SubnetMask",3,"uint32/ip4_addr");
       DMPackCreateParamTS(P5,"IPRouters","string(256)","string");
       DMPackCreateParamTS(P5,"DNSServers","string(256)","string");
       DMPackCreateParamTSN(P5,"LeaseTimeRemaining","int[-1:]","int",0);
       DMPackCreateParamS(P5,"DHCPServer",3,"uint32/ip4_addr");
       DMPackCreateParam(P5,"SentOptionNumberOfEntries",2);
       DMPackCreateParam(P5,"ReqOptionNumberOfEntries",2);
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 3,"SentOption","128");
        DMPackCreateFunctions(P6,"SentOption",15,0,2,3,4,10,11,12,13,15,16,17,18,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"Enable",0,1);
         DMPackCreateParamTSW(P7,"Alias","string(64)","string",1);
         DMPackCreateParamTSW(P7,"Tag","unsignedInt[1:254]","uint32",1);
         DMPackCreateParamTSW(P7,"Value","hexBinary(255)","string",1);
       P6=DMPackCreateObject(P5, 3,"ReqOption","128");
        DMPackCreateFunctions(P6,"ReqOption",15,0,2,3,4,10,11,12,13,15,16,17,18,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"Enable",0,1);
         DMPackCreateParamTSW(P7,"Order","unsignedInt[1:]","uint32",1);
         DMPackCreateParamTSW(P7,"Alias","string(64)","string",1);
         DMPackCreateParamTSW(P7,"Tag","unsignedInt[1:254]","uint32",1);
         DMPackCreateParamTSW(P7,"Value","hexBinary(255)","string",1);
     P4=DMPackCreateObject(P3, 0,"Server",0);
      DMPackCreateFunctions(P4,"Server",11,10,11,12,13,15,16,17,18,20,21,22);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"Enable",0,1);
       DMPackCreateW(P5,"StaticClientsData",3,1);
       DMPackCreateW(P5,"Lan",3,1);
       DMPackCreateParam(P5,"PoolNumberOfEntries",2);
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 3,"Pool","128");
        DMPackCreateFunctions(P6,"Pool",15,0,2,3,4,10,11,12,13,15,16,17,18,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"Enable",0,1);
         DMPackCreateW(P7,"X_CISCO_COM_TimeOffset",1,1);
         DMPackCreateParamTS(P7,"Status","string: Disabled(1),Enabled(2),Error_Misconfigured(3),Error(4)","uint32/mapped");
         DMPackCreateParamTSW(P7,"Alias","string(64)","string",1);
         DMPackCreateParamTSW(P7,"Order","unsignedInt[1:]","uint32",1);
         DMPackCreateParamTSW(P7,"Interface","string(256)","string",1);
         DMPackCreateParamTSW(P7,"VendorClassID","string(255)","string",1);
         DMPackCreateW(P7,"VendorClassIDExclude",0,1);
         DMPackCreateParamTSW(P7,"VendorClassIDMode","string: Exact(1),Prefix(2),Suffix(3),Substring(4)","uint32/mapped",1);
         DMPackCreateParamTSW(P7,"ClientID","hexBinary(255)","string",1);
         DMPackCreateW(P7,"ClientIDExclude",0,1);
         DMPackCreateParamTSW(P7,"UserClassID","hexBinary(255)","string",1);
         DMPackCreateW(P7,"UserClassIDExclude",0,1);
         DMPackCreateW(P7,"Chaddr",3,1);
         DMPackCreateW(P7,"ChaddrMask",3,1);
         DMPackCreateW(P7,"ChaddrExclude",0,1);
         DMPackCreateParamSWN(P7,"MinAddress",3,"uint32/ip4_addr",1,-1);
         DMPackCreateParamSWN(P7,"MaxAddress",3,"uint32/ip4_addr",1,-1);
         DMPackCreateParamTSW(P7,"ReservedAddresses","string(512)","string",1);
         DMPackCreateParamSWN(P7,"SubnetMask",3,"uint32/ip4_addr",1,-1);
         DMPackCreateParamTSW(P7,"DNSServers","string(64)","string",1);
         DMPackCreateW(P7,"DNSServersEnabled",0,1);
         DMPackCreateParamTSW(P7,"DomainName","string(64)","string",1);
         DMPackCreateParamTSW(P7,"IPRouters","string(64)","string",1);
         DMPackCreateParamTSW(P7,"LeaseTime","int[-1:]","int",1);
         DMPackCreateParam(P7,"StaticAddressNumberOfEntries",2);
         DMPackCreateParam(P7,"OptionNumberOfEntries",2);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 4,"StaticAddress","128");
          DMPackCreateFunctions(P8,"StaticAddress",17,0,2,5,6,3,4,10,11,12,13,15,16,17,18,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateParamTSW(P9,"Chaddr","string(18)","string",1);
           DMPackCreateParamSWN(P9,"Yiaddr",3,"uint32/ip4_addr",1,-1);
           DMPackCreateW(P9,"X_CISCO_COM_DeviceName",3,1);
           DMPackCreateParamTSW(P9,"X_CISCO_COM_Comment","string(255)","string",1);
         P8=DMPackCreateObject(P7, 3,"Option","128");
          DMPackCreateFunctions(P8,"Option1",15,0,2,3,4,10,11,12,13,15,16,17,18,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateParamTSW(P9,"Tag","unsignedInt[1:254]","uint32",1);
           DMPackCreateParamTSW(P9,"Value","hexBinary(255)","string",1);
         P8=DMPackCreateObject(P7, 2,"Client","128");
          DMPackCreateFunctions(P8,"Client2",15,0,2,5,6,10,11,12,13,15,16,17,18,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateParamTSW(P9,"X_CISCO_COM_Comment","string(256)","string",1);
           DMPackCreateParamTS(P9,"X_CISCO_COM_Interface","string(256)","string");
           DMPackCreateParamTS(P9,"X_CISCO_COM_HostName","string(64)","string");
           DMPackCreateParamTS(P9,"ClassId","string(64)","string");
           DMPackCreateParam(P9,"Chaddr",3);
           DMPackCreateParam(P9,"Active",0);
           DMPackCreateParam(P9,"IPv4AddressNumberOfEntries",2);
           DMPackCreateParam(P9,"OptionNumberOfEntries",2);
          P9=DMPackCreatePNode(P8,"objects");
           P10=DMPackCreateObject(P9, 1,"IPv4Address","128");
            DMPackCreateFunctions(P10,"IPv4Address2",6,0,2,10,11,12,13);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateParamS(P11,"IPAddress",3,"uint32/ip4_addr");
             DMPackCreateParamTS(P11,"LeaseTimeRemaining","dateTime","string");
             DMPackCreateParamTS(P11,"X_CISCO_COM_LeaseTimeCreation","dateTime","string");
           P10=DMPackCreateObject(P9, 1,"Option","128");
            DMPackCreateFunctions(P10,"Option2",6,0,2,10,11,12,13);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateParamTS(P11,"Tag","unsignedInt[0:255]","uint32");
             DMPackCreateParamTS(P11,"Value","hexBinary(255)","string");
   P2=DMPackCreateObject(P1, 0,"DHCPv6",0);
    DMPackCreateFunctions(P2,"DHCPv6",4,10,11,12,13);
    P3=DMPackCreatePNode(P2,"parameters");
     DMPackCreateParam(P3,"ClientNumberOfEntries",2);
    P3=DMPackCreatePNode(P2,"objects");
     P4=DMPackCreateObject(P3, 3,"Client","128");
      DMPackCreateFunctions(P4,"Client3",15,0,2,3,4,10,11,12,13,15,16,17,18,20,21,22);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"Enable",0,1);
       DMPackCreateParamTSW(P5,"Alias","string(64)","string",1);
       DMPackCreateParamTSW(P5,"X_RDK_LinuxInterface","string(256)","string",1);
       DMPackCreateParamTSW(P5,"Interface","string(256)","string",1);
       DMPackCreateParamTS(P5,"Status","string: Disabled(1),Enabled(2),Error_Misconfigured(3),Error(4)","uint32/mapped");
       DMPackCreateParamTS(P5,"DUID","hexBinary(130)","string");
       DMPackCreateW(P5,"RequestAddresses",0,1);
       DMPackCreateW(P5,"RequestPrefixes",0,1);
       DMPackCreateW(P5,"RapidCommit",0,1);
       DMPackCreateW(P5,"Renew",0,1);
       DMPackCreateParamTSW(P5,"SuggestedT1","int[-1:]","int",1);
       DMPackCreateParamTSW(P5,"SuggestedT2","int[-1:]","int",1);
       DMPackCreateParam(P5,"SupportedOptions",3);
       DMPackCreateW(P5,"RequestedOptions",3,1);
       DMPackCreateParam(P5,"ServerNumberOfEntries",2);
       DMPackCreateParam(P5,"SentOptionNumberOfEntries",2);
       DMPackCreateParam(P5,"ReceivedOptionNumberOfEntries",2);
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 2,"Server","128");
        DMPackCreateFunctions(P6,"Server2",8,0,2,5,6,10,11,12,13);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateParam(P7,"SourceAddress",3);
         DMPackCreateParamTS(P7,"DUID","hexBinary(130)","string");
         DMPackCreateParamTS(P7,"InformationRefreshTime","dateTime","string");
       P6=DMPackCreateObject(P5, 3,"SentOption","128");
        DMPackCreateFunctions(P6,"SentOption1",15,0,2,3,4,10,11,12,13,15,16,17,18,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"Enable",0,1);
         DMPackCreateParamTSW(P7,"Alias","string(64)","string",1);
         DMPackCreateParamTSW(P7,"Tag","unsignedInt[0:65535]","uint32",1);
         DMPackCreateParamTSW(P7,"Value","hexBinary(65535)","string",1);
       P6=DMPackCreateObject(P5, 2,"ReceivedOption","128");
        DMPackCreateFunctions(P6,"ReceivedOption",8,0,2,5,6,10,11,12,13);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateParamTS(P7,"Tag","unsignedInt[0:65535]","uint32");
         DMPackCreateParamTS(P7,"Value","hexBinary(65535)","string");
         DMPackCreateParam(P7,"Server",3);
       P6=DMPackCreateObject(P5, 0,"X_RDKCENTRAL-COM_RcvOption",0);
        DMPackCreateFunctions(P6,"dhcp6c_mapt_mape",3,10,12,13);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"MapTransportMode",3,0);
         DMPackCreateW(P7,"MapBRPrefix",3,0);
         DMPackCreateW(P7,"MapRuleIPv4Prefix",3,0);
         DMPackCreateW(P7,"MapRuleIPv6Prefix",3,0);
         DMPackCreateW(P7,"MapEALen",2,0);
         DMPackCreateParam(P7,"MapPSIDOffset",2);
         DMPackCreateW(P7,"MapPSIDLen",2,0);
         DMPackCreateW(P7,"MapPSID",2,0);
         DMPackCreateW(P7,"MapIsFMR",0,0);
         DMPackCreateW(P7,"MapIpv4Address",3,0);
     P4=DMPackCreateObject(P3, 0,"Server",0);
      DMPackCreateFunctions(P4,"Server3",11,10,11,12,13,15,16,17,18,20,21,22);
      P5=DMPackCreatePNode(P4,"parameters");
       DMPackCreateW(P5,"Enable",0,1);
       DMPackCreateParamTSW(P5,"X_CISCO_COM_Type","string: Stateful(1),Stateless(2)","uint32/mapped",1);
       DMPackCreateParam(P5,"PoolNumberOfEntries",2);
      P5=DMPackCreatePNode(P4,"objects");
       P6=DMPackCreateObject(P5, 3,"Pool","128");
        DMPackCreateFunctions(P6,"Pool1",13,0,2,3,4,10,12,13,15,17,18,20,21,22);
        P7=DMPackCreatePNode(P6,"parameters");
         DMPackCreateW(P7,"Enable",0,1);
         DMPackCreateParamTS(P7,"Status","string: Disabled(1),Enabled(2),Error_Misconfigured(3),Error(4)","uint32/mapped");
         DMPackCreateParamTSW(P7,"Alias","string(64)","string",1);
         DMPackCreateParamTSW(P7,"Order","unsignedInt[1:]","uint32",1);
         DMPackCreateParamTSW(P7,"Interface","string(256)","string",1);
         DMPackCreateParamTSW(P7,"DUID","hexBinary(130)","string",1);
         DMPackCreateW(P7,"DUIDExclude",0,1);
         DMPackCreateParamTSW(P7,"VendorClassID","hexBinary(65535)","string",1);
         DMPackCreateW(P7,"VendorClassIDExclude",0,1);
         DMPackCreateParamTSW(P7,"UserClassID","hexBinary(65535)","string",1);
         DMPackCreateW(P7,"UserClassIDExclude",0,1);
         DMPackCreateW(P7,"SourceAddress",3,1);
         DMPackCreateW(P7,"SourceAddressMask",3,1);
         DMPackCreateW(P7,"SourceAddressExclude",0,1);
         DMPackCreateW(P7,"IANAEnable",0,1);
         DMPackCreateW(P7,"IANAManualPrefixes",3,1);
         DMPackCreateParam(P7,"IANAPrefixes",3);
         DMPackCreateW(P7,"PrefixRangeBegin",3,1);
         DMPackCreateW(P7,"PrefixRangeEnd",3,1);
         DMPackCreateW(P7,"IAPDEnable",0,1);
         DMPackCreateW(P7,"IAPDManualPrefixes",3,1);
         DMPackCreateParam(P7,"IAPDPrefixes",3);
         DMPackCreateParamTSW(P7,"IAPDAddLength","unsignedInt[:64]","uint32",1);
         DMPackCreateW(P7,"X_RDKCENTRAL-COM_DNSServersEnabled",0,1);
         DMPackCreateW(P7,"X_RDKCENTRAL-COM_DNSServers",3,1);
         DMPackCreateParam(P7,"ClientNumberOfEntries",2);
         DMPackCreateParam(P7,"OptionNumberOfEntries",2);
        P7=DMPackCreatePNode(P6,"objects");
         P8=DMPackCreateObject(P7, 2,"Client","128");
          DMPackCreateFunctions(P8,"Client4",15,0,2,5,6,10,11,12,13,15,16,17,18,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateParam(P9,"SourceAddress",3);
           DMPackCreateParam(P9,"Active",0);
           DMPackCreateParam(P9,"IPv6AddressNumberOfEntries",2);
           DMPackCreateParam(P9,"IPv6PrefixNumberOfEntries",2);
           DMPackCreateParam(P9,"OptionNumberOfEntries",2);
          P9=DMPackCreatePNode(P8,"objects");
           P10=DMPackCreateObject(P9, 1,"IPv6Address","128");
            DMPackCreateFunctions(P10,"IPv6Address2",6,0,2,10,11,12,13);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateParam(P11,"IPAddress",3);
             DMPackCreateParamTS(P11,"PreferredLifetime","dateTime","string");
             DMPackCreateParamTS(P11,"ValidLifetime","dateTime","string");
           P10=DMPackCreateObject(P9, 1,"IPv6Prefix","128");
            DMPackCreateFunctions(P10,"IPv6Prefix1",6,0,2,10,11,12,13);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateParam(P11,"Prefix",3);
             DMPackCreateParamTS(P11,"PreferredLifetime","dateTime","string");
             DMPackCreateParamTS(P11,"ValidLifetime","dateTime","string");
           P10=DMPackCreateObject(P9, 1,"Option","128");
            DMPackCreateFunctions(P10,"Option3",6,0,2,10,11,12,13);
            P11=DMPackCreatePNode(P10,"parameters");
             DMPackCreateParamTS(P11,"Tag","unsignedInt[0:65535]","uint32");
             DMPackCreateParamTS(P11,"Value","hexBinary(65535)","string");
         P8=DMPackCreateObject(P7, 3,"Option","128");
          DMPackCreateFunctions(P8,"Option4",15,0,2,3,4,10,11,12,13,15,16,17,18,20,21,22);
          P9=DMPackCreatePNode(P8,"parameters");
           DMPackCreateW(P9,"Enable",0,1);
           DMPackCreateParamTSW(P9,"Alias","string(64)","string",1);
           DMPackCreateParamTSW(P9,"Tag","unsignedInt[0:65535]","uint32",1);
           DMPackCreateParamTSW(P9,"Value","hexBinary(65535)","string",1);
           DMPackCreateParamTSW(P9,"PassthroughClient","string(256)","string",1);
 return P0;
}
